PR/PD-51: 공용컴포넌트 Layout(Header,Footer)작업했습니다.
PurpleDynamics/PEA_Project pull request #10
Opened 2024-01-25 18:35 UTC by snkchan

## 🎯 작업 내용

## 작업이미지
-  <img width="1279" alt="Layout_PR" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/a0886b83-8eb6-47ee-80da-87a8412691df">

-  [design:Header componet작업했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/68f7a77423aa5e3267eb016d243dfcb355b653ff)
  - Header의 높이는 11rem으로 설정해두었습니다. 
     추후에  page컴포넌트 작업하실 분들은 margin-top or padding-top 11rem으로 설정해주시고 작업하셔야합니다.
## react-icon사용방법 모두 읽어주세요
### 1번
- <img width="637" alt="image" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/580656aa-2372-4301-a715-2fa933044c3b"> <br/>
   아이콘을 불러오실땐  위와같이 BsIcon에서 맞는 아이콘 찾아서 불러오시면 됩니다.
### 2번
- <img width="400" alt="Layout_PR(5)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/d5e7266c-9ba1-446b-8287-77897ff5b44d"> <br/>
 컨벤션에 맞추기위해서 위의 사진처럼 (Bs)IconName = styled(BsIconName) 이런식으로 사용하시고 
 스타일 컴포넌트객체인  S안에 넣어서 사용하시는걸로하면 좋을것 같습니다.
- <img width="291" alt="Layout_PR(4)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/7944669a-76a8-48b9-ba11-6382ee026bcd">

- [design: Footer Componet작업했습니다.]
(https://github.com/PurpleDynamics/PEA_Project/commit/d4ee3d2e0df9066e33253c3187f9fe8a94daa24d)

## 참고해주세요
 ### 1.로고이미지 경로 작성한 방법.
  - 로고 이미지는 파일경로는 github이슈에서 이미지 업로드시 나오는 사진경로를 복사 -> 복사한경로를 경로줄이는 사이트에서 간략하게 만든 주소를 로고이미지 경로로 작성해 두었습니다.
  - 문제가 생길수도 있을 것 같아서 확인해주세요다들~~
 ### 2.공용컴포넌트 SearchBar에대해
 - 헤더에 사용될 검색창이 채팅 컴포넌트에도 재사용 될 것 같아서 
 <img width="149" alt="Layout_PR(6)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/e7f37fda-3393-45bb-a1f0-f0a49f04748e">
다음과 같은 구조로 폴더를 생성했는데 의견 부탁드립니다.
<br/>

<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] PR 제목 (컨벤션에 따랐는지) 확인 
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!! 

### 👍 문제가 없다고 생각된다면...
1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...
1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.
```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```
2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-01-26 06:14 UTC, ijimlnosk approved these changes

2024-01-27 14:51 UTC, jjjiyoung0130 requested changes

2024-01-27 14:51 UTC, jjjiyoung0130 commented on src/components/search-bar.jsx
> +	background-color: #eee;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - reference-tokens의 color에 맞춰서 작성해주세요.

2024-01-27 14:51 UTC, jjjiyoung0130 commented on src/components/search-bar.jsx
컴포넌트와 관련된 폴더 구조는 금일 회의 내용대로 수정해주시기 바랍니다.

- components
  - `components/common`
      - `index.js` 배치
      - 공용 component 배치
  - `components/{page_name}`
      - `index.js` 배치
      - {page_name} 에 해당하는 component 배치

2024-01-28 15:12 UTC, snkchan commented on src/components/search-bar.jsx
- [fix: 새로운 폴더구조에 맞게 파일이동](https://github.com/PurpleDynamics/PEA_Project/pull/10/commits/7f7050d9e3918eef404b4d3beedf06223b33dd6d)

 - 수정했습니다.

2024-01-28 15:13 UTC, snkchan commented on src/components/search-bar.jsx
> +	background-color: #eee;
- [chore: 컨밴션에 맞게 코드 수정](https://github.com/PurpleDynamics/PEA_Project/pull/10/commits/374d0cf06a4a9935f2ed85b79ba7df9fd04c2490)

 수정완료!

2024-01-28 15:19 UTC, TransparentDeveloper requested changes
👍

2024-01-28 15:19 UTC, TransparentDeveloper commented on src/libs/react-router-dom/router.jsx
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 왜 수정이 된건지 모르겠습니다.? 수정이후 버전으로 쓰면 베럴파일 쓰는 의미가 없지 않나요?

2024-01-28 15:21 UTC, TransparentDeveloper requested changes
✌️

2024-01-28 15:21 UTC, TransparentDeveloper commented on src/assets/images/Logo.png
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 파일 이름은 케밥케이스죠..

2024-01-28 15:23 UTC, snkchan commented on src/assets/images/Logo.png
- [remove: 불필요한 파일 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/10/commits/4a53dc04ba717accec2aaa249d3d8a069494b999)
 삭제완료😱

2024-01-28 15:25 UTC, TransparentDeveloper approved these changes

2024-01-28 15:25 UTC, hayoung78 approved these changes

2024-01-28 15:25 UTC, jjjiyoung0130 approved these changes

2024-01-28 15:25 UTC, merged