PR:PD-38: 공용컴포넌트 "ProductCard" 작성했습니다.
PurpleDynamics/PEA_Project pull request #15
Opened 2024-01-28 17:39 UTC by TransparentDeveloper

## 🎯 작업 내용

- [feat: 생성일부터 조회일까지의 기간을 출력하는 함수 작성](https://github.com/PurpleDynamics/PEA_Project/commit/5fc9c63735f8134fa2b6d443eda004833a6df723)
  - 전달 받은 일로부터 오늘까지의 기간이 문자열로 출력됩니다.
  - 잘못된 날짜가 입력된다면 "invalid_date" 라는 문자열이 반환됩니다.
  - 24 시간 미만 이라면 "x 시간 전" 으로 반환됩니다.
  - 30 일 미만 이라면 "x 일 전" 으로 반환됩니다.
  - 365 일 미만 이라면 "x 달 전" 으로 반환됩니다.
  - 그 이상의 차이가 있다며누 "x 년 전" 으로 반환합니다.

<br/>

------------

<br/>

- [design: highlighted-text 공용컴포넌트 생성](https://github.com/PurpleDynamics/PEA_Project/commit/a32a03113c16ef813d0f3d96708ada01357d269f)
  - 전달되는 문자열의 색상을 변형시켜 강조효과를 주는 컴포넌트 입니다.

<br/>

### ✋ 사용하려면,,?

- _코드_
```js
<>나를<HighlightedText color={COLOR.PALLTE.base}>강조</HighlightedText>해줘</>
```

- _출력물_
<img width="139" alt="HighlightedText" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/22a7e268-739c-40cf-bd18-f57897b446fe">

<br/>

------------

<br/>

- [design: 공용컴포넌트 ProductCard 완성](https://github.com/PurpleDynamics/PEA_Project/commit/f095a9e5acdaf292cbab8e3eb1eba4e60d19c5a2)
  - 상품을 전시하는 컴포넌트입니다.
  - 호버/클릭 에 대해 css 적용이 달라집니다.
  - 클릭 에 대한 콜백함수를 전달받아, 페이지를 이동시키는 등의 작업을 할 수 있습니다.
  - '찜'/'관심 표현'에 대한 상태를 자체적으로 관리합니다. (외부에서 초기값을 지정할 수 있습니다.)
  - 'disabled' 값이 true 일 경우, 클릭 등의 이벤트가 발생하지 않습니다.
  - category 는 최소 1개, 최대 2개까지 노출됩니다.

<br/>
  
### ✋ 사용하려면,,?

 #### 일반
- _코드_
```js
<ProductCard
	productId={5}
	title="비둘기 치킨"
	imgUrl="https://source.unsplash.com/random/?pigeon"
	createdAt="2019-12-25"
	price={10000}
	interestCount={10}
	chattingCount={20}
	categoriesArray={["식품", "애완동물용품", "기타"]}
/>
```

- _출력물_
<img width="139" alt="HighlightedText" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/d9ea262a-2417-4381-8ddb-a98eca760010">

<br/>

---------

<br/>

#### 비활성화
- _코드_
```js
<ProductCard
	productId={5}
	title="비둘기 치킨"
	imgUrl="https://source.unsplash.com/random/?pigeon"
	createdAt="2019-12-25"
	price={10000}
	interestCount={10}
	chattingCount={20}
	categoriesArray={["식품", "애완동물용품", "기타"]}
        disabled = {true}
/>
```

- _출력물_
<img width="139" alt="스크린샷 2024-01-29 오전 2 35 40" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/4a4b0c85-728c-4014-a293-9223ba5c02b3">

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] PR 제목 (컨벤션에 따랐는지) 확인 
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!! 

### 👍 문제가 없다고 생각된다면...
1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...
1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.
```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```
2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-01-28 18:58 UTC, snkchan approved these changes
굉장하네요.... 한가지 사소한거만 수정하면 고칠게없어보입니다...2따봉 드립니다.👍👍

2024-01-28 18:58 UTC, snkchan commented on src/components/commons/product-card.jsx
> +					box-shadow: ${COLOR.COMMON[200]} 0 0.5rem;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
box-shadow: none; 이코드는 중복되서 불필요해 보이는거 같습니다.

2024-01-29 06:24 UTC, TransparentDeveloper commented on src/components/commons/product-card.jsx
> +					box-shadow: ${COLOR.COMMON[200]} 0 0.5rem;
- [chore: 불필요하게 명시된 속성 제거](https://github.com/PurpleDynamics/PEA_Project/pull/15/commits/275eb5f8df0d5738e81778b7736854db115fd52c) 
  -  감사합니다. 😊 못보고 지나쳤네요;; ㅎㅎ

2024-01-29 09:25 UTC, hayoung78 requested changes

2024-01-29 09:25 UTC, hayoung78 commented on src/components/commons/product-card.jsx
> +	BsHearts,
아주 좋습니다 
그 으 런 데 ..
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/e7157c6d-40ca-4d32-8b01-fa3e84565413)


# Description
찜하트아이콘이 안바뀌었습니다. ^__^
그때 채윤님이 알려준대로 바꾸기로한거 아니였나요 ??

2024-01-29 10:52 UTC, TransparentDeveloper commented on src/components/commons/product-card.jsx
> +	BsHearts,
<img src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/35907e8c-7c22-43f5-a143-2b0b76d0beff" alt="훗" width="300px"/>

훗..그렇지 않은데?
.
.
.
.

- `ResponsiveIcon` 말씀하시는 건가요?? 그건 기존 Icon 컴포넌트에 호버 효과가 필요할 경우 사용하는 걸로 알고있습니다. 
- 일전에 `RootLayout` 컴포넌트 만들때, hover 효과를 주기위해 `Icon` 을 상속받는 스타일 컴포넌트가 반복적으로 등장해서 문제가 됐던걸로 기억합니다. 그래서 호버 효과를 부여하는 로직을 분리시킨 게 `ResponsiveIcon` 입니다.
- ProductCard 위에 등장하는 아이콘에는 hover 효과가 필요없어, 그냥 `<Icon/>` 사용했습니다.

2024-01-29 14:18 UTC, hayoung78 commented on src/components/commons/product-card.jsx
> +	BsHearts,
엥? BsHearts 아이콘이 잘못됐다는건데..? 그 찜하트 갯수 표시하는 하트요 ^__^ 쌍하트 아이콘 아니잖아
뒤에 배경 검정으로 넣어서 하기로하지 않 았 나 ? ?

2024-01-29 14:21 UTC, hayoung78 commented on src/components/commons/product-card.jsx
> +	BsHearts,
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/2d0c87e6-5445-4678-94ad-a26cd2ee84fc)

2024-01-29 16:51 UTC, TransparentDeveloper commented on src/components/commons/product-card.jsx
> +	BsHearts,
- 아,, 죄송합니다. 잘못 이해했습니다. 
- 우리 프로젝트에서 Bootstrap Icons 만 쓰기로 했는데, 피그마에 나온 아이콘이 없더라구요.
- ProductCard 디자인 하신 분이랑 상담해봤는데, 그냥 이 아이콘 사용하셔도 좋다고 말씀하셨습니다.  👍

2024-01-30 14:36 UTC, hayoung78 commented on src/components/commons/product-card.jsx
> +	BsHearts,
허허이.... 이런이런... 안돼................속상하네여

2024-01-30 14:39 UTC, hayoung78 approved these changes

2024-01-30 15:36 UTC, keeprok approved these changes
확인햇습니다

2024-01-31 02:59 UTC, jjjiyoung0130 approved these changes
수고하셨습니다. 하트만 디자인에 맞춰서 수정해주시죠.

2024-01-31 02:59 UTC, jjjiyoung0130 commented on src/components/commons/product-card.jsx
> +	BsHearts,
@TransparentDeveloper 피그마 디자인에 맞게 BsHeart 아이콘 커스텀해주세요

2024-01-31 02:59 UTC, jjjiyoung0130 commented on src/utils/data-calculator.js
> +	if (diffHour < 24) return diffHour + " 시간 전"; // 24시간 이상이 아니라면 "시간" 단위로 반환
diffHour가 60 미만인 경우에 "x 시간 전"으로 반환되고 Math.floor를 사용하여 소수점 이하를 제거한다면 "1분 전"에 등록된 판매글의 경우에도 1시간 전으로 보여지는걸까요?

2024-02-02 06:41 UTC, hayoung78 approved these changes
화긴

2024-02-02 08:42 UTC, TransparentDeveloper commented on src/utils/data-calculator.js
> +	if (diffHour < 24) return diffHour + " 시간 전"; // 24시간 이상이 아니라면 "시간" 단위로 반환
오.. 좋은 지적이십니다. 
확인해보니 날짜만 전달받기 때문에, 당일에 등록한 상품은 당일 0시 ~ 조회 시간까지 출력됩니다.

예를 들어, 12시에 상품을 올렸고 13시에 조회했을 때, 0시 ~ 13시 까지의 시간이 표시되어 13시간으로 표시됩니다.

24시간 이내라면 "최근" 으로 변경하겠습니다;;

2024-02-02 08:45 UTC, TransparentDeveloper commented on src/utils/data-calculator.js
> +	if (diffHour < 24) return diffHour + " 시간 전"; // 24시간 이상이 아니라면 "시간" 단위로 반환
- [fix: 시간 변환 오류 수정, 24시간 이내라면 "최근" 으로 출력](https://github.com/PurpleDynamics/PEA_Project/pull/15/commits/e22072e3bf3c0d891414213df87d6020b7eb88cc)
  - 더 나은 방법이 있다면 알려주세요. 바로 수정하겠습니다.
  - 좋은 지적 감사합니다. 👍👍 거기까지 생각을 못했네요;;

2024-02-02 13:49 UTC, merged