PE/PD-41: 권한 여부에 따라 접근 페이지 제어 기능 구현
PurpleDynamics/PEA_Project pull request #16
Opened 2024-01-28 17:52 UTC by ijimlnosk

## 🎯 작업 내용

- [fix: 안되요 => 안돼요 수정했습니다](https://github.com/PurpleDynamics/PEA_Project/commit/17ccd9b7db00bd90397001a3a654adec9d6cb129)
  - PR 템플릿 오타 수정했습니다.

- [move: pages 파일 경로 수정](https://github.com/PurpleDynamics/PEA_Project/commit/235997a7af767f4e3d4c3ade16f6c04ac61417a9)
  - 기존 폴더 구조를 컨벤션에 맞게 수정했습니다

- [chore: router 경로 수정](https://github.com/PurpleDynamics/PEA_Project/commit/89fe7a4f35e023dc09878f41605d294c97f1a632)
  - 컨벤션에 맞게 barrel file에서 불러오게 끔 수정했습니다.

- [design: 404 페이지 퍼블리싱](https://github.com/PurpleDynamics/PEA_Project/commit/bceef5bdee743ac45aead81f8e7024deb8c97620)
  - 정해진 경로와 다른 경로 입력시 나오는 404 페이지를 생성했습니다.

- [feat: token에 따라 접근 경로 설정](https://github.com/PurpleDynamics/PEA_Project/commit/0bcfc2e90519b7cfd143e4acb0a5a9b6c3962e54)
  - token이 없는 사용자는 signin, signup 페이지로 이동
  - token이 있는 사용자는 나머지 페이지로 이동가능한 router를 설정했습니다.

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] PR 제목 (컨벤션에 따랐는지) 확인 
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!! 

### 👍 문제가 없다고 생각된다면...
1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...
1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.
```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```
2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-01-28 18:45 UTC, snkchan approved these changes
고생하셧습니다~~!

2024-01-29 06:54 UTC, TransparentDeveloper requested changes
👏👏👏 고생하셨습니다. 너무  좋네요 👍

<div align='center'>

<img src='https://github.com/PurpleDynamics/PEA_Project/assets/50646145/eb4c30ad-4ce9-40fc-be6e-0d4b241ec46c'/>

</div>

그냥 승인시켜주기 싫은데여??

2024-01-29 06:54 UTC, TransparentDeveloper commented on src/components/layouts/layout.jsx
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 여기서도 토큰 검사를 하네요?? `admin-router.jsx` 에서 access_token 있다고 확인된 경우, `<Outer/>` 를 반환하는 대신 `<RootLayout>` (이미 이 안에 `<Outer/>` 가 있기 때문에) 을 반환하면, 이 파일에서는 분기 로직이 불필요하지 않을까요?

2024-01-29 06:54 UTC, TransparentDeveloper commented on src/libs/react-router-dom/index.js
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 세 분이서 고민했던 게 `AdminRoute` import 하는 부분이었나요?? 
- 제가 branch 받아서 테스트 해보니, 저는 오류없이 잘 되더라구요. 회의 전에 한번 같이 한번 보시죠.!! 👍

2024-01-29 07:55 UTC, hayoung78 commented on src/libs/react-router-dom/index.js
굳

2024-01-29 07:59 UTC, ijimlnosk commented on src/libs/react-router-dom/index.js
네ㅔ 멀쩡하게 잘되다가 갑자기 순환 처리 오류가 발행해서 우선 다르게 임포트 해놓은 것이였습니다
다시 살펴보면 좋겠네요!

2024-01-29 08:06 UTC, hayoung78 commented on src/components/layouts/layout.jsx
아 그렇네요 수정하겠습니다

2024-01-29 08:21 UTC, ijimlnosk commented on src/components/layouts/layout.jsx
정확히 어느 부분을 말씀하시는지는 모르겠으나
admin_router에서 토큰으로 검증하는 부분은 토큰이 존재하지 않는 사용자가 sign 페이지가 아닌 다른 주소로 접근할 때 
막아주는 부분이고
layout의 토큰을 이용한 부분은 sign 페이지에서 header와 footer를 보여주지 않기 위함입니다.

admin_router 의 <Outlet /> 은  <Rootlayout /> 으로 변경되어도 똑같이 작동하는 것은 확인했습니다.

2024-01-29 08:22 UTC, ijimlnosk commented on src/components/layouts/layout.jsx
참고로 admin-router 에서 <Rootlayout />으로 설정 후 
layout 페이지에서 검증을 통해 나누어 주지 않으면 sign page에서 header와 footer가 나오는 것을 확인했습니다

2024-01-29 09:26 UTC, hayoung78 approved these changes
우리팀 완벽 그잡채

2024-01-29 10:10 UTC, TransparentDeveloper commented on src/components/layouts/layout.jsx
맞죠, 근데 결국 `access-token` 에 따라서 어떤 페이지를 보여주냐는 것과 RootLayout 을 보여주냐 마냐가 결정되는 거잖아요., 
이것들을 분기되는 로직을 `admin-router.jsx` 안에서 다 관리될 수 있을 것 같아 말씀드립니다.

2024-01-29 15:26 UTC, ijimlnosk commented on src/components/layouts/layout.jsx
[refactor: token 유무로 분리되는 로직을 수정하였습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/16/commits/62b47e5d4a7c35d3455f5eed2f8d4acf9fe20056)

2024-01-29 15:54 UTC, TransparentDeveloper approved these changes
변경 부탁드립니다. 고생하셨습니다.!~

2024-01-29 15:54 UTC, TransparentDeveloper commented on src/libs/react-router-dom/admin-router.jsx
> +		</>
- 그냥 <RootLayout/> 만 적는게 좋을 것 같습니다. clean-code 를 위해서.,

2024-01-29 15:58 UTC, keeprok approved these changes
좋네여

2024-01-29 16:24 UTC, merged