PR:PD-66: 공용컴포넌트 modal 작성했습니다.
PurpleDynamics/PEA_Project pull request #21
Opened 2024-01-30 15:29 UTC by keeprok

## 🎯 작업 내용

- [PR:PD-66: 공용컴포넌트 modal 작성했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/cd1f8331ab44ebe47c573648ba7dbb28edb53b26)
<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-01-31 01:53 UTC, snkchan requested changes
리뷰확인해 주세요 
추가로 리뷰작성하실때 전달 사항이나, design task였다면 이미지나 동영상으로 작업물을 보여주시는게 좋을 것 같아요~

2024-01-31 01:53 UTC, snkchan commented on src/components/commons/modal.jsx
> + *
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
어떤역할을 하는지 설명을 써주시면 좋을것 같아요.

2024-01-31 01:53 UTC, snkchan commented on src/components/commons/modal.jsx
> +	addText,
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
props들의 default값이 있어야 할 것들을 생각해보시고 default value를 넣어주시면 좋을 것 같아요

2024-01-31 01:53 UTC, snkchan commented on src/components/commons/modal.jsx
> +	height: ${({ height }) => height || "15rem"};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
props부분에 deafultvalue를 주셔서 기본값을 설정해주시는게 더 좋지 않을까요????

2024-01-31 04:50 UTC, keeprok commented on src/components/commons/modal.jsx
> + *
넵!! 수정했습니다

2024-01-31 04:50 UTC, keeprok commented on src/components/commons/modal.jsx
> +	addText,
네 가시성 좋게 했습니다

2024-01-31 04:50 UTC, keeprok commented on src/components/commons/modal.jsx
> +	height: ${({ height }) => height || "15rem"};
수정했습니다

2024-02-01 13:11 UTC, jjjiyoung0130 commented on src/components/commons/modal.jsx
> +	addBTN,
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 왜 addBTN만 BTN이 대문자로 쓰여있는지 모르겠군요. 컴포넌트 이름을 통일시켜서 작성해주시면 좋을 것 같아요.

2024-02-01 13:18 UTC, jjjiyoung0130 commented on src/components/commons/modal.jsx
> +const BaseBtn = styled.button`
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - BaseBtn과 AddBTN이 color 이외에는 동일하게 작성되어있는데, 스타일드 컴포넌트 함수로 만들거나 상속을 받아서 사용할 수 있지않을까요?

2024-02-02 05:21 UTC, ijimlnosk approved these changes
확인했습니다

2024-02-02 06:49 UTC, TransparentDeveloper requested changes
고생 하셨습니다. 처음 컴포넌트 만드셨는데, 고민한 티가 나네요. 👍

2024-02-02 06:49 UTC, TransparentDeveloper commented on src/components/commons/modal.jsx
> +	height: ${({ height }) => height || "15rem"};
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 스타일 컴포넌트에 props 전달할 경우, 그 이름에 대한 컨벤션이 노션에 정의되어있습니다. 확인 부탁드립니다.
- 이미 상단에 width와 height 에 대한 기본값 설정하셨습니다. 변수 값만 return 하면 될 것 같습니다.
- 'return' keyword 꼭 작성하는 것이 컨벤션으로 알고 있습니다. 수정 부탁해요.

2024-02-02 06:49 UTC, TransparentDeveloper commented on src/components/commons/modal.jsx
> +	border-radius: 8px; //임의 못찾음
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 주석의 의미를 모르겠습니다. 
- 기능, 활용 목적을 기술하는 주석이 아니라면, 프로젝트 코드상에서 없애는 게 좋을 것 같습니다.
- 어떤 고충이 있다면, pr 에 남기거나 메신저 통해서 질문해 주세요.

2024-02-02 06:49 UTC, TransparentDeveloper commented on src/components/commons/modal.jsx
> +		</>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 불필요한 프레그먼트가 감싸져 있네요. 제거해주시겠어요?

2024-02-02 06:49 UTC, TransparentDeveloper commented on src/components/commons/modal.jsx
> +				<S.Line></S.Line>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `<S.Line/>` 이렇게 작성하는게 더 좋을 거 같습니다.

2024-02-02 06:49 UTC, TransparentDeveloper commented on src/components/commons/modal.jsx
> + * @parameter modalHeight : string - 모달 세로 사이즈
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- JsDocs 도 일관성 있게 작성해야 좋을 것 같습니다. 
- 기본값을 명시할지 말지 결정해서, 기본값이 설정된 다른 파라미터 역시 동일하게 적용바랍니다.

2024-02-02 07:29 UTC, hayoung78 commented on src/components/commons/modal.jsx
> +	border-radius: 8px; //임의 못찾음
동의합니다

2024-02-02 12:13 UTC, keeprok commented on src/components/commons/modal.jsx
> +		</>
넵

2024-02-02 13:54 UTC, keeprok commented on src/components/commons/modal.jsx
> +				<S.Line></S.Line>
변경할부분이라 삭제 하도록 하겠습니다

2024-02-03 17:49 UTC, keeprok commented on src/components/commons/modal.jsx
> +const BaseBtn = styled.button`
수정했습니다(https://github.com/PurpleDynamics/PEA_Project/pull/21/commits/ce8c1d99fc4697e9e384b75ba8893c6c332d8dba)

2024-02-03 17:50 UTC, keeprok commented on src/components/commons/modal.jsx
> +	addBTN,
[수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/21/commits/ce8c1d99fc4697e9e384b75ba8893c6c332d8dba)

2024-02-03 17:50 UTC, keeprok commented on src/components/commons/modal.jsx
> + * @parameter modalHeight : string - 모달 세로 사이즈
[수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/21/commits/ce8c1d99fc4697e9e384b75ba8893c6c332d8dba)

2024-02-04 13:20 UTC, jjjiyoung0130 requested changes

2024-02-04 13:20 UTC, jjjiyoung0130 commented on src/components/commons/modal.jsx
> + * @parameter addBtn : function - 추가 버튼 기능
또한 baseBtn과 addBtn이 함수라면 이름을 좀 변경할 필요가 있다고 생각합니다.
공용 컴포넌트이기는 하나 스타일드 컴포넌트와 동일한 이름을 사용하는지도 의문이라, 기능 구현의 단계는 아니지만 임의로라도 이전에 컨벤션으로 정한 형식을 따라서 작성해주시면 좋을 것 같습니다.

> 이벤트 핸들러
> - Props의 경우 : on  → onClick
> - 함수인 경우: handle → handleUserAdd

2024-02-04 19:32 UTC, keeprok commented on src/components/commons/modal.jsx
> +// 모달기본 height 가 전달받고
[수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/21/commits/55b612146c4b071928395f6182d72e6be8021796)

2024-02-05 11:53 UTC, keeprok commented on src/components/commons/modal.jsx
> + * @parameter addBtn : function - 추가 버튼 기능
props부분  이름 변경했습니다 다음부터는 컨벤션 형식 준수 하겠습니다

2024-02-05 15:52 UTC, keeprok commented
[fix : Btn들의 공통된 style정리했고baseBtn에 onClose부분 추가했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/21/commits/1b25f5401e41108edbf7f2b0d199379797e159a8)
- 수정을 통해서  overlay방식을통해 props를 전달하면 overlay와onClose작동하게했습니다 

-코드

-출력물
(https://github.com/PurpleDynamics/PEA_Project/assets/140785214/57696213-0a5e-482c-8a82-c782d7dbf1ea)

2024-02-07 03:18 UTC, hayoung78 approved these changes

2024-02-07 03:54 UTC, TransparentDeveloper requested changes
👍👍

2024-02-07 03:54 UTC, TransparentDeveloper commented on src/components/overlay/modal.jsx
> +	grid-template-rows: auto 7rem; */
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 불필요한 코드는 지워주세요.

2024-02-07 03:54 UTC, TransparentDeveloper commented on src/components/overlay/modal.jsx
> +	}};
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 스타일 컴포넌트 props 전달 컨벤션 다시 확인 바랍니다.

2024-02-07 05:31 UTC, keeprok commented on src/components/overlay/modal.jsx
> +	}};
[fix : style부분변경및 불필요한 주석 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/21/commits/a71ccffa51424ae0bf05433096a4e0856142373e)

2024-02-07 05:32 UTC, keeprok commented on src/components/overlay/modal.jsx
> +	grid-template-rows: auto 7rem; */
[fix : style부분변경및 불필요한 주석 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/21/commits/a71ccffa51424ae0bf05433096a4e0856142373e)

2024-02-07 05:35 UTC, TransparentDeveloper approved these changes

2024-02-07 06:05 UTC, jjjiyoung0130 approved these changes

2024-02-07 07:52 UTC, merged