PR/PD-61: compression-container 생성
PurpleDynamics/PEA_Project pull request #23
Opened 2024-01-31 07:57 UTC by ijimlnosk

## 🎯 작업 내용

- [design: compression-container 생성](https://github.com/PurpleDynamics/PEA_Project/commit/a6a4f7792d7fb1f4024bbfa4cfa6527b832fd247)
  - 상-하, 좌-우 의 값을 입력받아 여백을 생성하는 컴포넌트입니다.

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-01 12:43 UTC, jjjiyoung0130 requested changes
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 전체적으로 페이지 좌우 여백을 200씩 지정 했던 걸로 기억합니다. 개인적인 의견입니다만, lr = "0rem"으로 두는 것 보다는 좌우 여백에 대한 default value를 지정해두면 페이지별로 사용하는데 더욱 용이하지않을까요?

2024-02-01 13:24 UTC, snkchan requested changes
리뷰 남겼습니다 확인해주세요~

2024-02-01 13:24 UTC, snkchan commented on src/components/commons/compression-container.jsx
> +		return `${$tb} ${$lr}`;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
return `${$tb} ${$lr}`; 이부분은  return `$tb $lr `이렇게 들어가야하는거 아닌가요??

2024-02-01 13:24 UTC, snkchan commented on src/components/commons/compression-container.jsx
> + * @parameter children : 내부에 들어갈 dom요소
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description

parameter에 tb,lr 에대한것도 같이 작성해주시면 좋을것 같아요.

2024-02-02 01:58 UTC, ijimlnosk commented on src/components/commons/compression-container.jsx
> +		return `${$tb} ${$lr}`;
말씀하신거 처럼 return $tb $lb 로 사용하면 앞의 $tb만 return 값으로 인식하고 오류가 발생합니다

2024-02-02 02:03 UTC, ijimlnosk commented on src/components/commons/compression-container.jsx
> + * @parameter children : 내부에 들어갈 dom요소
[추가, default value 변경](https://github.com/PurpleDynamics/PEA_Project/pull/23/commits/86c985a1cd1c2f4f5cda5a90d0bd9d462976f826)
추가했습니다

2024-02-02 06:55 UTC, TransparentDeveloper requested changes
👍 고생하셨습니다. 
주석 설명 잘 작성해주셨는데, 우리가 정한 JsDocs 작성법 조금 어긋났네요.

2024-02-02 06:55 UTC, TransparentDeveloper commented on src/components/commons/compression-container.jsx
> + * @parameter lr : left, right 의 padding 값
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 설명 잘 작성해주셨는데, 우리가 정한 JsDocs 작성법 조금 어긋났네요:|
- 타입이 없습니다.

2024-02-02 06:55 UTC, TransparentDeveloper commented on src/components/commons/compression-container.jsx
> +		</>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 불필요한 프레그먼트가 감싸져있습니다. 수정해주세요.

2024-02-02 06:55 UTC, TransparentDeveloper commented on src/components/commons/compression-container.jsx
> + * @components
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- "@component" 로 작성해야합니다. :)

# Description

2024-02-02 07:30 UTC, ijimlnosk commented on src/components/commons/compression-container.jsx
> + * @components
@ijimlnosk
[fix : jsdoc 수정 및 불필요 요소제거](https://github.com/PurpleDynamics/PEA_Project/pull/23/commits/33458f118c0f46bf1e808960558ee1cf69fb26b2)

2024-02-02 07:31 UTC, ijimlnosk commented on src/components/commons/compression-container.jsx
> +		</>
[fix : jsdoc 수정 및 불필요 요소제거](https://github.com/PurpleDynamics/PEA_Project/pull/23/commits/33458f118c0f46bf1e808960558ee1cf69fb26b2)

2024-02-02 07:31 UTC, ijimlnosk commented on src/components/commons/compression-container.jsx
> + * @parameter lr : left, right 의 padding 값
[fix : jsdoc 수정 및 불필요 요소제거](https://github.com/PurpleDynamics/PEA_Project/pull/23/commits/33458f118c0f46bf1e808960558ee1cf69fb26b2)

2024-02-02 07:51 UTC, hayoung78 approved these changes
확인했습니다

2024-02-02 12:10 UTC, jjjiyoung0130 approved these changes

2024-02-02 12:18 UTC, keeprok approved these changes
확인했스니다

2024-02-02 14:34 UTC, snkchan approved these changes
고생하셧습니다.

2024-02-02 14:34 UTC, merged