PR:PD-67: 공용컴포넌트 banner작업했습니다.
PurpleDynamics/PEA_Project pull request #25
Opened 2024-02-01 20:15 UTC by snkchan

## 🎯 작업 내용

https://github.com/PurpleDynamics/PEA_Project/assets/144839872/ce41381f-e119-45bc-aad7-ab740f01aeb8
- [design: banner componet publishing 완료](https://github.com/PurpleDynamics/PEA_Project/commit/bf1e3295afaddd776672a6f2344c73c434437001)
  - banner의 design 작업했습니다.
  
- [feat: <,>아이콘 클릭시 배너이동 기능 추가, anmation효과 적용](https://github.com/PurpleDynamics/PEA_Project/commit/988ebf4cb77a77caee04d68e97b7ba823280c372)
  - <, > 아이콘 클릭시 다음 광고정보를 github page에서 받아와서 화면에 보여줍니다.
  - 광고정보가 로드될때 animation효과 적용했습니다.

## 광고정보는 어디서??
- https://docs.google.com/forms/d/1fjqVfogyQ6tMJ4lqXqucpDg0lmey4_n0Z7-LgFTpf2E/viewform?pli=1&pli=1&edit_requested=true
- 위의 링크를 접속하면 저희 purpleDynamics의 광고를 받는 페이지가 나옵니다.
   해당페이지에서 받아온 광고data는 purpleDynamics > repo > PurpleDynamics.github.io  접속하시면 ads폴더안에 
   배열형태로 data가 저장되어있습니다.
<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-02 07:15 UTC, TransparentDeveloper requested changes
고생하셨습니다. 역시,,,,쵝오👍..

2024-02-02 07:15 UTC, TransparentDeveloper commented on src/components/commons/banner.jsx
> +	margin: 9rem 0;
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- PR 열기 전에 지운다고 하셨는데... ;)

2024-02-02 07:15 UTC, TransparentDeveloper commented on src/components/commons/banner.jsx
> +						})}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 저는 같이 작업해서 아는데, 다른 분들이 보시면 무슨 로직인지 모를 것 같습니다. 주석 작성하는게 어떨까요?

2024-02-02 07:15 UTC, TransparentDeveloper commented on src/components/commons/banner.jsx
> +import ResponsiveIcon from "./responsive-icon";
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 제가 기억하기로, 같은 깊이에 있는 컴포넌트라도 barrel 파일 통해서 import 하기로 했었습니다. 확인부탁드립니다.

2024-02-02 07:15 UTC, TransparentDeveloper commented on src/components/commons/banner.jsx
> +	const [adData, setAdData] = useState([]); // fetching된 data를담을 state
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 단수형으로 이름을 작명하셔서, 하나의 광고 데이터를 다루는 느낌이 나네요.
- 복수형으로 적거나, 배열 타입이라는 것을 알 수 있도록 이름 수정하는 게 좋을 것 같습니다 :)

2024-02-02 13:23 UTC, snkchan commented on src/components/commons/banner.jsx
> +	margin: 9rem 0;
이건 추후에 적용되면 지우려했는데 지금 지우고올리는게 좋을까요?

2024-02-02 13:42 UTC, keeprok approved these changes
더이상 고칠부분이 보이질않네여

2024-02-02 13:47 UTC, snkchan commented on src/components/commons/banner.jsx
> +						})}
- [docs: 줄바꿈 처리에대한 logic docs작성](https://github.com/PurpleDynamics/PEA_Project/pull/25/commits/52e9a14cf842baf8d6871ad34fa7d17b2cc87cc2) 
 주석 추가했습니다.

2024-02-02 13:47 UTC, snkchan commented on src/components/commons/banner.jsx
> +	const [adData, setAdData] = useState([]); // fetching된 data를담을 state
- [fix: 정확한 변수명을위해 변수명 변경](https://github.com/PurpleDynamics/PEA_Project/pull/25/commits/2cb8570b8fa428d840df5531750ef854ded3be32)
단수형에서 복수형으로 수정하는 것이 좋을것 같아서 복수형태로 수정했습니다.

2024-02-02 13:48 UTC, snkchan commented on src/components/commons/banner.jsx
> +import ResponsiveIcon from "./responsive-icon";
- [fix: 잘못된 import수정](https://github.com/PurpleDynamics/PEA_Project/pull/25/commits/c61ae1d48d0b27ac79a4c57b23d0997947582517)
 깜박하고 수정안했네요 헉,, 처리했습니다.

2024-02-02 14:39 UTC, jjjiyoung0130 commented on src/components/commons/banner.jsx
> +	padding: 0 3px;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 다른 부분은 다 rem으로 작성하신 거 같은데 왜 이 부분만 px로 작성하셨을까요?

2024-02-02 15:53 UTC, snkchan commented on src/components/commons/banner.jsx
> +	padding: 0 3px;
그러게요,,,, 버튼의 size가 작아서 px단위로해도 크게 문제없을것 같아서 작성했는데 참고하겟습니다.

2024-02-03 07:59 UTC, TransparentDeveloper approved these changes

2024-02-04 10:29 UTC, hayoung78 approved these changes
확인했습니다

2024-02-04 13:28 UTC, closed without merging