PR/PD-67: signup-page 작업했습니다.
PurpleDynamics/PEA_Project pull request #26
Opened 2024-02-02 07:24 UTC by hayoung78

## 🎯 작업 내용

[feat : input 에 cursor pointer 추가](https://github.com/PurpleDynamics/PEA_Project/commit/746274e0ad5186f6ad98cd1cadd651ad8a39935a)
 (해당 수정사항은 input 브랜치에서 해야하는게 맞지만 협의하에 제가 진행하였습니다^^.. 양해부탁드립니다.)
 - input 창 안에 buttonText(중복확인) 버튼 호버시 cursor : pointer 추가

[design : signup-page 생성](https://github.com/PurpleDynamics/PEA_Project/commit/49d7cd4d43333c7ecf829b1a46df68f554087b42)

![스크린샷 2024-02-02 155108](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/a085050a-63eb-4518-bfd8-2e75d115b9ca)

- 이메일 , 비밀번호, 닉네임 작성부분에는 해당부분에 맞는 정규 표현식 코드를 사용하였습니다.
   (이메일: 이메일 형식 / 비밀번호: 8글자이상 / 닉네임: 특수문자금지)
<video  src= "https://github.com/PurpleDynamics/PEA_Project/assets/142880051/123aadf2-fb44-44af-a9b3-1cf707dbed85
"></video>
- '가입하기' 버튼 클릭시 signin-page로 넘어갑니다.
- 닉네임 입력창은 autoComplete 이 불필요할것같아 off로 설정해 두었습니다.

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-02 07:54 UTC, TransparentDeveloper requested changes
고생하셨습니다. 👍👍
반응형 제대로 적용하지 않았다 하더라도, break-point `md` 사이즈까지 정상적으로 출력되는지 확인해주세요.!!

2024-02-02 07:54 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +								required: "필수 응답 항목입니다.",
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이런 알림 메시지는 다른 데에서도 사용할 것 같습니다.
- 분명 다른 사람도 사용할 거 같은데, 사용할 때마다 비슷한 의미의 다른 메시지로 적을 가능성이 높습니다.
  - 예를 들어,
    - "필수 응답 항목입니다."
    - "필수 항목입니다."
    - "꼭 응답해주세요."
- `src` 폴더 아래, `constants` 폴더를 만들고 이런 메시지를 관리할 수 있는 파일을 하나두어 거기서 export 해야 일관성 있게 사용 가능합니다.
- 이것뿐만 아니라, 유효성 검사에서 출력되는 다른 텍스트 모두 위와 같은 방법으로 사용하는 게 좋을 것 같습니다.

2024-02-02 07:54 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +`;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
-  좌/우 1대1 비율로 나누면서, 가운데로 모으는 기능을 하는 것 같습니다. 분리될 필요가 있을까요??

2024-02-02 07:54 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> + * @returns {JSX.Element}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 제 눈에는 전달받는 props 가 안보입니다. 😳

2024-02-02 07:54 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +								required: "필수 응답 항목입니다.",
- 이메일 형식이나, 특수문자 미사용 에 대한 정규식 같은 것도 빼두면 좋겠네요.

2024-02-02 13:36 UTC, keeprok requested changes
리뷰 확인해 주시면 감사하겠습니다

2024-02-02 13:36 UTC, keeprok commented on src/pages/signup-page.jsx
> +const SigninPage = () => {
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - Signup아닌가요...?

2024-02-02 13:36 UTC, keeprok commented on src/pages/signup-page.jsx
> +	const onMoveSignPage = () => {
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - onMoveSignPage -> onMoveSigninPage 로 변경하면 좋을거같아요

2024-02-02 13:37 UTC, snkchan requested changes
리뷰남겼습니다 확인해주세요~~

2024-02-02 13:37 UTC, snkchan commented on src/pages/signup-page.jsx
> + * @components
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
@components --> @component로 작성해주셔야합니다~
추가로@description에 대한것도 작성해주시면 좋겠습니다.

2024-02-02 13:52 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +								required: "필수 응답 항목입니다.",
네에 수정하겠습니다

2024-02-02 13:55 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +const SigninPage = () => {
아? 맞네 뭐야 나왜 signin 으로 씀..

2024-02-02 13:55 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	const onMoveSignPage = () => {
예ㅖ 확인~

2024-02-02 13:56 UTC, hayoung78 commented on src/pages/signup-page.jsx
> + * @components
네 수정하겠습니다

2024-02-03 09:21 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +`;
분리될 필요가있다는게 ,, 좌우 1:1 나누는게 굳이 필요하지 않다고 말씀하시는 걸까요???? 
화면 배율이 달라져도 가운데 같은 위치에 같은 1:1 비율로 보이게끔하려고 한건데 좋은 의견이 있으시면 말씀해주세요

2024-02-04 06:41 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +`;
수정했습니다

2024-02-04 06:41 UTC, hayoung78 commented on src/pages/signup-page.jsx
> + * @returns {JSX.Element}
수정했습니다

2024-02-04 06:41 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +								required: "필수 응답 항목입니다.",
[refactor: 반응형 웹사이트로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/69d5ca3c82b31f77b969c87ddf826ff0322dc9db)

2024-02-04 06:43 UTC, hayoung78 commented on src/pages/signup-page.jsx
> + * @components
[chore: jsDoc 이름 & 컴포넌트 이름 수정 (signin->signup)](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/c0aed37428da60e9e67292b7cf5b9b829be9af52)

2024-02-04 06:43 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	const onMoveSignPage = () => {
[chore: jsDoc 이름 & 컴포넌트 이름 수정 (signin->signup)](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/c0aed37428da60e9e67292b7cf5b9b829be9af52)

2024-02-04 06:43 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +const SigninPage = () => {
[chore: jsDoc 이름 & 컴포넌트 이름 수정 (signin->signup)](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/c0aed37428da60e9e67292b7cf5b9b829be9af52)

2024-02-04 10:14 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +`;
[refactor: 반응형 웹사이트로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/69d5ca3c82b31f77b969c87ddf826ff0322dc9db)

2024-02-04 10:23 UTC, hayoung78 commented on src/pages/signup-page.jsx
> + * @returns {JSX.Element}
[refactor: 유효성 검사메세지 constants파일로 관리](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/f82e96541bf8500eda254750e7be21abe46cebba)

2024-02-04 12:52 UTC, jjjiyoung0130 requested changes

2024-02-04 12:52 UTC, jjjiyoung0130 commented on src/pages/signup-page.jsx
> +				<Button
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 회원가입의 경우, button의 type이 "button"이 아닌 "submit"으로 명시되어야 API를 사용할 때 POST 방식으로 서버에 전달할 수 있지 않을까요?

2024-02-04 12:52 UTC, jjjiyoung0130 commented on src/pages/signup-page.jsx
> +	const onMoveSigninPage = () => {
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 -"가입하기" 버튼에 해당 함수를 실행하기보다 form 태그에 onSubmit 이벤트 핸들러를 작성하고 그에 맞는 함수를 작성하면 password, password confirm의 유효성 검사 및 error처리, 회원가입 성공 시 로그인 페이지로의 이동 등에 해당하는 로직을 설계할 수 있지않을까요?

2024-02-04 13:15 UTC, snkchan approved these changes
고생하셨습니다~~merge해도 좋을것같네요

2024-02-04 13:39 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	const onMoveSigninPage = () => {
[refactor: button타입 변경 및 form태그에 onSubmit핸들러 추가](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/4690e13a5825a60cd745bae2f25d0bd66675b779)

2024-02-04 13:39 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +				<Button
[refactor: button타입 변경 및 form태그에 onSubmit핸들러 추가](https://github.com/PurpleDynamics/PEA_Project/pull/26/commits/4690e13a5825a60cd745bae2f25d0bd66675b779)

2024-02-04 13:44 UTC, jjjiyoung0130 approved these changes

2024-02-04 13:57 UTC, KR-HeoJU approved these changes

2024-02-04 14:32 UTC, keeprok approved these changes

2024-02-04 14:46 UTC, TransparentDeveloper approved these changes

2024-02-04 14:46 UTC, hayoung78 commented on src/constants/validate-message.js
> +const EMAIL = {
constants 파일로 유효성 검사에서 필요한 메세지들 관리할수있게 수정했습니다

2024-02-04 14:49 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	const onSubmit = () => {
form 자체 내에서 onSubmit 핸들러 사용할수있게 수정했습니다

2024-02-04 14:49 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	@media (max-width: ${BREAK_POINT.md}) {
break-point md 사이즈 확인했습니다

2024-02-04 14:55 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +								required: "필수 응답 항목입니다.",
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/f703492c-528b-459a-8177-54f1924c56fc)
constants 파일에서 따로 유효성 메세지 관리하게끔 수정하였고, 반응형 웹사이트 실행도 완료했습니다

2024-02-04 14:57 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +`;
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/a7db0833-1069-4d20-8170-8f9c7e160eb0)
말씀하신대로 css 수정하였고. 
화면크기가 줄어들 시 , 
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/a7757013-a61f-4f35-b1ca-0235f0e64551)
다음과 같이 화면이 반응합니다

2024-02-04 14:57 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	const onMoveSigninPage = () => {
form 자체에 onSubmit 추가하였고, 버튼 타입도 'submit'으로 변경 완료하였습니다

2024-02-04 14:58 UTC, merged