PR/PD-68: 최근 본 상품 UI 관련 컴포넌트 작성했습니다.
PurpleDynamics/PEA_Project pull request #28
Opened 2024-02-03 16:07 UTC by jjjiyoung0130

## 🎯 작업 내용
![recnetlyProduct](https://github.com/PurpleDynamics/PEA_Project/assets/142701370/39792d2d-0f3b-4da4-9912-36b480e0757c) ![notRecnetlyProduct](https://github.com/PurpleDynamics/PEA_Project/assets/142701370/18b78a99-4451-4fe5-9859-9eb4a0056c4e)

 - [design: 공용 컴포넌트 ProductList 작업했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/932ffcf66bf668448af55e7d9693fcfae357b86a)
   - 페이지별 side에 fixed되는 [최근 본 상품] 컴포넌트를 생성했습니다.
   - 최근 본 상품이 있을 경우, 해당 data를 토대로 가장 최근에 확인한 상품 3개를 해당 리스트에 보여줍니다.
   - 최근 본 상품이 없을 경우, "최근 본 상품이 없습니다" 문구가 보여집니다.
   - 상품의 이미지를 클릭할 경우, productId를 param으로 하여 상세 페이지로 이동합니다. (현재 404 Error)

 - [design: 공용 컴포넌트 side-chat-button 작업했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/e0daa6cf30ba57287303587c1f738c7e7bde4fa5)
   - [최근 본 상품] 컴포넌트의 하단에 위치하는 채팅 버튼과 관련된 컴포넌트를 생성했습니다.

 - [feat: 공용 컴포넌트 top-button 작업했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/682c06eb329a24afdcfb092b90391dc04cc81a39)
   - [최근 본 상품] 컴포넌트 내부에 위치하는 Top 버튼 컴포넌트를 생성했습니다.
   - 클릭 시, 페이지의 맨 위로 스크롤됩니다.

 - [design: 공용 컴포넌트 spacer 작성 및 적용했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/b604a0edc829b95817ae78651aafe96a54714aa3)
   - props로 전달받는 size와 axis에 따라 빈 공간을 생성하는 컴포넌트를 생성했습니다.
   - 현재 header의 height: 11rem에 맞춰 layout.jsx에 Spacer 컴포넌트를 추가해놓았습니다.
    `<Spacer size={110} axis="vertical" />`

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-03 17:43 UTC, snkchan requested changes
작업 잘하셧네요 ㅎㅎ 사소한거만 수정해주시면 될거 같습니다. 수고하셨습니다.

2024-02-03 17:43 UTC, snkchan commented on src/components/commons/recent-product-list.jsx
> +import TopButton from "./top-button";
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
같은 depth에 있는 파일import할때 {} from '.'으로 하셔야 할것 같아요!

2024-02-03 17:43 UTC, snkchan commented on src/components/commons/recent-product-list.jsx
> +const RecentProductWrapper = styled.div``;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
RecentProductWrapper는 아무역할도 안한다면 없어도 되는거 아닌가요???

2024-02-03 17:43 UTC, snkchan commented on src/components/commons/recent-product-list.jsx
> +const RecentProductListContainer = styled.div``;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
이친구도 딱히 역할이 없는거 같습니다.

2024-02-03 17:43 UTC, snkchan commented on src/components/commons/index.js
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
작업하신 컴포넌트들중에 spacer를 제외하면 차라리 components아래 sideBar폴더를 만들어서 나머지네가지 컴포넌트를 안에두고 관리하는게 어떨까요???? 안면 top-button은 추후에 다른곳에서 제사용될 가능성이 있을 수 도 있으니
세가지 컴포넌트를 다른폴더에서 관리하는건 어떨지 의견입니다.!

2024-02-03 17:43 UTC, snkchan commented on src/components/commons/recent-product-list.jsx
> +	font-family: "SOYO_Maple_Bold";
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
기본 font는 bold적용이라 없어도되는 코드입니당

2024-02-03 18:05 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
> +import TopButton from "./top-button";
- [design: 불필요한 css 및 font와 관련된 style 수정하였습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/11bf13e2667b5a9b4c93e96a0e86d732b651d81d)
   - 수정 사항들이 동일한 컴포넌트라 한 번에 수정하여 커밋하였습니다.

2024-02-03 18:05 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
> +const RecentProductWrapper = styled.div``;
- [design: 불필요한 css 및 font와 관련된 style 수정하였습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/11bf13e2667b5a9b4c93e96a0e86d732b651d81d)
   - 수정 사항들이 동일한 컴포넌트라 한 번에 수정하여 커밋하였습니다.

2024-02-03 18:05 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
> +const RecentProductListContainer = styled.div``;
- [design: 불필요한 css 및 font와 관련된 style 수정하였습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/11bf13e2667b5a9b4c93e96a0e86d732b651d81d)
   - 수정 사항들이 동일한 컴포넌트라 한 번에 수정하여 커밋하였습니다.

2024-02-03 18:05 UTC, keeprok approved these changes

2024-02-03 18:05 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
> +	font-family: "SOYO_Maple_Bold";
- [design: 불필요한 css 및 font와 관련된 style 수정하였습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/11bf13e2667b5a9b4c93e96a0e86d732b651d81d)
   - 수정 사항들이 동일한 컴포넌트라 한 번에 수정하여 커밋하였습니다.

2024-02-03 18:06 UTC, keeprok approved these changes
확인했습니다

2024-02-03 18:06 UTC, jjjiyoung0130 commented on src/components/commons/index.js
저도 동일한 생각입니다만, 다른 분들 의견 들어보고 작업하도록 하겠습니다.

2024-02-04 08:27 UTC, TransparentDeveloper requested changes
고생하셨습니다. 👍👍 역시 장지영..

전체적으로 컴포넌트 이름에 대해서 생각해봐주셨으면 좋겠습니다.
예를 들어, `-Icon` 이라는 접두어가 많이 보여요.. 찾아보면 icon 컴포넌트를 감싸는 용도로 사용하셨더라구요. 그 자체로 icon 을 출력할 수 없다면 좋지 않은 작명법 같습니다. 

채윤님이 전에 말씀해주셨는데, 한가지 요소를 감싸는 용도라는 `-Container`, 두가지 이상의 요소를 감싸는 용도라면 `-Wrapper` 접두어를 사용했고 합니다.:)

2024-02-04 08:27 UTC, TransparentDeveloper commented on src/components/commons/recent-product.jsx
> +		console.log(`상품 ID ${productId} 클릭`);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이벤트 처리를 확인할 용도로 console.log 를 자주 사용하신 것 같습니다. 
- 이런 코드가 main-branch 에 병합되는 것은 경계해야합니다. 
- 나중에라도 발견하지 못하고 배포가 될 시, 사용자들에게 개발 과정 상에 정보들이 노출될 수 있어요.
- 여러번 사용하신 것 같은데 모두 지워주셨으면 좋겠습니다.

2024-02-04 08:27 UTC, TransparentDeveloper commented on src/components/commons/recent-product-list.jsx
> + * - 최근 본 상품의 리스트를 보여주는 컴포넌트 입니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이렇게 한 줄짜리 설명의 경우에, `RecentProductList` 위로 커서 올려보면, 이상하게 출력됩니다.  ('- -최근 본 상품의 리스트를 보여주는 컴포넌트 입니다.' 이렇게..)
- 한 줄만 적으실 거라면 `@description` 옆에 띄어쓰기 한번 하고 적어주세요.

2024-02-04 08:27 UTC, TransparentDeveloper commented on src/components/commons/recent-product-list.jsx
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 구조를 조금 변경하면 좋을 것 같습니다.
- `RecentProductList` 와 `RecentProduct` 가 분리될 필요가 있는지 모르겠습니다.
- 일단 `RecentProductList` 에 대해서 말씀드리겠습니다.
- 리스트 라고 하면 동일한 형식의 요소를 반복시키는 ui 가 생각납니다. 
- 그런 의미에서`recent-product` 에 있는 코드가 실제 리스트 아닐까요?  (아래 빨간 테두리 부분)

<div align="center">

![list2](https://github.com/PurpleDynamics/PEA_Project/assets/50646145/80fdd0e6-76e6-494e-879f-0b0cc71c7188)

</div>

- (개인 의견입니다...) 저라면 `recent-product-list` 에 있는 코드는 `RecentProductListWrapper` 라는 이름의 스타일 코드로 만들 것 같습니다.

2024-02-04 15:33 UTC, snkchan approved these changes
작업 정말잘하셨습니다ㅎㅎ 따봉드리고갑니다.👍👍

2024-02-04 15:33 UTC, jjjiyoung0130 commented on src/components/layouts/layout.jsx
> +import Spacer from "../commons/spacer";
- [fix: 잘못된 import 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/49623358c520dacf3b294f021fdcc47317b503b3)
   - 수정했습니다.

2024-02-04 15:35 UTC, jjjiyoung0130 commented on src/libs/styled-components/reference-tokens/font-size.js
> +	xll: "4.8rem", // extreme large x 2
- [fix: 불필요한 font-size 추가 및 그에 따른 컴포넌트 size 지정 방식 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/c0112fe5b8c80fa473d812c1d0fa1552bc3e0b6e)
   - 수정했습니다.

2024-02-04 15:37 UTC, jjjiyoung0130 commented on src/components/commons/recent-product.jsx
> +		e.stopPropagation();
`removeRecentlyProductItem()` 에서 `e.stopPropagation()` 을 빼고 해당 기능의 아이콘을 클릭할 경우, `handleProductClick()` 이벤트가 동시에 발생합니다.
따라서 버블링을 막기 위한 해당 코드는 놔두고 부모 요소에 입력한 불필요한 중복 코드를 삭제하였습니다

2024-02-04 15:39 UTC, jjjiyoung0130 commented on src/components/commons/recent-product.jsx
> +	],
- [fix: 불필요한 font-size 추가 및 그에 따른 컴포넌트 size 지정 방식 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/c0112fe5b8c80fa473d812c1d0fa1552bc3e0b6e)
   - 수정하였습니다.

2024-02-04 15:39 UTC, jjjiyoung0130 commented on src/components/commons/side-chat-button.jsx
> +`;
- [fix: 스타일드 컴포넌트 이름 변경](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/b4e40659f2ec17696020d2f61a59ae3c61483e07)
   - 수정하였습니다.

2024-02-04 15:41 UTC, jjjiyoung0130 commented on src/components/commons/recent-product.jsx
> +		console.log(`상품 ID ${productId} 클릭`);
네, 불필요한 console 전부 삭제하였습니다.

2024-02-04 15:41 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
> + * - 최근 본 상품의 리스트를 보여주는 컴포넌트 입니다.
- [docs: 불필요한 라인 구분 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/c6d193d1b99f043ca186127bfb800e9715cbd544)
   - 수정하였습니다.

2024-02-04 15:43 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
- [feat: 분리해서 작업했던 recent-product 컴포넌트 통합](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/5112e09e7d9533427609ab95977729077b9c45e7)
 - [remove: recent-product 폴더 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/3724cf4fe2eef5225cd4f0b8f039160454b7b711)
   - 하나의 파일로 통합하였습니다.

2024-02-04 16:16 UTC, TransparentDeveloper requested changes
확인 부탁드립니다.!!

2024-02-04 16:16 UTC, TransparentDeveloper commented on src/components/commons/spacer.jsx
> +	const height = axis === "horizontal" ? 1 : size;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 음.. 가로 세로 길이를 동시에 줘야 한다면 어떻게 해야하나요??
- `axis` 가 필요할까 싶어요..
- width 와 height 를 props 로 받되 기본값을 0 으로 설정해주면, 둘 중 하나만 적었을때 vertical spacer 인지, horizontal spacer 인지 바로 구분이 되지 않을까요?? 추가로 둘 다 길이 값을 다르게 줄 수도 있고요.
- style 속성은 ...rest 로 다 넘어옵니다.

2024-02-04 16:16 UTC, TransparentDeveloper commented on src/components/commons/spacer.jsx
> +		/>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 스타일 속성 쓰지 말고, styled-components 의존성 추가했는데 스타일 컴포넌트로 만드는 게 좋지 않을까요?

2024-02-04 16:46 UTC, jjjiyoung0130 commented on src/components/commons/side-chat-button.jsx
> +import ResponsiveIcon from "./responsive-icon";
- [fix: 불필요한 console 삭제 및 import 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/73af76725b03f7e79630ab645b99639ac40899f3)
   - 수정하였습니다.

2024-02-04 16:47 UTC, jjjiyoung0130 commented on src/components/commons/side-chat-button.jsx
> +		console.log("채팅 버튼 클릭");
- [fix: 불필요한 console 삭제 및 import 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/73af76725b03f7e79630ab645b99639ac40899f3)
   - 수정하였습니다.

2024-02-04 16:47 UTC, jjjiyoung0130 commented on src/components/commons/spacer.jsx
> + * @parameter style = {} : object : 추가적인 스타일 객체
- [refactor: 스타일드 컴포넌트로 변경 및 props 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/a4499a1b47fb3e11b5ba1808858c9049867414b0)
   - 수정하였습니다.

2024-02-04 16:47 UTC, jjjiyoung0130 commented on src/components/commons/spacer.jsx
> +	const height = axis === "horizontal" ? 1 : size;
- [refactor: 스타일드 컴포넌트로 변경 및 props 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/a4499a1b47fb3e11b5ba1808858c9049867414b0)
   - 수정하였습니다.

2024-02-04 16:48 UTC, jjjiyoung0130 commented on src/components/commons/spacer.jsx
> +		/>
- [refactor: 스타일드 컴포넌트로 변경 및 props 수정](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/a4499a1b47fb3e11b5ba1808858c9049867414b0)
   - 수정하였습니다.

2024-02-04 17:01 UTC, hayoung78 approved these changes
확인했습니다

2024-02-04 18:07 UTC, keeprok approved these changes
오호....수고하셨습니다

2024-02-04 18:22 UTC, keeprok approved these changes
승인

2024-02-06 15:04 UTC, ijimlnosk approved these changes

2024-02-06 15:09 UTC, TransparentDeveloper requested changes
역시,,,, 대단하십니다. 👍👍

2024-02-06 15:45 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
> +	};
- [fix: 컴포넌트/스타일 컴포넌트명 수정 및 불필요한 이벤트(e) 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/53d91b24b832e9a46d19023b4c448323d7b947f5)
 - 버블링 막는 코드 를 remove에만 남길 때 `e.stopPropagation()` 코드 삭제하면서 지웠어야 했는데 안지웠네요..
   - 수정했습니다.

2024-02-06 15:45 UTC, jjjiyoung0130 commented on src/components/commons/recent-product-list.jsx
> +			</S.MovedItemButton>
- [fix: 컴포넌트/스타일 컴포넌트명 수정 및 불필요한 이벤트(e) 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/28/commits/53d91b24b832e9a46d19023b4c448323d7b947f5)
   - 수정했습니다.

2024-02-07 01:41 UTC, TransparentDeveloper approved these changes

2024-02-07 01:41 UTC, merged