PR/PD-72:  공용컴포넌트 iconAndText 작업했습니다.
PurpleDynamics/PEA_Project pull request #31
Opened 2024-02-04 15:40 UTC by snkchan

## 🎯 작업 내용

- <img width="1100" alt="Icon_and_text_PR(2)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/ae1d091a-f275-4662-8af5-c5dd5ce43f34">
- [design: 공용컴포넌트 iconAndText 작업했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/d45aacfc028605287180fe3df59c6c44d3433863)
  - icon, text, amount(수량), unit(단위), color를 입력받아 판매자 정보를 보여주는 컴포넌트입니다.
## 사용방법
- <img width="395" alt="Icon_and_text_PR(1)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/f76f10dc-4f4f-4093-b5ad-c9b09f9ca39d">
- ☝ 위의 사진처럼 사용하시면 됩니다.
## 주의사항
- icon-and-text componet가 사용되는 곳의 background 색상은 pallete.weigt계열을 사용할 예정이니
  porps로 전달하는 color는 pallete.light계열 색상을 사용하시면 됩니다.
- amount는 서버로부터 전달되는 판매자의 수량정보를 받아 사용할 예정입니다.
  만일 단위가 필요하다면 unit에 전달하시면 됩니다

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-04 15:51 UTC, TransparentDeveloper requested changes
고생하셨습니다. 👍

2024-02-04 15:51 UTC, TransparentDeveloper commented on src/components/commons/icon-and-text.jsx
> +			<S.Amount $amountColor={amountColor}>{amount + "" + unit}</S.Amount>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 수치와 단위사이에 띄어쓰기가 되는 건가요? 위에 이미지에도 띄어쓰기 없는 것 같은데,, 띄어쓰기 안쓰실 거라면 "" 안쓰는 게 좋을 것 같습니다.

2024-02-04 15:51 UTC, TransparentDeveloper commented on src/components/commons/icon-and-text.jsx
> +`;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `text`또는 `amount` 값이 길어질 경우 어떻게 처리할 지에 대해 고민해봐 주셨으면 좋겠습니다.
- 지금 상태로는 좌우로 무한히 길어질 거 같네요. 이럴 경우, 같은 `IconAndText` 컴포넌트라도 다른 사이즈가 적용될 거 같아요. 의도한 게 맞으신가요??

2024-02-04 15:51 UTC, TransparentDeveloper commented on src/components/commons/icon-and-text.jsx
> +	unit = "",
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 기본값이 없어도 되지 않나요?

2024-02-04 15:53 UTC, snkchan commented on src/components/commons/icon-and-text.jsx
> +	unit = "",
unit에대한 말씀이신가요????? 기본값을 주지않으면 undifined라고 나와서 기본값을 넣어줬습니다.

2024-02-04 16:06 UTC, jjjiyoung0130 approved these changes
깔끔하네요 따봉👍+1

2024-02-04 17:00 UTC, hayoung78 approved these changes
굳 확인했습니다~

2024-02-04 18:24 UTC, keeprok approved these changes
승인했습니다

2024-02-04 18:32 UTC, snkchan reviewed
확인좀요

2024-02-04 18:32 UTC, snkchan commented on src/components/commons/icon-and-text.jsx
> +		cursor: pointer;
여기수정해

2024-02-07 12:42 UTC, TransparentDeveloper requested changes
수정 요청 추가합니다. ㅎㅎ

2024-02-07 12:42 UTC, TransparentDeveloper commented on src/components/commons/icon-and-text.jsx
> +	}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이젠 줄일 수 있을 것 같습니다. ㅎㅎㅎ

2024-02-07 12:42 UTC, TransparentDeveloper commented on src/components/commons/icon-and-text.jsx
> +		<S.IconTextWrapper {...rest} onClick={callbackFunc()}>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```js 
<S.IconTextWrapper {...rest} onClick={callbackFunc}>
```

이렇게 써도 될것 같습니다.

2024-02-08 14:51 UTC, snkchan commented on src/components/commons/icon-and-text.jsx
> +`;
이부분은 크게 문제가 안될것 같아 그대로 두었습니다.

2024-02-08 14:52 UTC, snkchan commented on src/components/commons/icon-and-text.jsx
> +			<S.Amount $amountColor={amountColor}>{amount + "" + unit}</S.Amount>
- [fix: amount의 기본값을 ""으로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/31/commits/fddb4fadd854be2e8237aa642f683e8a1b6a568c)
- 깜빡하고 띄어쓰기가안된 부분으리ㅏ "" ->  " "로 수정했습니다.

2024-02-08 14:54 UTC, snkchan commented on src/components/commons/icon-and-text.jsx
> +		<S.IconTextWrapper {...rest} onClick={callbackFunc()}>
- https://github.com/PurpleDynamics/PEA_Project/pull/31/commits/00e8b057f3b07a3a3f52b892fa2a88172146f21f
- 해당 커밋에서 callbackFunc() => callbackFunc로 수정했습니다.

2024-02-08 14:54 UTC, snkchan commented on src/components/commons/icon-and-text.jsx
> +	}
- https://github.com/PurpleDynamics/PEA_Project/pull/31/commits/00e8b057f3b07a3a3f52b892fa2a88172146f21f
- 해당 커밋에서 수정완료했습니다.

2024-02-08 14:58 UTC, snkchan commented
## 추가수정사항 있습니다.!! 확인부탁드려요 
- hooks > useFilterAmount 함수작성  
- icon의 amount + unit 부분에 위의함수적용시 아래 사진처럼 보이게됩니다.
- <img width="353" alt="Icon_and_text_PR(5)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/1d75217f-0e5a-42b8-b1db-affee095d1db">

2024-02-08 15:00 UTC, keeprok approved these changes
확인했습니다

2024-02-09 01:06 UTC, ijimlnosk approved these changes
잘 봤습니다 좋습니다

2024-02-09 16:33 UTC, snkchan commented
## 수정사항
- hooks아래 useFilterAmount 에서 ==> utils아래 data-editor.js 파일안에 appendUnit함수 생성
## 참고
- appendUnit함수는 unit에 " º " 를 입력시 소수점 첫째짜리까지 표현, 나머지 unit은 정수만 표현되도록 동작합니다.
- 

<img width="248" alt="Icon_and_text_PR(7)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/c0408e9f-74fb-4776-a3c2-ede15aee7c36">
<img width="247" alt="Icon_and_text_PR(8)" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/25c875a5-98f2-40fa-8ec3-6daf35a57d1f">

2024-02-09 16:38 UTC, TransparentDeveloper requested changes
역시...👍

2024-02-09 16:38 UTC, TransparentDeveloper commented on src/utils/data-editor.js
> + * @paramter unit : 수량 data에 맞는 단위
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 타입 미명시 입니다..

2024-02-09 16:42 UTC, snkchan commented on src/utils/data-editor.js
> + * @paramter unit : 수량 data에 맞는 단위
- [chore: paramter tpye작성](https://github.com/PurpleDynamics/PEA_Project/pull/31/commits/14e6ac42b8f054dd1a538fbccf24e7f85b3a310c)
- 두 paramter모두 string type으로 docs에 작성해두었습니다.

2024-02-09 16:42 UTC, TransparentDeveloper approved these changes

2024-02-09 16:42 UTC, merged