PR/PD-48: login-page 생성했습니다.
PurpleDynamics/PEA_Project pull request #32
Opened 2024-02-04 16:52 UTC by hayoung78

## 🎯 작업 내용

![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/64f8f2b7-933c-4c52-9495-e0273dfb7770)
[feat: signin page 생성](https://github.com/PurpleDynamics/PEA_Project/commit/8d8017942fa6ace23f8768cf9fb3497ac822b2dd)
- signin-page 생성했습니다.
- 회원가입과 마찬가지로 이메일과 비밀번호 창에는 ```constants```폴더 안에 유효성 검사 메세지 ```VAILDAITION``` 을 넣었습니다.
- 로그인 버튼은 이메일과 비밀번호 형식에 맞으면 자동으로 활성화되도록 했습니다.
<video src="https://github.com/PurpleDynamics/PEA_Project/assets/142880051/68d13629-d819-4a71-ae06-f105841fca10"></video>

- signup 페이지와 같이 화면이 어느정도 크기 까지 작아지면 (```BREAK_POINT.md```) 아래 화면과 같이 반응합니다.
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/b2f1cd6e-5790-4e61-bd81-a4e3ac9d084f)

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-04 17:30 UTC, snkchan requested changes
고생하셧습니다. 리뷰확인해주세요~

2024-02-04 17:30 UTC, snkchan commented on src/pages/signin-page.jsx
> + * @parameter handleSubmit : form 제출시 사용되는 parameter입니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- parameter 에 적어주신것들은 SigninPage를 불러오는 쪽에서 넘겨주는 parameter를 작성해주셔야하는데 
  지금 SigninPage는 전달받는 parameter가 없습니다.  
  docs에 적어주신 paramtersms 20~21번째 줄에 작성해주시면 좋을것 같아요.
- docs에 description이 빠졋는데 같이적어주시면 좋을것 같습니다.

2024-02-04 17:30 UTC, snkchan commented on src/pages/signin-page.jsx
> +		navigate("");
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- navigate()까지 적어주셧다면 추후에 작업하기편하게 main페이지의 주소를 적어주시면 좋을것 같아요.
- form tag의 제출이벤트를 막기위해 e.preventDefault() 도 미리 적어주시면 좋을것 같아요.

2024-02-04 17:30 UTC, snkchan commented on src/pages/signin-page.jsx
> +		formState: { errors, isValid, dirtyFields },
isValid와 dirtyFields의 용도가 어떤건지 알 수 있을까요??

2024-02-04 17:30 UTC, snkchan commented on src/pages/signin-page.jsx
> +				</CheckboxWrapper>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- CheckboxWrapper와 CheckBoxinput은  둘다 대문자 Box로적어주시는게 맞을것 같아요 그리고 객체S에 안넣으셔서 수정해야합니다.

2024-02-04 17:35 UTC, jjjiyoung0130 requested changes

2024-02-04 17:35 UTC, jjjiyoung0130 commented on src/pages/signin-page.jsx
> +					<Button type="button" width="30rem">
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 회원가입 페이지 작업도 되어있는데 onClick 이벤트를 추가하고 navigate로 회원가입 페이지를 연결시켜놓으면 좋지않을까요?

2024-02-04 18:13 UTC, keeprok approved these changes
확인했습니다

2024-02-04 18:24 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +		formState: { errors, isValid, dirtyFields },
isVaild: 현재 폼의 유효성 여부 , dirtyFields: 사용자가 입력한 값이 변경되었는지 여부 확인하는 용도로 사용합니다. 
주석으로 달아놓겠습니다.

2024-02-04 18:26 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +		navigate("");
메인페이지는 (/"") 입니다 ^^
form 태그에 e.preventDefault() 넣어 수정했습니다.

2024-02-04 18:35 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +				</CheckboxWrapper>
[feat: 태그명 통일 및 수정](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/c47949c982b60958ca7d5e27a802bda6a4ca9a9f)
수정했습니다

2024-02-04 18:35 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +		formState: { errors, isValid, dirtyFields },
[refactor : docs 내용 수정 및 태그 수정완료](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/21df7c3634473ef4101b6e6b41b01d0cfa1c81f6)

2024-02-04 18:36 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +		navigate("");
[refactor : docs 내용 수정 및 태그 수정완료](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/21df7c3634473ef4101b6e6b41b01d0cfa1c81f6)

2024-02-04 18:36 UTC, hayoung78 commented on src/pages/signin-page.jsx
> + * @parameter handleSubmit : form 제출시 사용되는 parameter입니다.
[refactor : docs 내용 수정 및 태그 수정완료](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/21df7c3634473ef4101b6e6b41b01d0cfa1c81f6)

use-hook-form에서 사용하는 반환값들은 20번째줄에 넣어 수정했습니다.
확인부탁드립니다.

2024-02-04 18:41 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +					<Button type="button" width="30rem">
[feat : 회원가입버튼 onClick이벤트 추가](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/8a8a10858e23a820cf90e7d8dc8c64110968f315)

onClick이벤트 추가하고 회원가입 페이지로 이동하는것까지 확인했습니다~

2024-02-05 00:35 UTC, jjjiyoung0130 approved these changes

2024-02-05 05:01 UTC, ijimlnosk approved these changes

2024-02-05 09:35 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +	grid-template-columns: 62.5rem 62.5rem;
넴 담번에는 repeat 사용해서 해보겠습니다~~ (2개 이상일때)

2024-02-06 13:19 UTC, snkchan approved these changes
고생하셧습니다. 👍👍

2024-02-06 14:24 UTC, TransparentDeveloper requested changes

2024-02-07 02:38 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +`;
[design : img태그css 수정](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/fb59179c2be028dac7819652f821c45139915f71)

이미지 태그 안에 width 추가하고 스타일 컴포넌트 삭제했습니다.

2024-02-07 02:39 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +				</S.CheckboxWrapper>
[design: CheckBox 스타일 컴포넌트 수정](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/ea8750ca084071ac637b1e31a1e4d56a15ec68e0)
스타일 컴포넌트 사용법에 맞춰서 수정했습니다.

2024-02-07 02:40 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +				</S.CheckboxWrapper>
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/e270097f-2eab-48b2-b7a2-54b861b69add)

2024-02-07 02:41 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +	} = useForm({ mode: "onChange" });
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/0591dd40-e306-4178-82a9-d9d9c7acc9d5)
[chore : docs 내용 수정했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/3dd6248f48367c52374f6585d42a4c0ced1c9055)
dosc 내용 수정했습니다.

2024-02-07 02:49 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +									: COLOR.COMMON[600],
```
<Button 
type="submit"
width="30rem"
disabled={ !dirtyFields.email || !dirtyFields.password || !isValid}>
로그인  </Button>
```

[feat : Button에 disabled 속성값 추가](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/426814429cd08ac92988c23745e4bf21002e9acb)
수정했습니다.

2024-02-07 02:51 UTC, hayoung78 commented
[feat : Button에 disabled 속성값 추가](https://github.com/PurpleDynamics/PEA_Project/pull/32/commits/426814429cd08ac92988c23745e4bf21002e9acb)
- disabled 속성 추가하고 기능 되는것까지 확인했습니다.

<video src="https://github.com/PurpleDynamics/PEA_Project/assets/142880051/8b96dbb9-9d37-43bc-8e83-b22951bacec7"></video>

2024-02-07 02:58 UTC, TransparentDeveloper approved these changes

2024-02-07 02:59 UTC, merged