PR/PD-77: 회원정보수정 오버레이 모달을 생성했습니다.
PurpleDynamics/PEA_Project pull request #33
Opened 2024-02-04 20:00 UTC by KR-HeoJU

## 🎯 작업 내용

- [design: 회원정보수정 overlay modal 생성했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/6b4aadfc9e6f7418f2b1413c4d6abf6c7c3837a0)
  - 이 commit 에서는 회원정보 수정을 위한 modal 창을 생성하였습니다.
  - 이 modal 창은 overlay로 나타납니다.

https://github.com/PurpleDynamics/PEA_Project/assets/142701420/4ee91194-1c38-440d-86cd-bb8ca69bfc24

구현 예정 사항
1. 실제 user 에 따라 data 값 불러와서 placeholder 기본 값에 반영하기
2. 중복 확인 기능
3. 주소 검색 기능
4. 회원 탈퇴 페이지 연동
5. 정보 변경 시 정보 변경을 확인하는 modal 창 띄우기
6. 수정된 data를 서버에 반영하기

상기 구현 예정 사항 중 시작 가능한 작업이 있으면 추후 반영하겠습니다.

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
8. "Review Changes" Button 클릭합니다.
9. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-05 12:16 UTC, hayoung78 requested changes
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
리뷰 확인해주세요~~
+ reviewers에 진욱님 제외하고 모두 체크해주셔야합니다~!

2024-02-05 12:16 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +							</>
여기에 fragment는 왜 있는걸까요 ??

2024-02-05 12:16 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +							</>
그리고 저렇게 컬러를 직접 사용하지 않고 제가 알기로는 ``` styled-components ``` 에 ```reference-token``` -> ```color.js``` 에 error 컬러가 빨간계열? 인걸로 알고있는데, 그걸 사용하는게 더 낫지 않을까요 ??

2024-02-05 12:16 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +					<span style={{ fontSize: "1.2rem", color: "red" }}>
``` reference-token ``` 에 font-size 사용하는게 더 좋지 않을까용? :)

2024-02-05 12:16 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +const Container = styled.div`
전체적으로 이름들이 더 명확하고 누가봐도 어느부분인지 알수있게 작성해주셨으면 더 좋았을것같습니다!

2024-02-05 12:16 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +	margin-bottom: 20px;
rem으로 표현할수있는 부분은 rem으로 하시는게 좋지 않을까요 ???

2024-02-05 12:16 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +							</>
스판태그는 왜 innerCSS로 작성하신건가요 ??

2024-02-05 12:16 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +	color: black;
색상 ```color.js```에서 사용하시면 좋을것같습니다.

2024-02-05 12:18 UTC, hayoung78 commented on src/components/overlay/edit-user-info-window.jsx
> +const Container = styled.div`
스타일 태그들 이름이 너무 포괄적(?) 이고 직접적이지 않는것같습니다..

2024-02-05 18:50 UTC, KR-HeoJU commented on src/components/commons/input.jsx
> +			<S.BorderBox style={borderBoxStyle}>
잘못했어요 다시 input 브랜치에서 수정할 수 있도록 복구 했습니다

2024-02-05 18:50 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +import { VAILDATION } from "../../constants";
감사합니다

2024-02-05 20:12 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +							</>
> 여기에 fragment는 왜 있는걸까요 ??

JSX에서는 부모 요소가 하나의 요소만 가질 수 있기 때문에
여러 자식 요소를 그룹화하기 위해서 사용하였습니다.

> 그리고 저렇게 컬러를 직접 사용하지 않고 제가 알기로는 `styled-components` 에 `reference-token` -> `color.js` 에 error 컬러가 빨간계열? 인걸로 알고있는데, 그걸 사용하는게 더 낫지 않을까요 ??

> 스판태그는 왜 innerCSS로 작성하신건가요 ??

피그마 참고하여 magenta.base 로 수정하였습니다. 스판 태그도 styled-component 로 수정하였습니다.

```js
const Span = styled.span`
	color: ${COLOR.PALETTE.magenta.base};
`;
```

2024-02-05 20:18 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +					<span style={{ fontSize: "1.2rem", color: "red" }}>
> `reference-token` 에 font-size 사용하는게 더 좋지 않을까용? :)

```js
const Caution = styled.div`
...생략...
	span {
		font-size: ${FONT_SIZE.sm};
	}
`;
```

수정하였습니다.

2024-02-05 20:24 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +const Container = styled.div`
> 전체적으로 이름들이 더 명확하고 누가봐도 어느부분인지 알수있게 작성해주셨으면 더 좋았을것같습니다!
> 스타일 태그들 이름이 너무 포괄적(?) 이고 직접적이지 않는것같습니다..

```js
return (
	<S.EditUserInfoWindowContainer>
		<S.EditUserInfoForm onSubmit={handleSubmit(onSubmit)}>
			<S.EditUserInfoTitle>회원 정보 수정</S.EditUserInfoTitle>
			<S.EditUserInfoCaution/>
			<S.EditUserInfoInputFields/>
		</S.EditUserInfoForm>
	</S.EditUserInfoWindowContainer>
);
```

수정하였습니다.

2024-02-05 20:26 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +	margin-bottom: 20px;
> rem으로 표현할수있는 부분은 rem으로 통일 하시는게 좋지 않을까요 ???

```js 
//rem 이외의 속성 생략
const EditUserInfoWindowContainer = styled.div`
	width: 80rem;
	padding: 2rem;
	border-radius: 3.8rem;
	box-shadow: 0px 0.4rem 0.8rem rgba(${COLOR.COMMON[0]}, 0.1);
`;
const EditUserInfoTitle = styled.div`
	margin-bottom: 2rem;
`;
const EditUserInfoCaution = styled.div`
	margin-bottom: 3rem;
	width: 17rem;
	margin-left: 18rem;
`;
const Buttons = styled.div`
	margin-top: 1rem;
`;
```
수정하였습니다.

2024-02-05 20:29 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +	color: black;
> 색상 `color.js`에서 사용하시면 좋을것같습니다.
> 전체적인 CSS 부분 공용 컴포넌트 color 랑 font-size 에서 사용할수있다면 활용하시는게 좋을것같습니다.

```js
// color, font-size 이외의 속성 생략
const EditUserInfoWindowContainer = styled.div`
	background-color: ${COLOR.COMMON[1000]};
	box-shadow: 0px 0.4rem 0.8rem rgba(${COLOR.COMMON[0]}, 0.1);
`;
const EditUserInfoTitle = styled.div`
	font-size: ${FONT_SIZE.xl};
	color: ${COLOR.COMMON[0]};
`;
const Span = styled.span`
	color: ${COLOR.PALETTE.magenta.base};
`;
const EditUserInfoCaution = styled.div`
	font-size: ${FONT_SIZE.sm};
	span {
		font-size: ${FONT_SIZE.sm};
	}
`;
```
수정하였습니다.

2024-02-06 05:54 UTC, jjjiyoung0130 requested changes
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - jsDoc는 작성하지 않으셨나요?

2024-02-06 05:58 UTC, jjjiyoung0130 commented
> # Request Level
> * [ ]  N : "🔥 이대로 Merge 하면 안돼요~!"
> * [ ]  M : "🥹 고치면 분명 나아질 게 분명합니다.."
> * [x]  S : "🤷 수정하면 좋지 않을까요?"
> 
> # Description
> * 불필요한 console은 지워주세요 :)

2024-02-06 06:35 UTC, jjjiyoung0130 requested changes

2024-02-06 06:35 UTC, jjjiyoung0130 commented on src/components/overlay/edit-user-info-window.jsx
> +						defaultValue={"주소로딩"}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 닉네임, 주소, 휴대폰 번호의 defaultValue는 임의로 넣어둔 것인가요? 그렇다면 commit 시에는 지워주는 게 좋을 것 같습니다.
 - Input 컴포넌트의 ...rest 로 defaultValue가 입력된 것 같은데 그렇다면 defaultValue에 대해서도 jsDoc 명시해주면 좋지않을까 생각됩니다.

2024-02-06 06:35 UTC, jjjiyoung0130 commented on src/components/overlay/edit-user-info-window.jsx
> +								<S.Span>*</S.Span>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 이메일은 회원 정보 수정의 필수 항목이 아닌데 *표시와 span 태그는 없어도 되지않을까요?

2024-02-06 11:34 UTC, keeprok commented
주소입력 되게하셨는데 저희 주소 직접입력 가능한건가요?? 검색하기 해서 받아온걸로만 작성하기위해서 검색하기 있는거 아닌지 생각이듭니다

2024-02-06 11:39 UTC, keeprok commented on src/components/overlay/edit-user-info-window.jsx
> +								주소
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x ] S : "🤷 수정하면 좋지 않을까요?"

# Description
저희 주소 직접입력 가능한건가요 ?? 검색하기 기능을 통해서 만 되는것아닐까요?? 그리고 검색하기버튼에 아직 기능은없지만 onClick 미리 넣어놓는건 어떤가요..?

2024-02-06 11:39 UTC, keeprok commented on src/components/overlay/edit-user-info-window.jsx
> +					<S.Buttons>
**# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
** Buttons보단 ButtonBox나 Contain이 낫지않을까요??

2024-02-06 15:11 UTC, TransparentDeveloper requested changes
오.. 대단합니다. 고수셨군요;;

2024-02-06 16:11 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +						defaultValue={"주소로딩"}
> * 불필요한 console은 지워주세요 :)
```js
const onSubmit = (data) => {
	if (!data.password) {
		delete data.password;
		delete data.passwordConfirm;
	}
	불필요한 콘솔 삭제
	onClose();
};
```
수정하였습니다.

> * 참고 영상을 보니 회원정보를 입력하고 :회원 탈퇴" 버튼을 클릭하면 Modal이 close되는 거 같은데 아직 기능 구현의 단계는 아니지만 실제 로직을 저렇게 가지는 않으시겠죠?

"회원 탈퇴 버튼"과 "정보 변경 버튼"을 누르면 임시 modal 창이 absolute 포지션으로 나타나도록 수정하였습니다.

> * "정보 변경"의 경우 "새 비밀번호"와 "새 비밀번호 확인"이 필수 응답 항목으로 들어갈건지 궁금합니다.

```js
validate={{
	pattern: VAILDATION.PASSWORD_CONFIRM,
	validtae: (value) =>
	value === newPassword || (!value && !newPassword) || VAILDATION.PASSWORD_CONFIRM.message,
}}
```

필수 응답에서 제외하고, 빈 값으로 제출될 경우 기존 비밀번호를 그대로 사용하도록 수정하였습니다.

> * 닉네임, 주소, 휴대폰 번호의 defaultValue는 임의로 넣어둔 것인가요? 그렇다면 commit 시에는 지워주는 게 좋을 것 같습니다.

```js
value={""}
```
빈 값으로 수정하였습니다.

> * Input 컴포넌트의 ...rest 로 defaultValue가 입력된 것 같은데 그렇다면 defaultValue에 대해서도 jsDoc 명시해주면 좋지않을까 생각됩니다.

```js
/**
 * 회원 정보 수정 오버레이 컴포넌트
 * @component
 * @parameter {Function} onClose - 오버레이를 닫는 콜백 함수
 * @returns {JSX.Element}
 *
 * @description
 * - useForm을 사용하여 폼 관리 및 유효성 검사를 수행합니다.
 * - 오버레이에서 회원 정보를 수정하고, '정보 변경' 버튼을 눌러 변경사항을 저장할 수 있습니다.
 * - '회원 탈퇴' 버튼을 눌러 탈퇴 할 수 있습니다.
 * - Input 의 value 값에는 user의 현재 회원정보가 반영됩니다.
 *
 */
 ```
 
 수정하였습니다.

2024-02-06 16:18 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +								<S.Span>*</S.Span>
*표시와 span 태그 제거했습니다.

2024-02-06 16:18 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +					<span style={{ fontSize: "1.2rem", color: "red" }}>
수정하였습니다.

2024-02-06 16:23 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +					<S.Buttons>
ButtonsBox 로 수정하였습니다.

2024-02-06 16:23 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +		onClose();
삭제하였습니다.

2024-02-06 16:30 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +								주소
```js
<Input
	...중략...
	readOnly={true}
/>
```

읽기전용으로 변경했습니다.


```js
<S.TextButton
	onClick={(e) => {
		handleButton();
		e.preventDefault(); // form 태그 내부에 작성된 버튼이기 때문에, 제출 이벤트를 방지합니다.
	}}
>
	{buttonText.trim()}
</S.TextButton>
```

onClick과 handleButton=()=>{} 은 input.jsx 내에 있습니다. 검색하기 기능이 추가되면 수정하겠습니다.

2024-02-06 17:38 UTC, KR-HeoJU commented
https://github.com/PurpleDynamics/PEA_Project/assets/142701420/4f705c4e-7434-4b18-96de-254fa206cc70

@parameter 작성법과 registerKey 값 상수화는 수정 예정입니다.

2024-02-11 12:25 UTC, ijimlnosk approved these changes
오...수정사항들이 많네요 고생하셨습니다.

2024-02-11 13:15 UTC, hayoung78 approved these changes

2024-02-11 14:40 UTC, jjjiyoung0130 approved these changes

2024-02-17 18:34 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> + * @returns {JSX.Element}
수정하였습니다

2024-02-17 18:36 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +					<span style={{ fontSize: "1.2rem", color: "red" }}>
그게 좋을 것 같습니다

2024-02-17 18:37 UTC, KR-HeoJU commented
https://github.com/PurpleDynamics/PEA_Project/assets/142701420/35810a06-ac8a-444c-a788-c78a596c21cf

Modal 창 overlay 기능으로 구현하였습니다.

2024-02-20 16:49 UTC, TransparentDeveloper requested changes

2024-02-20 16:49 UTC, TransparentDeveloper commented on src/components/overlay/edit-user-info-window.jsx
> +			].find((key) => errors[key]);
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- errors 안에 이미 키값이 있을 텐데, 배열화하면 순회하지 않고 더 효율적으로 key 값을 얻을 수 있지 않을까요?

2024-02-20 16:49 UTC, TransparentDeveloper commented on src/components/overlay/edit-user-info-window.jsx
> +		}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 모달이 있는데, alert 를 사용을 굳이 해야할까요?

2024-02-20 16:49 UTC, TransparentDeveloper commented on src/components/overlay/edit-user-info-window.jsx
> +	const [modalType, setModalType] = useState("");
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 모달 타입을 상태로 관리해야 할까요? 
- 불필요하게 리렌더링이 일어나는 것 같습니다.
- 각 버튼 클릭 시, 일어나는 이벤트 로직을 두 개 각각 준비하면 좋지 않을까요?

2024-02-21 15:01 UTC, KR-HeoJU commented
https://github.com/PurpleDynamics/PEA_Project/assets/142701420/69209b60-da22-456d-b941-e45d1c008386

에러 메시지도 모달 오버레이로 구현하였습니다.

2024-02-21 15:10 UTC, KR-HeoJU commented on src/components/overlay/edit-user-info-window.jsx
> +	const [modalType, setModalType] = useState("");
모달 상태를 제거하고, 이벤트 로직 두 개로 적용하였습니다.

2024-02-21 15:43 UTC, TransparentDeveloper approved these changes

2024-02-21 15:43 UTC, merged