PR/PD-47: design/publish-main
PurpleDynamics/PEA_Project pull request #34
Opened 2024-02-05 08:30 UTC by ijimlnosk

## 🎯 작업 내용

- [fix : compression-container 오타 수정](https://github.com/PurpleDynamics/PEA_Project/commit/72997256c12e0c4cd3b006546002c576e08306a8)
  - index.js 의 compression-container 오타 수정 했습니다 

- [design: publish-main](https://github.com/PurpleDynamics/PEA_Project/commit/eb832e049d79b8fe7ef2e876f2484cdea245a1e3)
  - components/main 밑에
  - eight-product-grid.jsx 추가
    - product-list-page에 보여지는 OO동 중고거래 및 OO동 무료나눔에 보여지는 title과 product card를 8개씩 보여주는 컴포넌트 입니다.
    - 현재 임시 유저 데이터 location 과 임시 프로덕트 데이터의 location, salesCategory로 사용자의 위치별로 불러오고 중고판매 || 무료나눔으로 나누어 보여주고 있습니다.
    - ![스크린샷 2024-02-05 오후 5 25 57](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/0c93c351-db97-4c02-98a5-1979b25fb53c)
    - ![스크린샷 2024-02-05 오후 5 26 12](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/feb9afe7-f7c9-4e23-b3ae-c2009da82683)
    - ![스크린샷 2024-02-05 오후 5 26 06](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/aa6576c2-679b-4e2e-a624-e98304bcbfad)

  - index.js 추가
  - promotion-banner.jsx 추가
    - product-list-page에 제일 처음 보여지는 promotion banner 입니다.
    - 마땅한 이름이 생각나지 않아 promotion banner로 작성하게 되었습니다 (의견 주세요)
    - button을 누르면 해당 페이지로 이동해야 됩니다.
    - 더 큰 font-size가 필요합니다.
![스크린샷 2024-02-05 오후 5 23 41](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/652995a5-dfb0-4d24-aa4a-b76d5ac40dd6)

- [fix: promotion-banner 의 button box 크기 조정](https://github.com/PurpleDynamics/PEA_Project/commit/a054a6ef3828ad04463e8fd1003ffc2f3a6bb9c2)
  - promotion-banner 의 크기를 수정했습니다.

<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] PR 제목 (컨벤션에 따랐는지) 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-06 01:25 UTC, ijimlnosk commented
[chore: js doc 추가 및 수정](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/18f78363ddfc3eec5ea1607c69cb6faa25d5deef)
02/06 js doc에 빠져있는 내용을 발견하여 추가 했습니다.

2024-02-06 07:21 UTC, jjjiyoung0130 requested changes

2024-02-06 07:21 UTC, jjjiyoung0130 commented on src/components/main/eight-product-grid.jsx
> +const TextWrppaer = styled.div`
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 오타있습니다. "TextWrppaer" -> "TextWrapper" 수정해주세요.

2024-02-06 07:21 UTC, jjjiyoung0130 commented on src/components/main/eight-product-grid.jsx
> +const UesdFreeText = styled.span`
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 혹시 이 부분도 Used의 오타일까요? "UesdFreeText" -> "UsedFreeText"

2024-02-06 07:21 UTC, jjjiyoung0130 commented on src/components/main/eight-product-grid.jsx
> +							<S.NoDataText>No matching data found</S.NoDataText>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - data가 없는 경우를 피그마에 정의해놓지 않은 것 같은데 이건 디자인 쪽 과실입니다만, 개인적인 의견으로 피그마의 [검색결과_등록상품x]의 레이아웃에 보여지는 내용과 동일하게 "등록된 상품이 없습니다"가 문구로 보여지면 어떨까 싶습니다.

2024-02-06 07:36 UTC, jjjiyoung0130 requested changes

2024-02-06 07:36 UTC, jjjiyoung0130 commented on src/components/main/promotion-banner.jsx
> + * - product list page에 제일 처음에 올라오는 컴포넌트입니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - description이 한 줄일 경우 @description 옆에 한 칸 띄어서 작성해주세요 :)

2024-02-06 07:36 UTC, jjjiyoung0130 commented on src/pages/product-list-page.jsx
> +	const usedData = data
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - mock data지만 data 내에 createdAt(등록일)과 status(판매상태)를 추가해서 최근 등록된 상품 중 판매중 상태인 data도 조건으로 추가해서 slice 해보는게 어떻까요?

2024-02-06 11:20 UTC, ijimlnosk commented on src/pages/product-list-page.jsx
> +	const usedData = data
아직 디자인 부분이라 세부적인건 작성하지 않았습니다
우선 데이터가 왔을 때 뿌려지는 부분을 보기위해 작성한 것이라 
추후 feat 작성 시 반영해 보겠습니다.

2024-02-06 11:26 UTC, ijimlnosk commented on src/components/main/eight-product-grid.jsx
> +const TextWrppaer = styled.div`
[fix: textWrapper 오타수정](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/a8c188d5278060f484b9479dd7a60978ea65cfc7)
수정 완료했습니다

2024-02-06 11:27 UTC, ijimlnosk commented on src/components/main/eight-product-grid.jsx
> +const UesdFreeText = styled.span`
[fix: usedFreeText 오타 수정](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/cdfac4ecd8d454adc017a553961a396c56da7646)
수정 했습니다

2024-02-06 11:27 UTC, ijimlnosk commented on src/components/main/eight-product-grid.jsx
> +							<S.NoDataText>No matching data found</S.NoDataText>
[refactor: 데이터가 없을 시 문구 수정](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/edd78cffa7b09f20ef1d6d27769e91a7fe28f236)
수정 완료했습니다

2024-02-06 11:28 UTC, ijimlnosk commented on src/components/main/promotion-banner.jsx
> + * - product list page에 제일 처음에 올라오는 컴포넌트입니다.
[fix: js doc 수정](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/e144cc8a17f95ac9c300f9902717236772a67ca9)
수정 완료했습니다

2024-02-06 11:30 UTC, keeprok commented on src/components/main/eight-product-grid.jsx
> + * - salesCategory에 중고판매 || 무료나눔을 입력받아 8개의 product card를 보여주는 컴포넌트입니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
@parameter랑 일치하게 중고 거래 로 하는게 좋지않을까요 그리고 parmater부분 중고 거래 오타있습니다

2024-02-06 11:30 UTC, keeprok commented on src/components/main/eight-product-grid.jsx
> +		<>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
<></>없어도 되지않을까요??

2024-02-06 11:44 UTC, ijimlnosk commented on src/components/main/eight-product-grid.jsx
> + * - salesCategory에 중고판매 || 무료나눔을 입력받아 8개의 product card를 보여주는 컴포넌트입니다.
[fix : js doc 수정 및 불필요한 프래그먼트 제거](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/14473fae6bd53390fccd67c5b53d8a2f88c1c801)
수정 완료했습니다

2024-02-06 11:44 UTC, ijimlnosk commented on src/components/main/eight-product-grid.jsx
> +		<>
[fix : js doc 수정 및 불필요한 프래그먼트 제거](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/14473fae6bd53390fccd67c5b53d8a2f88c1c801)
임시로 넣어 놓고 깜빡했네요

2024-02-06 14:14 UTC, snkchan approved these changes
고생하셧습니다.. 몇가지만 수정하면 될 것 같아요

2024-02-06 14:14 UTC, snkchan commented on src/components/main/eight-product-grid.jsx
> +						<S.NoDataText>등록된 상품이 없습니다.</S.NoDataText>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
현재 코드에서 "등록된 상품이 없습니다."는 왼쪽으로 나오게될것 같은데 코드 수정이 필요해보입니다.!

2024-02-06 14:14 UTC, snkchan commented on src/components/main/promotion-banner.jsx
> +		<S.PromoWrapper>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- S.PromoWrapper 가 CompressionContainer하나를 감싸고있는데 저희 다른 파일들에서 하나의 태그만 감싸는경우 container를 사용했던거 같은데 S.PromoContainer가 맞지않을까요?
- 추가로 
- <img width="572" alt="image" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/6a677158-9f5c-4044-b978-7715411ff1ba">
- figma에서 확인해보면 banner의 위치가 저파란선 안에 들어가야하는데 작업하신 것을 보면 왼쪽으로 너무 와있는거 같습니다.

2024-02-06 14:14 UTC, snkchan commented on src/components/main/eight-product-grid.jsx
> + * @returns
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
return 값이 빠져있습니다.

2024-02-06 14:15 UTC, snkchan requested changes
고생하셧습니다.. 몇 가지만 수정하면 될 것 같습니다.

2024-02-06 14:53 UTC, ijimlnosk commented on src/components/main/promotion-banner.jsx
> +		<S.PromoWrapper>
![스크린샷 2024-02-06 오후 11 50 47](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/93260e18-5782-46ac-bb44-a0227ca64f67)
- [fix: promotion banner 가 중간에 오도록 조정했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/3e7b9c23f52a0ec4a1f112b3505c81c430d89bbb)
- 가운데에 보이도록 조정을 완료했습니다~~~

2024-02-06 14:54 UTC, ijimlnosk commented on src/components/main/eight-product-grid.jsx
> + * @returns
- [fix: js doc를 수정했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/c72daec22f894ac15bb9b8bd9b43d6fb066b9241)
- 추가했습니다

2024-02-06 14:55 UTC, ijimlnosk commented
- [refactor: container와 wrapper의 위치를 변경했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/3e7b9c23f52a0ec4a1f112b3505c81c430d89bbb) 
[3e7b9c2](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/3e7b9c23f52a0ec4a1f112b3505c81c430d89bbb)
- fix: promotion banner 가 중간에 오도록 조정했습니다.

container 와 wrapper가 맞지않아서 변경했습니다.

2024-02-06 14:55 UTC, ijimlnosk commented
- [fix: js doc를 수정했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/c72daec22f894ac15bb9b8bd9b43d6fb066b9241) 
[c72daec](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/c72daec22f894ac15bb9b8bd9b43d6fb066b9241)
- data가 없을 때 가운데에 출력되도록 했습니다
- 반응형 700px일 때를 추가했습니다
- 중고거래와 무료나눔의 위치를 조정했습니다.

2024-02-06 15:25 UTC, TransparentDeveloper requested changes
굳굳 좋습니다.

2024-02-06 15:25 UTC, TransparentDeveloper commented on src/components/main/promotion-banner.jsx
> +								<S.PromoTitleSpan>중고</S.PromoTitleSpan>
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 불필요한 텍스트가 포함된것 같습니다 💦

2024-02-06 15:25 UTC, TransparentDeveloper commented on src/pages/product-list-page.jsx
> +			></EightProductGrid>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `<EightProductGrid />` 이런식으로 작성이 가능할 거 같습니다.

2024-02-06 15:26 UTC, ijimlnosk commented on src/components/main/promotion-banner.jsx
> +								<S.PromoTitleSpan>중고</S.PromoTitleSpan>
- [fix: 불필요한 텍스트 제거](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/6fc408ab4c2e392219297df1bd414b4d23c2ff9a)
- 수정 완료했습니다.

2024-02-06 15:29 UTC, ijimlnosk commented on src/pages/product-list-page.jsx
> +			></EightProductGrid>
- [fix: eight product grid 사용 단축](https://github.com/PurpleDynamics/PEA_Project/pull/34/commits/e38926420f76d7933f2d0dd263afd7df93ee6689)
- 수정 완료했습니다

2024-02-06 15:49 UTC, snkchan approved these changes
1따봉 드리고가겠습니다. 👍

2024-02-07 01:43 UTC, TransparentDeveloper approved these changes

2024-02-07 01:52 UTC, jjjiyoung0130 approved these changes

2024-02-07 01:59 UTC, hayoung78 approved these changes
확인했습니다

2024-02-07 02:11 UTC, merged