PR/PD-62: 거래 형태에 따른 상품 리스트 출력 로직 작성했습니다.
PurpleDynamics/PEA_Project pull request #36
Opened 2024-02-07 03:01 UTC by TransparentDeveloper

## 🎯 작업 내용

- [config: axios 를 통한 fetching 함수 파일 생성](https://github.com/PurpleDynamics/PEA_Project/commit/aa1643cdc9f33334c1bb29dc98b0ed23f26df75a)
  - axios 사용 함수를 정리할 폴더 구조 잡아두었습니다.
  - 광고 서버(ads), 사용자 인증 서버(auth), 데이터 서버(base) 아래 나눠서 fetching 함수를 나눠 작성해주세요.
  
  
- [feat: 거래형태에 따른 상품 리스트 반환 로직 보안](https://github.com/PurpleDynamics/PEA_Project/commit/41eaccce7a894f3c58e35720549221c131a53961)
  - `getProductsByPaymentMethod` 함수를 이용하면, 데이터 리스트를 받을 수 있습니다. 

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-07 03:36 UTC, ijimlnosk commented on src/libs/msw/database/users.json
> +			"location": "강남구 역삼역",
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [] S : "🤷 수정하면 좋지 않을까요?"

# Description
- location에 00구 00역 00동 까지 나와야 될 것 같습니다.

2024-02-08 12:24 UTC, hayoung78 requested changes
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/206943b7-f13b-419a-9660-330bf5dda9b9)


jsDocs가 하나도 없네요..

2024-02-09 13:44 UTC, jjjiyoung0130 approved these changes
깔끔해보이네요

2024-02-09 17:02 UTC, jjjiyoung0130 approved these changes
mock data에 대해 배우고 갑니다

2024-02-09 17:04 UTC, jjjiyoung0130 reviewed
실제 데이터를 받아올 떄와 어느정도의 차이가 있을지 궁금하네요 :)

2024-02-12 09:14 UTC, TransparentDeveloper commented on src/libs/msw/database/users.json
> +			"location": "강남구 역삼역",
00시 00구 00동 으로 수정했습니다. 👍

2024-02-12 13:54 UTC, ijimlnosk commented on src/libs/msw/database/users.json
> +			"location": "강남구 역삼역",
확인했습니다

2024-02-12 13:54 UTC, ijimlnosk approved these changes

2024-02-12 14:03 UTC, snkchan approved these changes
고생하셧습니다..! 굉장합니다.

2024-02-12 14:06 UTC, hayoung78 approved these changes

2024-02-12 14:06 UTC, merged