PR/PD-41 router 초기 설정을 완료하였습니다.
PurpleDynamics/PEA_Project pull request #4
Opened 2024-01-22 16:22 UTC by hayoung78

## 🎯 작업 내용

<img height= "500" width= "300" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/c8ab0fd8-c563-4ccc-a7fc-81ac253923c4"/>
<img height= "500" width= "300" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/dd4522be-c2f8-48c3-bb9d-bb014e6a1661"/>

router 초기 설정 및 페이지 폴더 & 파일 생성을 완료하였습니다.
초기설정이므로 의견주시면 수정하겠습니다.

[feat: router 초기 설정을 완료하였습니다](https://github.com/PurpleDynamics/PEA_Project/commit/231657f081444840ed9dfe83a2d994709cd747b0)
- 이 commit에서는 router 초기설정 및 페이지 폴더와 파일을 생성했습니다.

[chore : import 파일이름 수정하였습니다](https://github.com/PurpleDynamics/PEA_Project/commit/ffdb658d427d334a2416dd16690bae7301938e06)
- 이 commit에서는 import 가 require 로 잘못 작성되어 수정하였습니다.

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] PR 제목 (컨벤션에 따랐는지) 확인 
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!! 

### 👍 문제가 없다고 생각된다면...
1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...
1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.
```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```
2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-01-22 16:28 UTC, KR-HeoJU approved these changes

2024-01-22 18:08 UTC, snkchan requested changes
review남겼습니다 확인해주세요~~

2024-01-22 18:08 UTC, snkchan commented on src/libs/react-router-dom/router.jsx
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- path: "/DeialProductPage", path: "/UserdProductPage",  오타 있어서 수정하셔야해요.

2024-01-22 18:08 UTC, snkchan commented on src/libs/react-router-dom/router.jsx
> +				path: "/UserdProductPage",
UsedProductPage에서는 어떤것을 다루는 페이지죠???? 잘모르겠어서 질문드립니다

2024-01-22 18:08 UTC, snkchan commented on src/libs/react-router-dom/router.jsx
> +				path: "/DeialProductPage",
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- path: "/DeialProductPage" 이부분은 추후에 url에 productId를 뿌려줄거기때문에 
path: "/DeialProductPage/:productId"이렇게 설정해주시는게 좋지 않을까요? 초기설정단계라 생략하신거라면 이대로도 좋을거 같습니다.

2024-01-23 02:38 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/UserdProductPage",
메인 페이지에서 더보기를 누르면 가지는 중고/나눔 페이지 입니다.
더 좋은 이름 있으면  말씀해주세요...

2024-01-23 02:40 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/DeialProductPage",
초기 설정이라 간단한 연결만 해놓은 상태입니다.
원래 생각은 페이지를 만들어 나가면서 수정하는것 이였는데
어떤 방식이 좋을까요..

2024-01-23 02:41 UTC, ijimlnosk approved these changes

2024-01-23 03:39 UTC, TransparentDeveloper requested changes
확인했습니다.!!

2024-01-23 03:39 UTC, TransparentDeveloper commented on src/layouts/layout.js
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `pages` 폴더 아래 파일처럼 `.jsx` 확장자로 변경해주세요. 
- RootLayout 은 `src>components` 폴더 아래서 관리하는게 어떨까요?

2024-01-23 03:39 UTC, TransparentDeveloper commented on src/libs/react-router-dom/router.jsx
> +import SignUpPage from "../../pages/sign/signup-page";
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- barrel-file 쓰기로 했던거 같은데, 'pages' 폴더에 `index.js` 두고 한번에 export 하는게 좋을 거 같습니다.

2024-01-23 03:39 UTC, TransparentDeveloper commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 주소창에 노출되는 정보는 kebab-case 로 적는게 좋지 않을까요?

2024-01-23 03:39 UTC, TransparentDeveloper commented on src/pages/main/main-page.jsx
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `pages` 폴더 아래에 바로 파일을 두지 않고, 각 파일별로 폴더가 한번 더 감싸져있네요?
- 특별한 이유가 없다면, 깊이가 늘어나지 않게 바로 파일을 두는 게 좋을 거 같습니다.

2024-01-23 03:39 UTC, TransparentDeveloper commented on src/pages/chat/chat-page.jsx
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 채팅은 별도의 페이지를 두지 않고,, 좌측 하단, 작은 컴포넌트 통해서 출력되도록 구현되는 걸로 디자인 팀한테 들었습니다.
- 채팅 관련 페이지를 만드는 건가요?

2024-01-23 03:39 UTC, TransparentDeveloper commented on src/pages/sign/signin-page.jsx
> +const SignInPage = () => {
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `SignInPage` 이면 파일 이름도 `sign-in-page`  여야 맞지 않나요? 
- `SignUpPage`도 마찬가지가지로, 컴포넌트 명 혹은 파일명 둘 중 하나는 변경해 주셨으면 좋겠습니다.

2024-01-23 03:42 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +import SignUpPage from "../../pages/sign/signup-page";
아 깜빡했습니다 
수정 하겠습니다

2024-01-23 03:43 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
확인 했습니다~ 
수정 하겠습니다

2024-01-23 03:44 UTC, ijimlnosk commented on src/pages/main/main-page.jsx
- 확인 했습니다

2024-01-23 03:48 UTC, ijimlnosk commented on src/pages/chat/chat-page.jsx
좌측 하단, 작은 컴포넌트를 통해서 출력이되는 채팅 기능이
페이지를 작게 만들어서 보여주는것이기 때문에 라우터 연결이 필요합니다.
추후 "/chat:roomName or roomNumber" 로 들어갈 예정입니다

2024-01-23 03:51 UTC, ijimlnosk commented on src/pages/sign/signin-page.jsx
> +const SignInPage = () => {
컨벤션에 파일이름은 케밥케이스 컴포넌트 이름은 파스칼케이스로 되어있어서 작성했습니다
어떠한 방식으로 갈지 다시 얘기를 해보는게 좋을 것 같습니다

2024-01-23 03:57 UTC, TransparentDeveloper commented on src/pages/sign/signin-page.jsx
> +const SignInPage = () => {
아아,, 그게 아니라,,, 파일 이름 케밥으로 잘 작성했고, 컴포넌트 이름도 파스칼로 잘 작성했는데, 공백에 대한 처리가 일관성이 없다는 의미 입니다. 

- `sign in` (공백구분x) 일때, kebab 이면 `sign-in` 이고, 파스칼이면 `SignIn` 입니다.
- `signin` (공백구분) 일때, kebab 이면 `signin` 이고, 파스칼이면 `Signin` 입니다.

근데 파일이름은 `signin`(공백구분 x) 으로 적고, 컴포넌트 이름은 `SignIn`(공백구분) 으로 작성되어 있습니다.

2024-01-23 04:02 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
확인했습니다

2024-01-23 04:04 UTC, ijimlnosk commented on src/layouts/layout.js
확인했습니다

2024-01-23 04:05 UTC, ijimlnosk commented on src/pages/sign/signin-page.jsx
> +const SignInPage = () => {
아 확인했습니다
맞게 수정하겠습니다

2024-01-23 04:10 UTC, TransparentDeveloper commented on src/pages/chat/chat-page.jsx
- 주소창 통해서 채팅방 id 저장하게 하는 건 좋은 방법인 것 같습니다. 그거까지 생각 못했네요.

- 하지만 주소창 바뀔 때 좌측 하단에 컴포넌트는 변경되겠지만, 나머지 여백 부분은 아무것도 안 나올 것 같습니다. 주소가 변경되면 뒤에 있는 페이지가 유지될까요? overlay 구현이 어려울 것 같아요.

- 그리고 궁금한 점이, 채팅 관련 컴포넌트를 여는 위치가 main-page 일 때, 주소창에 'http://pea.app/chat-page/chat~~' 이렇게 나오겠지만, my-page 에서 열면 'http://pea.app/my-page/chat-page/chat~~' 이렇게 나오나요?

2024-01-23 04:14 UTC, TransparentDeveloper commented on src/pages/chat/chat-page.jsx
채팅방 id를 저장하고, 되돌아가기 기능이 필요하다면 채팅관련 페이지를 별도로 두는게 좋을 것 같아요. 
모든 페이지에서 여닫기 + overlay 되도록 하려면 pages 에서 관리하지 않는 게 좋을 것 같습니다.

2024-01-23 04:30 UTC, TransparentDeveloper commented on src/libs/react-router-dom/router.jsx
> +				path: "/UserdProductPage",
일단 Userd 는 오타인 것 같습니다. 수정해야할 것 같습니다. 😁

2024-01-23 04:41 UTC, ijimlnosk commented on src/pages/chat/chat-page.jsx
따로 로직 보면서 설명 해드리겠습니다

2024-01-23 07:00 UTC, snkchan commented on src/libs/react-router-dom/router.jsx
> +				path: "/DeialProductPage",
> 초기 설정이라 간단한 연결만 해놓은 상태입니다. 원래 생각은 페이지를 만들어 나가면서 수정하는것 이였는데 어떤 방식이 좋을까요..
- 초기설정단계니깐 꼭 넣어야할 사항은 아닐거같아서 이대로도 괜찮을거 같습니다!

2024-01-23 07:04 UTC, snkchan commented on src/libs/react-router-dom/router.jsx
> +				path: "/UserdProductPage",
> 메인 페이지에서 더보기를 누르면 가지는 중고/나눔 페이지 입니다. 더 좋은 이름 있으면 말씀해주세요...

- 윤신님의견이었는데 FilterdMainPage 이런식이면 좋을거같다고 하시던데 Used는 의미가 좀애매한거같아서 우선 더생각해보고 밤에 오겠습니다

2024-01-23 08:11 UTC, jjjiyoung0130 reviewed
리뷰 남겼습니다. 확인해주세요.

2024-01-23 08:11 UTC, jjjiyoung0130 commented on src/libs/react-router-dom/router.jsx
> +				path: "/UserdProductPage",
메인페이지에서 이동하는 거라면 ProductList를 메인으로 두고 productList/sale, productList/free로 이동하는게 낫지 않을까요?

2024-01-23 08:11 UTC, jjjiyoung0130 commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [X] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - path에 꼭 Page가 들어가야할까요? url에 노출되는 부분이라 없는 편이 낫지 않을까 싶어 의견남깁니다.

2024-01-23 08:11 UTC, jjjiyoung0130 commented on src/libs/react-router-dom/router.jsx
> +				path: "/PostProductPage",
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [X] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - PostProductPage는 상품 등록 페이지인가요? 이름이 직관적이지 않아서 질문드립니다. 상품 등록이라면 Post 보다는 Register가 어떨까요?

2024-01-23 08:18 UTC, jjjiyoung0130 requested changes
코멘트에서 변경요청으로 수정

2024-01-23 08:30 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
오...둘 다 확인 했습니다 의견 나눠보고 적용하겠습니다

2024-01-23 08:30 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/PostProductPage",
확인했습니다 수정하겠습니다

2024-01-23 11:01 UTC, keeprok approved these changes
다른분들이 쓴 리뷰를 다읽으면서 오히려 배우고 있네여 리뷰달린 부분을 제외하고 저는 지적할게 따로보이진않아서 다음부터는 더일찍 리뷰하겠습니다 리뷰된곳만 되면 될거같아여

2024-01-23 11:15 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
main page를 productList 로 바꾸는 건 좋다고 생각합니다만
중고 / 나눔은 하나의 페이지에서 동작하지 않나요?

2024-01-23 11:21 UTC, jjjiyoung0130 commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
상태로 관리할거니까 productList까지만 있으면 되겠네요.
다른 팀꺼 참고하면서 작업하다보니 별개의 페이지로 생각했네요.

2024-01-23 11:23 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
그럼 productList로 변경하겠습니다

2024-01-23 11:45 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +import SignUpPage from "../../pages/sign/signup-page";
수정했습니다 확인 부탁드립니다
ad889bc17e2a45ce1b85b41bb33cabd4c12026ec

2024-01-23 11:46 UTC, ijimlnosk commented on src/pages/chat/chat-page.jsx
수정 했습니다.
확인 부탁드립니다.
68c696dab463734cfa9bd521e88b6226eb0e9ebb

2024-01-23 11:48 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
수정했습니다.
확인 부탁드립니다.
0496a67185ac3225026b1b3d67041829f045ee56

2024-01-23 11:48 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/PostProductPage",
수정했습니다.
확인 부탁드립니다.
0496a67185ac3225026b1b3d67041829f045ee56

2024-01-23 11:50 UTC, ijimlnosk commented on src/pages/main/main-page.jsx
![스크린샷 2024-01-23 오후 8 49 29](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/48b61566-3eb2-4c96-94c8-8f07f6726bfe)
수정했습니다.

2024-01-23 11:53 UTC, ijimlnosk commented on src/layouts/layout.js
수정했습니다. 
1046d428d0af78e3c51656e6b8826796ccb42198

2024-01-23 11:56 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +				path: "/SignInPage",
수정했습니다.
<img height="500" width="300" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/98bd7d6c-55e2-4205-b97e-ee0b4c685aef" />

2024-01-23 12:41 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +import SignUpPage from "../../pages/sign/signup-page";
2차 수정 완료했습니다
2bfd8db65ffe6de668f1fed68b0967457e3692fa

2024-01-23 13:08 UTC, ijimlnosk commented on src/libs/react-router-dom/router.jsx
> +import SignUpPage from "../../pages/sign/signup-page";
3차 수정 완료했습니다
b0e5d8740dc96de93979f6dc7600ab9eb86d13bf

2024-01-23 13:31 UTC, snkchan approved these changes
이제된것 같습니다. 고생하셧습니다~~~

2024-01-23 16:06 UTC, closed without merging