PR/PD-46: feat/login 로직 기능 구현
PurpleDynamics/PEA_Project pull request #40
Opened 2024-02-07 12:03 UTC by hayoung78

## 🎯 작업 내용

[feat : 로컬/세션스토리지 토큰 관리 파일 생성 (auth)](https://github.com/PurpleDynamics/PEA_Project/commit/c481d3e764d6aaa1d46bf6ad759895518efecac8)
 - 더 쉬운 토큰 관리를 위해 ```auth.js``` 파일을 생성하였습니다.
 - import 하여 사용 가능합니다.
 
 ``` 
 export const getLocalToken = () => {
	return localStorage.getItem("token");
};

export const setLocalToken = (token) => {
	return localStorage.setItem("token", token);
};

export const setSessionToken = (token) => {
	return sessionStorage.setItem("token", token);
};
export const getSessionToken = () => {
	return sessionStorage.getItem("token");
};
```

[feat : instance 파일 생성](https://github.com/PurpleDynamics/PEA_Project/commit/9bb79d654d3cedf84bc733fd36a6c5228cacc3e7)
- 임시 BaseUrl을 ```instance.js``` 로 파일 생성했습니다.

[feat: 로그인 로직 기능 구현](https://github.com/PurpleDynamics/PEA_Project/commit/fab78f87b812df706256a6a25281b4c3b828c38c)
- signin-page 로그인 기능 구현하였습니다.
- 자동로그인 체크 후 로그인 시, 토큰은 ```localStorage``` 에 저장되고, 미체크 후 로그인 시 , ```sessionStorage```에 저장됩니다. (웹페이지 종료 후에도 기능 확인 완료했습니다)
- 기존 로그인 버튼 활성화 기능 구현시, dirtyFields 속성을 사용했는데, ```disabled={!isVaild}``` 속성으로도 구현이 가능하여 수정하였습니다.

- 해당 기능이 제대로 작동하기위해 ```admin-router.jsx```수정하였습니다.

[refactor : admin route 수정 및 구조 변경](https://github.com/PurpleDynamics/PEA_Project/commit/839a60cb3712aed0d85de86643a104979ecdbe31)
- sessionStorage token과 localStorage token 을 따로 나누어 코드 작성했습니다.
- ```auth.js```를 반영하여 수정했습니다.
- 로컬과 세션 스토리지에 토큰이 없으면 ```signin-page``` 로 넘어갑니다. (지난번 기능과 동일)
```
const AdminRoute = () => {
	const localToken = getLocalToken();
	const sessionToken = getSessionToken();
	const navigate = useNavigate();
	useEffect(() => {
		if (!localToken && !sessionToken) {
			navigate("/signin");
		}
	}, [localToken, sessionToken, navigate]);

	return <RootLayout />;
};
export default AdminRoute;
```
### 아래 gif 보실때 token 저장소를 봐주십쇼~~ (화질 구려서 ㅈㅅㅜㅜ)
![자동로그인 (1)](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/94f541dc-e820-4264-ad93-1244d1a833a7)

![그냥 로그인 (1)](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/9d133ceb-81b2-488a-9d16-97d99846f10d)

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-07 12:13 UTC, ijimlnosk commented on src/utils/auth.js
> +};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- localStorage 와 sessionStorage의 key값인 토큰이 자세하게 구분되면 더 좋을 것 같습니다.

2024-02-07 12:53 UTC, TransparentDeveloper requested changes
고생하셨습니다.!!

2024-02-07 12:53 UTC, TransparentDeveloper commented on src/utils/auth.js
> +};
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- JSDocs 작성하는 의도를 생각해봐주셨으면 좋겠습니다. 
- 각 함수에 마우스를 올려보았을 때, 어떻게 출력되는지 확인해 봐주시겠어요??

2024-02-07 12:53 UTC, TransparentDeveloper commented on src/utils/auth.js
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `auth` 라는 파일 이름은 적절치 못한 것 같습니다.
- 로컬 스토리지, 세션 스토리지 에 접근하는 함수가 주로 있는 것 같습니다.
- 로컬 스토리지, 세션 스토리지 는 인증 토큰 관리만을 위해 있는 게 아닙니다. 
- 'storage-manager' 같은 게 어떨까요?

2024-02-07 12:53 UTC, TransparentDeveloper commented on src/utils/instance.js
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 여기서 작성한 인스턴스 는 사용자 인증 서버로의 요청에 필요한 인스턴스 입니다.
- 그런데, `instance.js` 라고 파일명을 사용하시면 상품 데이터 호출할 떄, 해당 instance 를 잘못 import 할 수 있지 않을까요??
- 제가 해당 인스턴스 관련 폴더 구조를 만들고 있으니, 지금은 인스턴스 말고, axios.get() 으로 직접 작성 부탁드립니다. 🙏

2024-02-07 16:34 UTC, hayoung78 commented on src/utils/auth.js
[fix: auth파일 이름 수정 및 docs 내용 수정, token key값 수정](https://github.com/PurpleDynamics/PEA_Project/pull/40/commits/3ae23b77a693048df079dcdac11f4959d67d427d)

```auth``` -> ```storage-manager``` 로 파일 이름 바꿨습니다

2024-02-07 16:39 UTC, hayoung78 commented on src/utils/instance.js
[fix : instance 파일 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/40/commits/0ba4176feabf086ed5d679e075baa3d199ddc1ce)

2024-02-07 16:41 UTC, hayoung78 commented on src/utils/auth.js
[fix: auth파일 이름 수정 및 docs 내용 수정, token key값 수정](https://github.com/PurpleDynamics/PEA_Project/pull/40/commits/3ae23b77a693048df079dcdac11f4959d67d427d)

docs.... 수정... 했습니다...... 이렇게 쓰는거 아니면...... 의견 주세요.. 닥스가 제일 어려움ㅠ

2024-02-07 16:41 UTC, hayoung78 commented on src/utils/auth.js
> +};
[fix: auth파일 이름 수정 및 docs 내용 수정, token key값 수정](https://github.com/PurpleDynamics/PEA_Project/pull/40/commits/3ae23b77a693048df079dcdac11f4959d67d427d)

docs.... 수정... 했습니다...... 이렇게 쓰는거 아니면...... 의견 주세요.. 닥스가 제일 어려움ㅠ

2024-02-07 16:43 UTC, hayoung78 commented on src/utils/auth.js
> +};
localStorage => accessToken으로 , 
sessionStorage => refreshToken으로 키값 변경했습니다

2024-02-07 16:44 UTC, ijimlnosk approved these changes
합격 드리겠습니다!

2024-02-08 13:29 UTC, keeprok approved these changes
확인 했습니다

2024-02-08 13:45 UTC, snkchan requested changes
굉장하네요...따봉드리고 갑니다.👍

2024-02-08 13:45 UTC, snkchan commented on src/pages/signin-page.jsx
> + * - password: qwer1234
- 이부분은 추후에 작업진행할때 모두 같이 사용하게 될 임시 아이디 비번이라면 pr작성해주실때
-ex) 참고해주세요! 라는 제목으로 밑에 작성해주시거나 notion에 따로 작성해주시고 모두같이 알 수 있게 해주셧으면합니다.

2024-02-08 13:45 UTC, snkchan commented on src/pages/signin-page.jsx
> +				navigate("/");
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 간단한 로직이지만 중요한 내용이니 간단하게 주석을 달아주는건 어떨까요?

2024-02-08 13:45 UTC, snkchan commented on src/pages/signin-page.jsx
> +						onChange={(e) => setAutoLogin(e.target.checked)}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- auto,setAuto 라는 상태는 현재 로그인 로직을 위한 변수로만 사용되는 것 같은데 화면에 render하기 위한 상태관리가 아니라면 굳이 상태로 관리할 필요가 없어보입니다. 차라리 useRef를 사용하시는게 좋아보여요.

2024-02-08 15:12 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +						onChange={(e) => setAutoLogin(e.target.checked)}
이 부분은 딱히 크게 문제가 되지 않을것같아 그냥 두었습니다.

2024-02-08 15:13 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +						onChange={(e) => setAutoLogin(e.target.checked)}
지만... 한번 확인해볼게요^^

2024-02-11 09:49 UTC, hayoung78 commented on src/pages/signin-page.jsx
> + * - password: qwer1234
[fix : docs 'ex)' 수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/40/commits/ecac20a96e410c528f43e8434735f8b0a937b6e2)

원하시는게 이게 맞는지 확인부탁드립니다~ 노션에도 남겼습니다
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/6b7dff1f-1d63-42eb-bae4-4f6a444c3da1)

2024-02-11 09:51 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +						onChange={(e) => setAutoLogin(e.target.checked)}
[fix : autoLogin Ref로 관리 수정했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/40/commits/a0e0c6fa3a34c244de841a6aa960b525001f8807)

ref로 수정하고 로그인에 문제 없는거까지 확인했습니다.
```
const SigninPage = () => {
	const navigate = useNavigate();
	const onMoveSignupPage = () => {
		navigate("/signup");
	};
	const autoLoginRef = useRef(false);
	const {
		register,
		handleSubmit,
		formState: { errors, isValid }, // isVaild: 현재 폼의 유효성 여부
	} = useForm({ mode: "onChange" });
	const onSubmit = async (data) => {
		const Data = {
			email: data.email,
			password: data.password,
		};
		try {
			const response = await axios.post(`${BASE_URL}/signin`, Data);
			const token = response.data.token;

			// 로그인이 성공적이고, 자동로그인 체크시 localStorage에 , 미체크시 sessionStorage에 토큰이 저장
			if (response.status === 200) {
				if (autoLoginRef.current) {
					setLocalToken("accessToken", token);
				} else {
					setSessionToken("refreshToken", token);
				}
				navigate("/");
			}
		} catch (error) {
			alert("로그인 실패: 이메일 또는 비밀번호를 확인해주세요.");
		}
	};
```

2024-02-11 13:14 UTC, jjjiyoung0130 approved these changes

2024-02-11 13:14 UTC, jjjiyoung0130 commented on src/utils/storage-manager.js
> + * @retruns {string | null} 저장된 token값 또는 token이 없을 경우 null
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 사소한 거지만 returns에 오타있습니다 :)

2024-02-11 13:24 UTC, hayoung78 commented on src/pages/signin-page.jsx
> + * - password: qwer1234
아? 당사자 나오시죠

2024-02-11 13:25 UTC, hayoung78 commented on src/utils/storage-manager.js
> + * @retruns {string | null} 저장된 token값 또는 token이 없을 경우 null
허허이....어메이징하네요

2024-02-11 13:27 UTC, snkchan approved these changes
고생하셧습니다..! 굉장하네요

2024-02-12 10:08 UTC, TransparentDeveloper approved these changes
몇 가지만 수정해주시고 바로 merge 해주세요~

2024-02-12 10:08 UTC, TransparentDeveloper commented on src/utils/storage-manager.js
> +};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 함수 넘길 파라미터는 객체 형태로 전달해야 합니다.

2024-02-12 10:08 UTC, TransparentDeveloper commented on src/utils/storage-manager.js
> + * @parameter token : sessionStorage에 저장될 토큰
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 타입이 없어요.

2024-02-12 10:08 UTC, TransparentDeveloper commented on src/pages/signin-page.jsx
> +		};
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 그냥 'Data' 는 너무 추상적인 이름같아요.
- 추가적으로 변수명은 camelCase 로 작성해야합니다.

2024-02-13 14:13 UTC, hayoung78 commented on src/pages/signin-page.jsx
> +		};
authData로 수정했습니다

2024-02-13 14:13 UTC, hayoung78 commented on src/utils/storage-manager.js
> +};
```
if (response.status === 200) {
				if (autoLoginRef.current) {
					setLocalToken({ token: token });
				} else {
					setSessionToken({ token: token });
				}
				navigate("/");
			}
		} catch {
			handleOpenModal();
		}
```
수정했습니다

2024-02-13 14:16 UTC, merged