PR/PD-56: chatting overlay common 생성 완료했습니다
PurpleDynamics/PEA_Project pull request #42
Opened 2024-02-12 09:24 UTC by ijimlnosk

## 🎯 작업 내용

- 오류발생으로 인해 pr을 새로 보냅니다.

- [fix: search-bar.jsx 수정](https://github.com/PurpleDynamics/PEA_Project/commit/d6344bf0c1dc4001f03cb1b7a7df8cfb310587e8)
- search bar 에 width, height, paddingLeft, placeholder를 입력 받을 수 있습니다.

- [fix: header.jsx 수정 완료](https://github.com/PurpleDynamics/PEA_Project/commit/36de63447bc3ff98d5b3e8a958bd3393613d195e)
- header.jsx 의 search-.bar의 위치를 수정했습니다.

- [design: chatting-overlay-common 생성](https://github.com/PurpleDynamics/PEA_Project/commit/fc7c8fd38a8f7180852b6c5565b538c31fb46906)
- 기존 오류 사항 수정 완료
- chatting안에 폴더 구조 재 설정
- index.js 재설정
- chat-room-list -> chatting-overlay 변경
- chat-room -> chat-room-list 변경

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-12 10:25 UTC, TransparentDeveloper requested changes
고생하셨습니다.!!

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chatting-overlay.jsx
> +`;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 폴더랑 파일명으로도 어떤 컴포넌트인지 알 수 있으니까 반복되는 "-Chat" 접두어는 빼도 되지 않을까요?

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chatting-overlay.jsx
> +	}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 더 줄여서 작성할 수 있어요.

```js
cursor: pointer;
```

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/commons/search-bar.jsx
> +					height={height}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 스타일 컴포넌트에 전달하는 props 에 대한 컨벤션 확인바랍니다.

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/commons/search-bar.jsx
> +	paddingLeft,
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 기본값이 설

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/commons/search-bar.jsx
> +	paddingLeft,
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 기본값이 설정되어 있지 않은데, 값을 주지 않을 경우, 오류가 발생하나요? 아니면 왼쪽 패딩이 없는 채로 ui가 그려지나요??

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/commons/search-bar.jsx
> +	cursor: pointer;
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 'z-index' 속성이 왜 사용되나요?? 
- 이 속성이 없어도 똑같이 출력되지 않을까요?

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat-room-list.jsx
> + * @parameter data: Array - 임시로 방정보를 받오는 파라미터 입니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 어떤 타입의 데이터를 담은 배열인지도 알 수 있으면 좋겠습니다.
- 예를 들어, 채팅방의 id 를 담은 배열이라면, `Array<number>` 이렇게 적는게 어떨까요?

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat-room-list.jsx
> + * @parameter data: Array - 임시로 방정보를 받오는 파라미터 입니다.
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `data` 라는 이름은 굉장히 포괄적이고 추상적인 것 같습니다.

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat-room-list.jsx
> +			isFiltered: false,
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- overlay 컴포넌트 위에 overlay 해야할 컴포넌트를 추가적으로 호출해야 할 경우, `zIndex` 값을 설정해줘야 합니다.

2024-02-12 10:25 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat-room-list.jsx
> +			{/* <Chat /> */}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 불필요한 주석인 것 같습니다.

2024-02-12 10:29 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> +			isFiltered: false,
zIndex 깂을 설정해주지 않아도 정상적으로 작동하기에 굳이 설정해주지 않았는데 설정해보겠습니다

2024-02-12 10:29 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> +			{/* <Chat /> */}
아 삭제하는걸 깜박했네요

2024-02-12 10:52 UTC, ijimlnosk commented on src/components/commons/search-bar.jsx
> +					height={height}
- [fix: 스타일 props name 수정](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/04be5ddc70a23119b0dbd2589601fd7b63aca108)
- 변경하였습니다.

2024-02-12 10:55 UTC, ijimlnosk commented on src/components/commons/search-bar.jsx
> +	paddingLeft,
왼쪽 패딩이 없는 상태로 그려집니다

2024-02-12 13:25 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> +			{/* <Chat /> */}
- [fix: 불필요한 주석 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/fa0d2e2d5dfdc9f685aa8b712742f8a6a12756e9)
- 삭제하였습니다.

2024-02-12 13:36 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> + * @parameter data: Array - 임시로 방정보를 받오는 파라미터 입니다.
- [fix: data를 확실하게 표기 했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/16ea084de043320568e597b59e0bcbca2d893dc8)
- 기존 user -> userData
- 기존 data -> productData
- 기존 data -> roomData
- 로 변경했습니다.

2024-02-12 13:41 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> + * @parameter data: Array - 임시로 방정보를 받오는 파라미터 입니다.
- [fix: js doc를 수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/3a109f2f5c905ee6d3ff00c5fe4cdbcfd199d1f3)
- 객체를 담고있으므로 Array<object>로 작성했습니다

2024-02-12 13:43 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> +			isFiltered: false,
- [fix: chat-room-list에 zIndex 추가했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/ea77e5e14173302c46901e5835ae931da313ed37)
- 작성했습니다.

2024-02-12 13:43 UTC, ijimlnosk commented on src/components/commons/search-bar.jsx
> +	cursor: pointer;
- 삭제 완료 했습니다

2024-02-12 14:03 UTC, TransparentDeveloper requested changes

2024-02-12 14:03 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat.jsx
> +			<S.ChatView>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `ChatView` 는 역시 수정이 되었으면 좋겠습니다;; 바로 이해되지가 않아요.
- `MessagesWrapper` 나 `MessagesList` 는 어떤가요?

2024-02-13 02:32 UTC, ijimlnosk commented on src/components/commons/search-bar.jsx
> +	$paddingLeft,
- [fix: styled 컨벤션에 맞게 수정](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/41deb0799cfa39564212d393aa6a2192873704b6)
- 수정했습니다

2024-02-13 02:35 UTC, ijimlnosk commented on src/components/overlay/chatting/chat.jsx
> +`;
- [fix: 접두어 제거](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/4ec85a8c1bbe8f385e66f6f1f5c2313f73ae6ce3)
- 제거 했습니다

2024-02-13 02:37 UTC, ijimlnosk commented on src/components/overlay/chatting/chat.jsx
> +			<S.ChatView>
제 생각은 MessagesWrapper 나 MessageList 보다는 채팅을 보여주는 창 이기 때문에 ChatView가 의미적으로 맞다고 생각됩니다.

2024-02-14 02:18 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat-room-list.jsx
> + * @parameter data: Array - 임시로 방정보를 받오는 파라미터 입니다.
- [fix: js doc를 수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/3a109f2f5c905ee6d3ff00c5fe4cdbcfd199d1f3)
  - 음.. 아니요. 여전히 `roomData` 직접 설계한 진솔님 이 외 누구도 사용불가합니다.
  - object 에 key-value 에 대한 정보가 명시되어야 합니다.

2024-02-14 06:03 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> + * @parameter data: Array - 임시로 방정보를 받오는 파라미터 입니다.
- [fix: js dox 수정](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/c4304f03cb5707407b34983cd422cca91b7a4012)
- 재 수정했습니다.

2024-02-14 07:12 UTC, hayoung78 approved these changes
확인했습니다

2024-02-14 07:31 UTC, keeprok reviewed
체크했습니다

2024-02-14 07:31 UTC, keeprok commented on src/pages/product-list-page.jsx
>  		<>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
빈공간으로 하신이유가있을까요???

2024-02-14 07:31 UTC, TransparentDeveloper requested changes
확인했습니다.

2024-02-14 07:31 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat-room-list.jsx
> +`;
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `margin: 0` 은 뭔가요??

2024-02-14 07:31 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat.jsx
> +	align-items: center;
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `justify-content: left` 이런 값은 없는 걸로 압니다.

2024-02-14 07:31 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat.jsx
> +	font-size: ${FONT_SIZE.sm};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 토큰에 등록된 error 색상을 활용해 주시면 좋을 것 같습니다.

2024-02-14 07:31 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat.jsx
> +`;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이건 컨벤션 위반으로 보는 게 맞지 않나요?

2024-02-14 07:31 UTC, TransparentDeveloper commented on src/components/commons/search-bar.jsx
> +	border: none;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- border 는 기본이 없지 않나요??
- `background: none` 필요한 속성인가요??

2024-02-14 07:39 UTC, snkchan approved these changes
윤신님 요구사항 수정완료하시면 더수정할게 없을것 같아요!! 고생하셧습니다.👍

2024-02-14 07:59 UTC, ijimlnosk commented on src/components/overlay/chatting/chat.jsx
> +	align-items: center;
- [fix: style 삭제 및 수정](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/2d59b2f9ef6e50a545c67d2c6f71827c33ab3bed)
- 수정했습니다

2024-02-14 07:59 UTC, ijimlnosk commented on src/components/overlay/chatting/chat.jsx
> +	font-size: ${FONT_SIZE.sm};
- [fix: style 삭제 및 수정](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/2d59b2f9ef6e50a545c67d2c6f71827c33ab3bed)
- 수정했습니다

2024-02-14 08:00 UTC, ijimlnosk commented on src/components/overlay/chatting/chat.jsx
> +`;
- [fix: style 삭제 및 수정](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/2d59b2f9ef6e50a545c67d2c6f71827c33ab3bed)
- 수정했습니다

2024-02-14 08:00 UTC, ijimlnosk commented on src/components/commons/search-bar.jsx
> +	border: none;
- [fix: style 삭제 및 수정](https://github.com/PurpleDynamics/PEA_Project/pull/42/commits/2d59b2f9ef6e50a545c67d2c6f71827c33ab3bed)
- 수정했습니다

2024-02-14 08:19 UTC, keeprok approved these changes

2024-02-14 08:38 UTC, TransparentDeveloper approved these changes

2024-02-14 10:38 UTC, closed without merging