PR/PD-44: skeleton ui 생성 완료
PurpleDynamics/PEA_Project pull request #45
Opened 2024-02-12 17:27 UTC by ijimlnosk

## 🎯 작업 내용

- [design: skeleton ui를 만들었습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/09259770d73938494f6c3a30d0f9d761ee4cb49b)
- skeleton base 생성했습니다.
- skeleton product card를 생성했습니다.

- skeleton product card를 사용한 예시
- ![스크린샷 2024-02-13 오전 2 03 48](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/35901f10-e433-42d0-b395-41c70878c660)

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-13 13:31 UTC, keeprok reviewed
확인했습니다

2024-02-13 13:31 UTC, keeprok commented on src/components/skeleton/skeleton-product-card.jsx
> +			<SkeletonBase $width="21rem" $height="3rem" />
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
사이즈가 동일시 되는게 많은거같은데styled로 묶어서 하는게 깔끔해 보이지 않을까요??

2024-02-13 13:31 UTC, snkchan requested changes
확인했습니다.! 리뷰확인해주세요~~

2024-02-13 13:31 UTC, snkchan commented on src/components/skeleton/skeleton-base.jsx
> + * @parameter $height : string - 높이를 입력 받습니다.
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
저희 porps에는 $를 안붙히고 사용했던거 같습니다.

2024-02-13 13:31 UTC, snkchan commented on src/components/skeleton/skeleton-base.jsx
> +			borderRadius={$borderRadius}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
props명에 $를 붙혀주시고 실제로 전달받는값은 $없이 사용해주셔야 개발자도구에서 오류가 안뜹니다.

2024-02-13 13:31 UTC, snkchan commented on src/components/skeleton/skeleton-base.jsx
> +	height: ${({ height }) => height};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
여기도 같이수정해주세요~

2024-02-13 13:31 UTC, snkchan commented on src/components/skeleton/skeleton-product-card.jsx
> +import SkeletonBase from "./skeleton-base";
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
import경로가 잘못된거같아 보니깐 index.js가 없네요 barrel file생성해주세요~

2024-02-13 13:42 UTC, ijimlnosk commented on src/components/skeleton/skeleton-base.jsx
> +			borderRadius={$borderRadius}
- [fix: $ 컨벤션 수정](https://github.com/PurpleDynamics/PEA_Project/pull/45/commits/476d6140743f6985daacd417e222317bf2b49f03)
- 수정했습니다

2024-02-13 13:42 UTC, ijimlnosk commented on src/components/skeleton/skeleton-base.jsx
> +	height: ${({ height }) => height};
- [fix: $ 컨벤션 수정](https://github.com/PurpleDynamics/PEA_Project/pull/45/commits/476d6140743f6985daacd417e222317bf2b49f03)
- 수정했습니다

2024-02-13 13:43 UTC, ijimlnosk commented on src/components/skeleton/skeleton-product-card.jsx
> +import SkeletonBase from "./skeleton-base";
- [fix: barrel file 경로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/45/commits/2ee1b84d7013621c7228cdfdc2ca05053b664e1f)
- 수정했습니다

2024-02-13 13:46 UTC, ijimlnosk commented on src/components/skeleton/skeleton-product-card.jsx
> +			<SkeletonBase $width="21rem" $height="3rem" />
각각의 컴포넌트를 불러와서 입력해주는 거라 스타일로 묶기는 어려울것 같습니다

2024-02-13 14:37 UTC, keeprok approved these changes

2024-02-13 14:37 UTC, keeprok commented on src/components/skeleton/skeleton-product-card.jsx
> +			<SkeletonBase $width="21rem" $height="3rem" />
아 넵!!

2024-02-13 16:52 UTC, jjjiyoung0130 approved these changes
채윤님이 언급한 컨벤션 외에 코드에서 수정할 부분은 보이지 않네요.
수고하셨습니다.

2024-02-13 20:06 UTC, TransparentDeveloper requested changes
고생하셨습니다.!!

2024-02-13 20:06 UTC, TransparentDeveloper commented on src/components/skeleton/skeleton-base.jsx
> + * - 이런식으로 사용하시면 됩니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `@example` 로 작성바랍니다..

2024-02-14 07:01 UTC, snkchan approved these changes
잘사용하겠습니다...!!!

2024-02-14 07:03 UTC, hayoung78 approved these changes
확인했습니다

2024-02-14 07:04 UTC, ijimlnosk commented on src/components/skeleton/skeleton-base.jsx
> + * - 이런식으로 사용하시면 됩니다.
- [fix: js doc 수정완료](https://github.com/PurpleDynamics/PEA_Project/pull/45/commits/e4ea5ba51011ee60f34b5474b21c5d9ece7b69ad)
- 수정했습니다

2024-02-14 08:40 UTC, keeprok approved these changes

2024-02-14 08:50 UTC, TransparentDeveloper requested changes
추가 리뷰입니다.

2024-02-14 08:50 UTC, TransparentDeveloper commented on src/components/skeleton/skeleton-base.jsx
> + * - skeleton ui component 입니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 설명이 한 줄일 경우 `@description` 옆에 붙여 작성해야합니다..

2024-02-14 08:50 UTC, TransparentDeveloper commented on src/components/skeleton/skeleton-base.jsx
> + */
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- jsDocs 올리기 전에, 작성한 문서가 어떻게 보이는지 확인 부탁드립니다.
- `-` 없이 작성해보시겠어요?

2024-02-14 14:56 UTC, ijimlnosk commented on src/components/skeleton/skeleton-base.jsx
> + */
- [design: chatting-overlay-common 재 커밋](https://github.com/PurpleDynamics/PEA_Project/pull/45/commits/31dcb7dea6cbd414df42973c62c5a3ebcad06068)
- 변경 했습니다.

2024-02-14 15:01 UTC, ijimlnosk commented on src/components/skeleton/skeleton-base.jsx
> + */
-수정했습니다;;
push 과정에서 엉켜서 커밋이 많습니다.
<img width="564" alt="스크린샷 2024-02-14 오후 11 59 32" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/eadb6d00-5f3d-4020-82dd-372237fb897f">

2024-02-15 05:25 UTC, TransparentDeveloper approved these changes

2024-02-15 06:27 UTC, merged