PR/PD-70: 상품등록페이지 퍼블리싱 완료했습니다.
PurpleDynamics/PEA_Project pull request #46
Opened 2024-02-12 19:00 UTC by TransparentDeveloper

## 🎯 작업 내용

- [design: 스크롤바 스타일링](https://github.com/PurpleDynamics/PEA_Project/commit/be3dd61138dbec834ffe00d0a4a860ca983970d6)
  - 스크롤바 배경색을 없애고, 얇게 변형했습니다. 
  - 모든 컴포넌트에 적용됩니다.
  
- [refactor: 폰트 크기 속성 추가](https://github.com/PurpleDynamics/PEA_Project/commit/de58b559f665a6c3e944a99f98b00a1756977c53)
  - `HighlightedText` 에 폰트 크기도 외부에서 지정할 수 있도록 수정했습니다.

- [design: 상품 등록 페이지 퍼블리싱](https://github.com/PurpleDynamics/PEA_Project/commit/26ef53152ba5353908399a9ca7bf9487b3a767d9)
  - ![register-product](https://github.com/PurpleDynamics/PEA_Project/assets/50646145/67f7a2c4-817c-4f4c-a590-8487555c5615)

<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] PR 제목 (컨벤션에 따랐는지) 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-13 02:24 UTC, ijimlnosk reviewed
확인했습니다.
궁금한 점이 있습니다.
각 구역마다 파일을 나눈거 같은데 혹시 이렇게 한 특별한 이유가 있는지 궁금합니다

2024-02-13 02:24 UTC, ijimlnosk commented on src/components/register-product/page-notice.jsx
> +				</HighlightedText>{" "}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- {" "} 는 없어도되지 않을까요?

2024-02-13 02:24 UTC, ijimlnosk commented on src/components/register-product/section-heading-texts.jsx
> +export default SectionHeadingTexts;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- js doc에 parameter가 빠진 것 같습니다.

2024-02-13 02:40 UTC, ijimlnosk commented
상품 등록 페이지를 들어가 보니 옆에 최근 본 상품란이 떠 있던데
상품 등록 페이지에서 최근 본 상품을 보여줄 필요가 있을까요??
전체 페이지에서 보여주게 끔 만들어 진 것은 알고있습니다.
없어도 되지 않을까 하는 질문 이에요

2024-02-13 08:43 UTC, jjjiyoung0130 requested changes
일단 jsDoc부터 parameter나 description 추가해주십셔.
(코드.. 뭘 잡아내야하지...)

2024-02-13 08:43 UTC, jjjiyoung0130 commented on src/components/register-product/categories-selector.jsx
> + * - 카테고리르 추가할 수 있도록 출력되는 카테고리 이름을 담은 배열을 상태로 관리
오타있습니다.

2024-02-13 14:10 UTC, TransparentDeveloper commented on src/components/register-product/location-picker.jsx
> +		<div>
- <div> 태그 없으면 외부 스타일 컴포넌트의 속성 중, grid 의 영향을 이상하게 적용 받더라구요..
- <div> </div> 로 묶어야 하나의 컴포넌트로 인식이 됩니다.

2024-02-13 14:26 UTC, snkchan requested changes
리뷰 수정했습니다 확인해주세요~`

2024-02-13 14:26 UTC, snkchan commented on src/pages/register-product-page.jsx
> +				<SectionHeadingTexts titleText="상품명" />
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
현재페이지 컴포넌트에서 계속해서 이부분이 중복되고 titleText만 바뀌는 구조인데 이부분을 하나의 컴포넌트로 합친다면 register-product-page의 구조가 한눈에 들어오지 않을까요?

2024-02-13 19:04 UTC, TransparentDeveloper commented on src/pages/register-product-page.jsx
> +	background-color: ${({ $bgColor = COLOR.COMMON[0] }) => $bgColor};
- 피그마에서 가장 처음 (최상단) 등장한 Divider 의 색상이 검은색이었기 때문에, 해당 컴포넌트를 처음 작성할 때 COLOR.COMMON[900]을 기본값으로 설계했습니다.
- 맞네요.. 자주 사용하는 색상을 기본값으로 설정하는 좋을 거 같습니다. 👍

2024-02-13 19:08 UTC, TransparentDeveloper commented on src/components/register-product/categories-selector.jsx
> + * - 카테고리르 추가할 수 있도록 출력되는 카테고리 이름을 담은 배열을 상태로 관리
- [chore: 오타 수정](https://github.com/PurpleDynamics/PEA_Project/pull/46/commits/586273f3d2a46c57bd91217b6ec83940e7aa4084)
  - 오타 수정했습니다.

2024-02-13 19:09 UTC, TransparentDeveloper commented on src/pages/register-product-page.jsx
> +				<SectionHeadingTexts titleText="상품명" />
- [refactor: 반복 중첩되는 컴포넌트 병합](https://github.com/PurpleDynamics/PEA_Project/pull/46/commits/7169970af48064c57480d0f09c707d1a098c7518)
  - 넵 수정완료했습니다.!~

2024-02-13 19:09 UTC, TransparentDeveloper commented on src/pages/register-product-page.jsx
- [chore: jsDocs description 작성](https://github.com/PurpleDynamics/PEA_Project/pull/46/commits/cb3941c758d1e38543269c4ea1a57cad9676b4e1)
  - 완료했습니다.!

2024-02-13 20:10 UTC, TransparentDeveloper commented on src/components/register-product/section-heading-texts.jsx
> +export default SectionHeadingTexts;
- [refactor: 반복 중첩되는 컴포넌트 병합](https://github.com/PurpleDynamics/PEA_Project/pull/46/commits/7169970af48064c57480d0f09c707d1a098c7518)
  - 컴포넌트 병합하면서 작성했습니다.!

2024-02-14 02:41 UTC, ijimlnosk approved these changes

2024-02-14 02:41 UTC, keeprok approved these changes
확인했습니다

2024-02-14 02:49 UTC, jjjiyoung0130 approved these changes

2024-02-14 02:50 UTC, snkchan approved these changes
수고하셧습니다.1!!!!

2024-02-14 02:53 UTC, merged