Feat/sign up
PurpleDynamics/PEA_Project pull request #53
Opened 2024-02-14 15:47 UTC by hayoung78

## 🎯 작업 내용

[feat: checkDuplication 컴포넌트 생성](https://github.com/PurpleDynamics/PEA_Project/commit/899d3142a6de53e52643c971bde45486a358aba9)
- 이메일과 닉네임 중복시 확인할수있는 CheckDuplication 컴포넌트 생성했습니다.
- 파일 위치: ```components ``` -> ```commons``` 에 생성
- 사용하시려면, import 하시고 아래와 같이 사용하시면 됩니다. (아래 예시)
 ```
//이메일 중복 확인함수
   const onEmailDup = async () => {
      await CheckDuplication(
         "email",
         emailValue,
         isEmailAvailable,
         handleOpenModal,
         errors
      );
   };
//닉네임 중복 확인함수
   const onNicknameDup = async () => {
      await CheckDuplication(
         "nickname",
         nicknameValue,
         isNicknameAvailable,
         handleOpenModal,
         errors
      );
   };
```

[feat : signup page 기능 생성 최종](https://github.com/PurpleDynamics/PEA_Project/commit/a7b309247cd41fefbcd248f60786c1203fb9b1e1)
- 이메일과 닉네임 을 입력하지 않고 중복확인을 누르면 "이메일 or 닉네임을 입력해주세요" 라는 모달창이 뜹니다.
- input 값이 제대로 입력되지않으면 (=유효성검사가 통과되지않으면) '가입하기' 버튼은 활성화 되지 않습니다.
- 비밀번호 값과 비밀번호 입력 값이 같지 않으면 '가입하기' 버튼을 눌렀을때 모달창에 "비밀번호가 일치하지 않습니다" 라는 메세지가 보여지고, 페이지가 넘어가지않습니다.
- input에 값이 제대로 입력 되었다고 하더라도 도중에 이메일 값이나 닉네임값이 변경되면 '가입하기' 버튼이 비활성화 됩니다.
- 회원가입이 무사히 완료가 되면 로그인페이지로 넘어갑니다.

- (css -TitleText 에서 margin-bottom값 삭제했습니다 => padding-bottom으로 변경)

![녹음 2024-02-15 003711 (1)](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/e75de1da-ce28-47b0-84ea-13505a6c01da)

(이거 gif 어떻게 크기 키우나요...???)

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-15 10:28 UTC, ijimlnosk approved these changes

2024-02-15 14:25 UTC, snkchan requested changes
고생하셧습니다. 굉장하네요!!!  수정사항 하나만 고치시면 될거같아요

2024-02-15 14:25 UTC, snkchan commented on src/components/commons/check-duplication.js
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 일반함수는 utils폴더 아래 ex) user-info.js라던지 유저의 개인정보에 관한 js파일 아래서 관리하는게 좋을거 같네요

2024-02-17 16:38 UTC, hayoung78 commented on src/components/commons/check-duplication.js
[fix: CheckDuplication 파일 utils 폴더로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/53/commits/397eab10279e1a4229b1b16e87cefdb59607027a)

파일 위치 수정했습니다

2024-02-18 08:05 UTC, keeprok approved these changes
주석으로 정리 잘되있어서 해석하기 좋앗네요

2024-02-18 12:57 UTC, jjjiyoung0130 requested changes

2024-02-18 12:57 UTC, jjjiyoung0130 commented on src/utils/check-duplication.js
> +		const response = await axios.get(url);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 로그인, 회원가입 관련 로직은 개인 정보가 URL에 노출되어 보안에 취약할 수 있으니 get보다는 post로 요청하고 서버에서 중복확인을 한 후 결과를 반환받는 것은 어떨까요?
 (물론 이건 서버에 로직이 있는지 확인이 먼저 필요할 것 같긴 하군요..)

2024-02-18 12:57 UTC, jjjiyoung0130 commented on src/constants/validate-message.js
> +	message: "8글자 이하, 특수문자제외하고 입력해주세요",
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 혹시 문구가 길어지면 modal이 어떻게 보여질까요?
 - "8글자 이하로 입력해주세요. 특수문자는 사용할 수 없습니다." 로 문구를 수정하면 별로일까요?

2024-02-18 13:52 UTC, ijimlnosk commented on src/utils/check-duplication.js
> +		const response = await axios.get(url);
좋은 방법인 것 같습니다.

2024-02-18 16:35 UTC, TransparentDeveloper requested changes
고생하셨습니다.! 리뷰 확인 부탁해요~~

2024-02-18 16:35 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +		}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 회원가입 오류 시, 실행해야할 로직을 정의해주세요.

2024-02-18 16:35 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +			console.log(response, "response");
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
`console.log` 지워주세요.

2024-02-18 16:35 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +	};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 중복이 되든 안되든 `enableIfAllTrue()` 가 실행되지 않나요?

2024-02-18 16:35 UTC, TransparentDeveloper commented on src/utils/check-duplication.js
> +) => {
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 함수에 전달하는 파라미터 type 은 object 여야 합니다.

2024-02-19 08:47 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +			console.log(response, "response");
[fix: 불필요한 코드 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/53/commits/6fc5d252f783491527d4152c8ba2fff0d8356a8a)

삭제했습니다

2024-02-19 09:15 UTC, hayoung78 commented on src/constants/validate-message.js
> +	message: "8글자 이하, 특수문자제외하고 입력해주세요",
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/a9a9d8b5-ba43-47d8-ba07-e42441913c57)
이렇게 뜹니다.
[fix:modal 문구 수정](https://github.com/PurpleDynamics/PEA_Project/pull/53/commits/b2e5f8531d1c3206d28f1154cc790f5ee90fb810)
수정하겠습니다~

2024-02-19 13:01 UTC, TransparentDeveloper commented on src/utils/check-duplication.js
> +		const response = await axios.get(url);
미래에서 왔습니다.!
post 로 주는 게 맞네요 👍
역시..

2024-02-20 01:23 UTC, ijimlnosk commented on src/utils/check-duplication.js
> +		const response = await axios.get(url);
자 틀렸습니다
post로 요청 시 404 에러를 반환하고 get을 사용해야 동작이 됩니다

2024-02-20 14:13 UTC, hayoung78 commented on src/utils/check-duplication.js
> +		const response = await axios.get(url);
다틀렸어!

2024-02-20 16:09 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +		}
추가했습니다.
```
		try {
			const response = await axios.post(`${BASE_URL}`, authData);
			if (response.status === 200) {
				navigate("/signin");
			}
		} catch (error) {
			console.error("회원가입 오류", error);
			handleOpenModal("회원가입에 실패했습니다. 다시 시도해주세요.");
		}
	};
```

2024-02-20 16:10 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	};
해당 함수는 중복확인 버튼을 눌렀는지 체크해주는 함수입니다. 필요합니다..?

2024-02-20 16:11 UTC, hayoung78 commented on src/utils/check-duplication.js
> +) => {
[fix: 서버새로 연결 및 파라미터 객체 형태로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/53/commits/b9db2478b9fcd4556f95e0aa4934a187970a0a0f)
파라미터 타입 수정했습니다
```
export const CheckDuplication = async ({
	type,
	value,
	avilableRef,
	handleOpenModal,
	errors,
})
```

2024-02-20 16:13 UTC, hayoung78 commented
- 강사님 서버에 연결하여 새로 수정하였습니다.
```const BASE_URL = "https://topdragon.co.kr/api/user";```

- 중복확인 등 각각의 모달에 맞는 modalState 속성 추가하였습니다.
(error 모달 추가)
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/0103f5e0-bd07-4d5c-abdc-20eec2acce1e)

2024-02-20 17:05 UTC, jjjiyoung0130 requested changes

2024-02-20 17:05 UTC, jjjiyoung0130 commented on src/pages/signup-page.jsx
> +					registerKey="phoneq"
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - `registerKey = "phone"`를 입력하려던게 오타가 난게 아닐까 싶습니다.

2024-02-20 17:13 UTC, TransparentDeveloper requested changes
고민 많이 하셨겠네요. 고생하셨어요.!

2024-02-20 17:13 UTC, TransparentDeveloper commented on src/utils/check-duplication.js
> +		console.log(response, "response");
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `console.log` 지워주세요.

2024-02-20 17:13 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +	};
그렇다면 이름을 수정부탁합니다.

`All` 이 의미하는게 뭔가요?

2024-02-20 17:13 UTC, TransparentDeveloper commented on src/utils/check-duplication.js
> + * @component
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
-  컴포넌트 아닌 것 같습니다.

2024-02-20 17:13 UTC, TransparentDeveloper commented on src/utils/check-duplication.js
> +			console.error(`중복확인 오류 (${type})`, error);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `console.error` 삭제해주세요.

2024-02-20 17:13 UTC, TransparentDeveloper commented on src/utils/check-duplication.js
> +	const url = `${BASE_URL}/check/${type}?${type}=${encodeURIComponent(value)}`;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
`encodeURIComponent` 이건 뭔가요?

2024-02-20 17:13 UTC, TransparentDeveloper commented on src/pages/signup-page.jsx
> +	}, [emailValue, nicknameValue]);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이러면 `emailValue`, `nicknameValue` 값 변경이 감지될 때마다, 리렌더링 일어나는 거 아닌가요??
- 랜더링 최적화가 react-hook-form 사용 목적입니다.

2024-02-20 17:28 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	};
이메일 중복 확인 이랑 닉네임 중복확인 둘다 체크(?) 한다는 의미에서 all사용했는데 뻬는게 좋을까요??

2024-02-20 17:29 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +					registerKey="phoneq"
악

2024-02-20 17:33 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +	}, [emailValue, nicknameValue]);
이게 회원가입도중 중복확인 버튼을 다 통과하고 나서 갑자기 사용자가 이메일 값이나 닉네임값을 바꿨을때를 실시간으로 감지하여 다시 ```가입하기``` 버튼을 블록화 하기 위해 만든 함수입니다. 더 좋은 방법이 있을까요?

2024-02-20 17:49 UTC, hayoung78 commented on src/utils/check-duplication.js
> +	const url = `${BASE_URL}/check/${type}?${type}=${encodeURIComponent(value)}`;
```encodeURIComponent```는 문자열을 인코딩하여 URI구성 요소로 사용할 수 있게 해주는 함수입니다.
 URI는 특정 문자를 포함할 수 없기 때문에, 이 함수를 사용하여 URI 구성 요소를 안전하게 전달할 수 있다고 합니다.

2024-02-21 07:25 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +					registerKey="phoneq"
수정했습니당

2024-02-21 07:26 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +			console.error("회원가입 오류", error);
삭제했습니다.

2024-02-21 07:26 UTC, hayoung78 commented on src/utils/check-duplication.js
> +		console.log(response, "response");
삭제했습니다.

2024-02-21 07:27 UTC, hayoung78 commented on src/utils/check-duplication.js
> + * @component
```function``` 으로 수정했습니다.

2024-02-21 07:28 UTC, hayoung78 commented on src/utils/check-duplication.js
> +			console.error(`중복확인 오류 (${type})`, error);
```
if (error.response.status === 404) {
			handleOpenModal("404error");
		} else if (error.response.status === 400) {
			handleOpenModal({
				type: `중복된 ${type}입니다`,
				modalState: "error",
			});
			avilableRef.current = false;
		} else {
			handleOpenModal({
				type: `잘못된 ${type}입니다. 다시 입력해주세요.`,
				modalState: "error",
			});
		}
```

수정했습니다.

2024-02-21 08:42 UTC, TransparentDeveloper approved these changes

2024-02-21 08:44 UTC, hayoung78 commented on src/utils/check-duplication.js
> +		console.log(response, "response");
삭제했습니다~

2024-02-21 09:30 UTC, hayoung78 commented on src/utils/check-duplication.js
> +			console.error(`중복확인 오류 (${type})`, error);
[fix: sign-up 코드 수정](https://github.com/PurpleDynamics/PEA_Project/pull/53/commits/836bd37560b40efd9412eb3360ac71ae35412b24)

2024-02-21 09:30 UTC, hayoung78 commented on src/utils/check-duplication.js
> + * @component
[fix: sign-up 코드 수정](https://github.com/PurpleDynamics/PEA_Project/pull/53/commits/836bd37560b40efd9412eb3360ac71ae35412b24)

2024-02-21 09:31 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +				modalState: "error",
keyType으로 변경 완료했습니다

2024-02-21 09:31 UTC, hayoung78 commented on src/pages/signup-page.jsx
> +				modalState: "error",
[fix: sign-up 코드 수정](https://github.com/PurpleDynamics/PEA_Project/pull/53/commits/836bd37560b40efd9412eb3360ac71ae35412b24)

2024-02-21 09:41 UTC, jjjiyoung0130 approved these changes

2024-02-21 10:29 UTC, snkchan approved these changes
- 정말고생많으셨습니다. 어려운부분이었는데 든든하네요 ^.^

2024-02-21 10:30 UTC, merged