Design/publish used product
PurpleDynamics/PEA_Project pull request #55
Opened 2024-02-17 15:36 UTC by hayoung78

## 🎯 작업 내용

[design: 중고거래, 무료나눔 컴포넌트 생성](https://github.com/PurpleDynamics/PEA_Project/commit/6cdca593710c2e91956992107003a9316df49a01)
 - 중고거래 랑 무료나눔 버튼 클릭시 해당 컴포넌트를 보여줍니다.
 - 해당 컴포넌트와 used-product 페이지는 compressionWrapper 를 사용하지 않고, used-product 페이지 wrapper를 display:flex  & justify-content:center 활용하여 화면 축소 시 가운데 정렬이 되도록 하였습니다.
 - 화면 축소시 아래와 같이 화면이 변경됩니다.
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/08267f1e-28d8-4a01-8903-e18841490ace)
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/0d75e165-ea70-4ffa-9db4-5160536cd288)

[design: used-product-page 생성](https://github.com/PurpleDynamics/PEA_Project/commit/0d18e28726833f00adf2063428950ccce5c3a2c1)
 - 무료나눔 버튼 클릭시,
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/b903881e-389f-488e-8d49-307af930308c)

 - 중고거래 버튼 클릭시,
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/086f9f3c-d541-4fdc-9fe6-8e800f15af1e)

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] PR 제목 (컨벤션에 따랐는지) 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

[design: 중고거래, 무료나눔 컴포넌트 생성]
## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-18 14:30 UTC, jjjiyoung0130 requested changes

2024-02-18 16:19 UTC, TransparentDeveloper requested changes
고생하셨습니다.

2024-02-18 16:19 UTC, TransparentDeveloper commented on src/components/used-product/free-share.jsx
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `used-trade` 와 `free-share` 는 구조가 완전히 똑같네요.
- props 로 값만 다르게 하면 하나의 컴포넌트로 만들 수 있지 않을까요?

2024-02-20 18:18 UTC, snkchan reviewed
- 다른 수정사항은 다른분들이 지적해주셔서 이부분은 의견남깁니다.

2024-02-20 18:18 UTC, snkchan commented on src/components/used-product/free-share.jsx
> +				))}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
이부분은 진솔님이 작업하신 eight-product-grid컴포넌트로 대체할 수 있지 않을까요???
infinite query를 위해서 직접 map을뿌려주는 코드로 작성해두신건가요????

2024-02-21 06:43 UTC, hayoung78 commented on src/components/used-product/free-share.jsx
> +				))}
인피니티 쿼리 사용하려고 직접 코드 작성했습니다~

2024-02-21 06:54 UTC, hayoung78 commented on src/components/used-product/free-share.jsx
수정했습니다
```
<S.Wrapper>
			<S.LocationTitleContainer>
				{productData && productData.length > 0 ? (
					<S.LocationTitle>
						{productData[0]?.location}
						<TextSpacer />
						<HighlightedText color={$color} fontSize={FONT_SIZE.bg}>
							{title}
						</HighlightedText>
					</S.LocationTitle>
				) : (
					<S.NoDataText>등록된 상품이 없습니다</S.NoDataText>
				)}
```
[fix: used-free-list파일 생성 및 used-product페이지 구조 변경](https://github.com/PurpleDynamics/PEA_Project/pull/55/commits/84cd8c7cdb29b772a91b7a35ce3e19a7039cb4b4)

2024-02-21 06:54 UTC, hayoung78 commented on src/pages/used-product-page.jsx
> +	const usedProductsData = [
수정했습니다
```
<S.Wrapper>
			<S.LocationTitleContainer>
				{productData && productData.length > 0 ? (
					<S.LocationTitle>
						{productData[0]?.location}
						<TextSpacer />
						<HighlightedText color={$color} fontSize={FONT_SIZE.bg}>
							{title}
						</HighlightedText>
					</S.LocationTitle>
				) : (
					<S.NoDataText>등록된 상품이 없습니다</S.NoDataText>
				)}
```
[fix: used-free-list파일 생성 및 used-product페이지 구조 변경](https://github.com/PurpleDynamics/PEA_Project/pull/55/commits/84cd8c7cdb29b772a91b7a35ce3e19a7039cb4b4)

2024-02-21 06:54 UTC, hayoung78 commented on src/pages/used-product-page.jsx
> +		/* padding-left: 20rem; */
삭제했습니다~

2024-02-21 06:57 UTC, hayoung78 commented on src/pages/used-product-page.jsx
> +	};
코드구조 및 내용 수정 했습니다 확인부탁드립니다.
[fix: used-free-list파일 생성 및 used-product페이지 구조 변경](https://github.com/PurpleDynamics/PEA_Project/pull/55/commits/84cd8c7cdb29b772a91b7a35ce3e19a7039cb4b4)

```
const UsedProductPage = () => {
	const location = useLocation();

	//메인페이지에서 "중고거래" 혹은 "무료나눔" 중 어떤값을 클릭했는지에 대한 값
	const typeData = location.state?.type;

	const [selectedButton, setSelectedButton] = useState(typeData);

	// 버튼 클릭시, 버튼색 변경하는 이벤트함수
	const onClickTypeSelector = ({ id }) => {
		setSelectedButton(id);
	};

	return (
		<>
			<S.Wrapper>
				<Spacer height="2rem" />
				<Banner />
				<S.TradeTypeWrapper>
					<S.TradeTypeSelector
						id="usedTrade"
						onClick={() => onClickTypeSelector({ id: "usedTrade" })}
						$isSelected={selectedButton === "usedTrade"}
					>
						중고거래
					</S.TradeTypeSelector>
					<S.TradeTypeSelector
						id="freeShare"
						onClick={() => onClickTypeSelector({ id: "freeShare" })}
						$isSelected={selectedButton === "freeShare"}
					>
						무료나눔
					</S.TradeTypeSelector>
					{selectedButton === "usedTrade" && (
						<UsedFreeList
							productData={usedProductsData}
							type={"usedTrade"}
						/>
					)}
					{selectedButton === "freeShare" && (
						<UsedFreeList
							productData={freeProductsData}
							type={"freeShare"}
						/>
					)}
				</S.TradeTypeWrapper>
			</S.Wrapper>
		</>
	);
};
export default UsedProductPage;

const TradeTypeSelector = styled.button`
	padding: 0 2rem;
	cursor: pointer;
	background-color: ${COLOR.COMMON[1000]};
	color: ${({ $isSelected, id }) =>
		$isSelected
			? id === "usedTrade"
				? COLOR.PALETTE.orange.weight
				: COLOR.PALETTE.mint.weight
			: COLOR.COMMON[400]};
`;

```

2024-02-21 06:58 UTC, hayoung78 commented on src/components/used-product/free-share.jsx
해당컴포넌트 하나로 합쳐서 수정했습니다.

[fix: freeShare & usedTrade 컴포넌트 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/55/commits/522f51dd8aec174849c2ed76a941d5e583fe7642)
[fix: used-free-list파일 생성 및 used-product페이지 구조 변경](https://github.com/PurpleDynamics/PEA_Project/pull/55/commits/84cd8c7cdb29b772a91b7a35ce3e19a7039cb4b4)

[used-free-list.js]파일 생성 
```
import { useEffect, useState } from "react";
import styled from "styled-components";

import { BREAK_POINT, COLOR, FONT_SIZE } from "../../libs/styled-components";
import { HighlightedText, ProductCard, TextSpacer } from "../commons";

/**
 * @component
 * @parameter productData : array<상품데이터> - used-product페이지안에  usedProductsData 데이터를 받아옵니다.
 * @parameter type : string - 표시할 상품유형 | usedTrade | freeShare
 * @returns {JSX.Element}
 *
 * @description
 * - used-product-page 에서 사용되는 컴포넌트입니다.
 * - 중고거래/무료나눔에 해당하는 productCard를 보여줍니다.
 */
const UsedFreeList = ({ productData, type }) => {
	const [title, setTitle] = useState("");
	const [$color, setColor] = useState("");

	//중고거래/무료나눔 버튼 클릭시, 색상 변경
	useEffect(() => {
		if (type === "usedTrade") {
			setTitle("중고거래");
			setColor(COLOR.PALETTE.orange.weight);
		} else {
			setTitle("무료나눔");
			setColor(COLOR.PALETTE.mint.weight);
		}
	}, []);

	return (
		<S.Wrapper>
			<S.LocationTitleContainer>
				{productData && productData.length > 0 ? (
					<S.LocationTitle>
						{productData[0]?.location}
						<TextSpacer />
						<HighlightedText color={$color} fontSize={FONT_SIZE.bg}>
							{title}
						</HighlightedText>
					</S.LocationTitle>
				) : (
					<S.NoDataText>등록된 상품이 없습니다</S.NoDataText>
				)}
			</S.LocationTitleContainer>
			<S.ProductCardWrapper>
				{productData?.map((item, index) => (
					<ProductCard
						key={index}
						productId={index}
						title={item?.title}
						imgUrl="https://source.unsplash.com/random/?pigeon"
						createdAt="2023-03-26"
						price={item?.price}
						interestCount={10}
						chattingCount={20}
						categoriesArray={["사람", "기타"]}
					/>
				))}
			</S.ProductCardWrapper>
		</S.Wrapper>
	);
};
export default UsedFreeList;

const Wrapper = styled.div`
	width: 115.2rem;
	display: flex;
	justify-content: center;
	align-items: center;
	flex-direction: column;
	@media (max-width: ${BREAK_POINT.lg}) {
		width: 90rem;
	}
`;

const LocationTitle = styled.div`
	font-size: ${FONT_SIZE.bg};
	text-align: center;
`;
const LocationTitleContainer = styled.div`
	padding: 3.5rem 0;
`;
const NoDataText = styled.h1`
	padding: 25rem;
`;
const ProductCardWrapper = styled.div`
	width: 100%;
	display: grid;
	grid-template-columns: repeat(4, 1fr);
	row-gap: 2rem;
	@media (max-width: ${BREAK_POINT.lg}) {
		grid-template-columns: repeat(3, 1fr);
	}
`;

const S = {
	Wrapper,
	LocationTitle,
	LocationTitleContainer,
	ProductCardWrapper,
	NoDataText,
};


```

2024-02-23 13:04 UTC, jjjiyoung0130 approved these changes

2024-02-24 06:32 UTC, keeprok approved these changes
체크한줄알았네요 ㅠㅠ 확인햇습니다

2024-02-24 06:32 UTC, keeprok commented on src/components/used-product/used-trade.jsx
> +						price={item?.price}
옛날에 해놓고 사라진 부분입니다

2024-02-24 22:07 UTC, TransparentDeveloper approved these changes
고생하셨습니다.!

2024-02-25 13:19 UTC, hayoung78 commented on src/components/used-product/used-trade.jsx
> +						price={item?.price}
해당 부분은 productCard 컴포넌트 부분에 맞게 쓴것입니다. 
여기 브랜치에서 수정할 사항이 아닌것같습니다

2024-02-25 13:19 UTC, merged