PR:fpublish-main searchbar 위치조정, header 크기 115.2rem으로 조정
PurpleDynamics/PEA_Project pull request #60
Opened 2024-02-19 09:05 UTC by ijimlnosk

## 🎯 작업 내용

- [fix: publish-main searchbar 위치조정, header 크기 115.2rem으로 조정](https://github.com/PurpleDynamics/PEA_Project/commit/110e53d4bcde0b64b8563559aa53ce59e4167d0d)
- search bar 위치를 조정했습니다

<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] PR 제목 (컨벤션에 따랐는지) 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-19 12:28 UTC, jjjiyoung0130 approved these changes
확인했습니다

2024-02-19 12:57 UTC, TransparentDeveloper requested changes

2024-02-19 12:57 UTC, TransparentDeveloper commented on src/components/product-list/promotion-banner.jsx
>  `;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `justify-content: center` 가 없으면, 횡 기준으로 가운데 정렬이 안되지 않나요?
- PR 내용에 수정된 UI 이미지 함께 올려주셨으면 좋겠습니다.

2024-02-19 12:57 UTC, TransparentDeveloper commented on src/components/layouts/header.jsx
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이것도 마찬가지로 PR 내용에 업데이트 부탁합니다.
- publish-main searchbar 위치가 어디서 어디로 조정된 건가요?
- header 크기를 어떤 이유로 변경해야 했나요?

2024-02-19 13:01 UTC, TransparentDeveloper approved these changes

2024-02-19 13:08 UTC, jjjiyoung0130 commented on src/components/product-list/promotion-banner.jsx
>  `;
UI 이미지도 올려달라! 올려달라!

2024-02-20 13:07 UTC, ijimlnosk commented on src/components/product-list/promotion-banner.jsx
>  `;
확인하고...
다시 조정중에 있었습니다.

2024-02-20 13:32 UTC, ijimlnosk commented on src/components/layouts/header.jsx
page에 가운데에 들어가는 컴포넌트 크기를 115.2rem으로 설정했는데 
그것에 비해 125rem은 상대적으로 커보여서 115.2rem으로 재조정하였습니다

2024-02-20 14:08 UTC, keeprok approved these changes
확인했습니다

2024-02-22 12:06 UTC, hayoung78 commented on src/components/product-list/promotion-banner.jsx
>  `;
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ지영님 음성지원되는 이유좀...

2024-02-22 13:07 UTC, hayoung78 requested changes
UI 이미지 올려달라! 올려달라!

2024-02-22 13:07 UTC, hayoung78 commented on src/pages/product-list-page.jsx
> +					onClick={() => onClickNavigate({ keyType: "usedTrade" })}
keyType..안바뀌었는데요????????

2024-02-22 13:07 UTC, hayoung78 commented on src/pages/product-list-page.jsx
> +	z-index: 999;
이거는 필요 없는것 같습니다?? ^____________^

2024-02-22 15:05 UTC, snkchan approved these changes
확인했습니다!!

2024-02-23 15:45 UTC, hayoung78 approved these changes

2024-02-23 15:45 UTC, ijimlnosk commented on src/pages/product-list-page.jsx
> +	z-index: 999;
- [fix: type 및 불필요한 로직 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/60/commits/305cc37cc441df1e07c3bdb62998bfff9cf7c7d9)
- 삭제완료했습니다

2024-02-23 15:45 UTC, ijimlnosk commented on src/pages/product-list-page.jsx
> +					onClick={() => onClickNavigate({ keyType: "usedTrade" })}
- [fix: type 및 불필요한 로직 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/60/commits/305cc37cc441df1e07c3bdb62998bfff9cf7c7d9)
- 수정완료했습니다

2024-02-23 16:03 UTC, merged