PR: 로그인 로직 수정 및 axios-instance수정 및 user.js api 페이지 생성
PurpleDynamics/PEA_Project pull request #63
Opened 2024-02-23 15:31 UTC by ijimlnosk

## 🎯 작업 내용

- [fix: login수정, cookie받아오기, cookies에 저장해서 자동로그인, refreshToken설정 완료](https://github.com/PurpleDynamics/PEA_Project/commit/536c6e8ffc9e97e62252d6687404f1b506f55123)

- 백엔드 서버에서 쿠키값 가져오기 성공.
![스크린샷 2024-02-24 오전 12 14 40](https://github.com/PurpleDynamics/PEA_Project/assets/98089768/3d1129f4-4a22-44d2-8cd3-d2613d5908d2)

- 받아온 token값을 react-cookie를 사용하여  자동로그인 클릭 시 저장한다음 페이지 접속시 불러오는 로직을 작성했습니다
<img width="473" alt="스크린샷 2024-02-24 오전 12 21 30" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/fdfc5ffb-a3e1-4f31-a38c-e214974d433e">
<img width="477" alt="스크린샷 2024-02-24 오전 12 22 18" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/6bba4c73-2ceb-4c15-a679-53b4c6300024">

### axios-instance 작성 완료
- token이 존재하는 경우 header에 Authorization을 추가하도록 하였습니다
<img width="572" alt="스크린샷 2024-02-24 오전 12 24 47" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/4be9cd37-8628-422f-b41c-f33560c5a968">
<br/>
<br/>

- token이 만료되었을 때(401 에러가 반환되었을 때)
- 토큰을 갱신하는 interceptor를 작성하였습니다.
- (잘 작동하는것은 확인하였으나 솔직히 아직 잘 모르겠습니다(잘 작동하는지))

### user.js 생성
- user api 요청 js를 생성했습니다.
- 1~7번 까지 완료하였고, 나머지 부분은 채윤님이 작성하실 예정입니다.
- 그리고 조금 다른 내용이 들어가 있는데 어디에 넣어야할지 애매해서 넣었습니다. 
- accessToken을 새로고침하는 함수입니다.
<img width="760" alt="스크린샷 2024-02-24 오전 12 29 53" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/4cc0aa8d-29a0-4b47-99be-b52f3652d486">

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-23 17:29 UTC, jjjiyoung0130 approved these changes

2024-02-24 03:41 UTC, ijimlnosk commented on src/libs/axios/auth/storage-manager.js
> + * localStorage를 사용하여 애플리케이션 인증 토큰을 관리하는 파일입니다.
- [fix: jsdocs 수정](https://github.com/PurpleDynamics/PEA_Project/pull/63/commits/1c04651bfe2db8e2d7615d706afb96cc45377bfd)
- 수정했습니다

2024-02-24 07:11 UTC, hayoung78 reviewed
역시...
솔직히 말하면 제가 이거에 리뷰 달 실력이 아니라고 판단됩니다만.. 열심히 뜯어보았습니다 ~~ 굳굳

2024-02-24 07:11 UTC, hayoung78 commented on src/libs/axios/base/axios-instance.js
> +
- 해당 코드는 합칠수있을것같습니다 :)
```
try {
          const newAccessToken = await refreshAccessToken(); 
          originalRequest.headers["Authorization"] = `Bearer ${newAccessToken}`;
          return axiosInstance(originalRequest); 
        } 
```
- 주석 오타 찾음~~~~얏호
```"발금"```  -> ```"발급"``` 수정요망~

2024-02-24 07:13 UTC, hayoung78 requested changes
역시..
솔직히 제가 이 코드를 리뷰할수있는 실력이 안되는것같지만? 열심히 뜯어보았습니다..
굳굳~~

2024-02-24 08:07 UTC, TransparentDeveloper reviewed
[🚨 긴급]

2024-02-24 08:07 UTC, TransparentDeveloper commented on package.json
> +    "dotenv": "^16.4.5",
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 환경변수 값 불러오기 위한 목적으로 의존성 추가하신건가요??
- 참고 한번 해주세요~ [CRA (create-react-app) dotenv](https://4sii.tistory.com/46)

2024-02-24 08:45 UTC, TransparentDeveloper requested changes
주석 꼼꼼히 작성해주셨네요.! 👍

2024-02-24 08:45 UTC, TransparentDeveloper commented on src/pages/signin-page.jsx
> +			noticeText: type,
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- noticeText 에 들어가는 `type`,, 의미전달이 안됩니다.
- 이 타입에는 어떤 값들이 들어갈 수 있나요?
- 변수명을 더 직관적으로 고치거나, 이런데야 말로 주석을 달아서 무슨 값이 있을 수 있는지 적어줘야 할 거 같습니다.

2024-02-24 08:45 UTC, TransparentDeveloper commented on src/utils/index.js
>  export * from "./storage-manager";
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `storage-manager` 완전히 삭제하셨는데,, 이 부분도 수정 부탁합니다.

2024-02-24 08:45 UTC, TransparentDeveloper commented on src/utils/storage-manager.js
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 삭제한 이유가 무엇인가요?
- 단순 질문입니다. 🙃

2024-02-24 08:45 UTC, TransparentDeveloper commented on src/libs/react-router-dom/admin-router.jsx
>  	const navigate = useNavigate();
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 보통 일반함수보다 훅함수를 더 우선하여 작성합니다.

2024-02-24 08:45 UTC, TransparentDeveloper commented on src/pages/signin-page.jsx
>   * - password: qwer1234
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `@example` 에는 해당 컴포넌트/함수 의 사용 예시를 작성합니다.
- 테스트 이메일, 비밀번호는 노션에 작성합시다.

2024-02-24 09:17 UTC, ijimlnosk commented on src/utils/storage-manager.js
위치가 이동되었습니다

2024-02-24 12:55 UTC, ijimlnosk commented on .env
- [fix: .env설정](https://github.com/PurpleDynamics/PEA_Project/pull/63/commits/de2a1477c4d2862f711135017a1400b481f99ed0)
- 수정했습니다

2024-02-24 12:58 UTC, ijimlnosk commented on src/pages/signin-page.jsx
> +			noticeText: type,
같은 noticeText 로 변경했습니다.

2024-02-24 12:59 UTC, ijimlnosk commented on src/utils/index.js
>  export * from "./storage-manager";
- [fix : 로직 수정 및 jsDocs 수정](https://github.com/PurpleDynamics/PEA_Project/pull/63/commits/8f37b9a2119f17e803439288ca3c141664bf352d)
- 삭제하였습니다

2024-02-24 12:59 UTC, ijimlnosk commented on src/libs/react-router-dom/admin-router.jsx
>  	const navigate = useNavigate();
변경하였습니다

2024-02-24 22:13 UTC, TransparentDeveloper requested changes

2024-02-24 22:13 UTC, TransparentDeveloper commented on .env
아니요. 단순히 gitInore 만 수정하면, 커밋이력으로 백엔드 url 은 확인 가능합니다. 
`git reset` 으로 url 이 공개된 커밋 이력을 지워야 합니다.

2024-02-24 22:17 UTC, TransparentDeveloper requested changes
확인바랍니다.

2024-02-24 22:17 UTC, TransparentDeveloper commented on package.json
> +    "dotenv": "^16.4.5",
<img width="677" alt="스크린샷 2024-02-25 오전 7 08 54" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/712ed3f6-a7e4-4044-aa90-608f3d188227">

불필요한 라이브러리가 설치되었습니다.

2024-02-24 22:17 UTC, TransparentDeveloper commented on .env
- 아니요. 단순히 gitIgnore 에 해당 파일을 등록을 한다고 해도, 커밋이력에 백엔드 url 이 노출되어있습니다.
- git reset 으로 해당 파일 생성이력을 완전히 삭제해야 합니다.

2024-02-25 13:14 UTC, TransparentDeveloper approved these changes
고생 하셨습니다.!

2024-02-25 13:49 UTC, hayoung78 approved these changes
수정된것들 다 확인~

2024-02-25 14:01 UTC, jjjiyoung0130 approved these changes

2024-02-25 17:14 UTC, snkchan approved these changes
고생하셨습니다 .! 3따봉갑니다.👍👍👍

2024-02-25 17:15 UTC, merged