PR/PD-49: detail-product 페이지 퍼블리싱 완료했습니다.
PurpleDynamics/PEA_Project pull request #64
Opened 2024-02-24 08:13 UTC by keeprok

## 🎯 작업 내용

- [design: detialProduct,Info컴포넌트 생성](0f8f97374ed092c83fc19b7ff04a864b64754b74)
  - 배너를 중심으로 기준을 나눠서 컴포넌트를 작성했습니다
  - 디테일 이미지부분과 설명 부분을 나눠서 작성햇습니다
  - 채팅하기 와 공유하기 및 찜하트 부분 기능 추가 들어가야됩니다
  - product부분 선택할시 border색변경가능하게 했습니
 <div align="center">

![React-App-Chrome-2024-02-24-16-25-26](https://github.com/PurpleDynamics/PEA_Project/assets/140785214/9b74fc55-3c7f-49ae-bcf7-e774adf0a8d4)

</div>
 - [design : banner 컴포넌트 생성](58a5db57194504c916312cb2bad0e856b829c294)
  -  배너안의 main숫자 api받아오면기능추가로  문자열 함수로 변경해주면됩니다 
- [desgin: TagProducts 컴포넌트 작성했습니다](4261bbce5136e3a10d93f850fc85b667ad6a7952)
  - TagChart 가 api추가되면서 생성될시 사용할컴포넌트도  생성은 해놨습니다 그전까지는 직접 detail-product-page에 사용되고 그후에는 
   TagData에서 사용될예정입니다

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-24 13:33 UTC, ijimlnosk requested changes
고생하셨습니다

2024-02-24 13:33 UTC, ijimlnosk commented on .env
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- gitignore에 추가 안되어있는 것 같습니다
- 제가 올렸습니다! 삭제 부탁드려요

2024-02-24 13:33 UTC, ijimlnosk commented on package.json
> +    "dotenv": "^16.4.5",
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 여기두요

2024-02-24 13:33 UTC, ijimlnosk commented on src/components/detail-product/detail-info.jsx
> +const productPriceAndLocation = styled.div`
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 컨벤션을 틀리셨습니다
- `ProductPriceAndLocation`으로 변경해주세요.

2024-02-24 13:33 UTC, ijimlnosk commented on src/components/detail-product/seller-banner.jsx
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 글씨 크기를 좀 줄이거나 아이콘과 글씨의 간격이 좀 더 넓으면 좋을 것 같습니다.

2024-02-24 13:33 UTC, ijimlnosk commented on src/components/detail-product/tag-products/tag-product-chart.jsx
> +            /> */}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 주석은 지워주세요~

2024-02-24 13:53 UTC, hayoung78 requested changes
전체적으로 break-point가 되어있는것같지않습니다.

2024-02-24 13:53 UTC, hayoung78 commented on src/components/detail-product/detail-info.jsx
> +				</S.ProductPrice>
아래 사진이 피그마 인데, 배치가 맞지 않는것같습니다
- 금액 색도 다르고 금액 위치도 다른듯?
![image](https://github.com/PurpleDynamics/PEA_Project/assets/142880051/49452239-2711-4c2e-bf61-a0218060e8f2)

2024-02-24 13:53 UTC, hayoung78 commented on src/components/detail-product/detail-image.jsx
> +const buttonStyle = css`
width:100% 이렇게 줘버리면 화면 축소시에 버튼이 이상하게 될것같습니다. 
break-point 적용되는지 확인도 부탁드립니다.

2024-02-24 13:53 UTC, hayoung78 commented on src/components/detail-product/tag-products/tag-data.jsx
> +const TagData = ({ findProduct }) => {
jsDocs가 없숩니다 영록님이 만진곳이 맞나요??

2024-02-24 13:53 UTC, hayoung78 commented on src/libs/axios/base/instance.js
> +	});
이게 변경점이 왜 잡히지??

2024-02-24 14:26 UTC, keeprok commented on src/components/detail-product/tag-products/tag-data.jsx
> +const TagData = ({ findProduct }) => {
이부분 아직 차트 작성데이터가 없어서 관심사 분리만 해놓은 상태 이고쓰이지는 않씀니다

2024-02-24 14:54 UTC, keeprok commented on src/components/detail-product/tag-products/tag-product-chart.jsx
> +            /> */}
이부분은 관심사 분리만 되있는곳이라 차트 추가하고 넣겠습니다

2024-02-24 14:55 UTC, keeprok commented on src/components/detail-product/seller-banner.jsx
간격을 수정했습니다

2024-02-24 14:57 UTC, keeprok commented on src/components/detail-product/detail-info.jsx
> +const productPriceAndLocation = styled.div`
수정했습니다

2024-02-24 14:57 UTC, keeprok commented on package.json
> +    "dotenv": "^16.4.5",
수정했습니다

2024-02-24 14:57 UTC, keeprok commented on .env
넵 감사합니다

2024-02-24 17:39 UTC, snkchan requested changes
고생하셨습니다. 컴포넌트 구조를 너무 많이 나누신거같습니다. 전반적으로 한눈에 들어오지 않아서 review가 수월하지 않은것 같아요. 관심사 분리에대해 다시한번 생각해보시는 것도 좋을것 같습니다.
저같은 경우에는 한가지의 컴포넌트에서 너무많은 기능, data들이 다뤄진다면 관심사를 분리하며 작성합니다. 
또한 해당 컴포넌트가 어떤 data를 관리하는지에 따라서 하나의 컴포넌트로 분리를 하는데 
지금과 같은 구조는 좀 복잡할것 같아요. 수정사항 확인해주세요~~고생하셧습니다

2024-02-24 17:39 UTC, snkchan commented on src/libs/msw/database/products.json
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
해당 변경점은 추후에 패칭된 데이터에서 받아올 정보를 사용할 것이기때문에 pr을위해서 수정한부분이었다면 pr올리기전에 스크린샷으로 저장하시고 다시 돌려두는게 좋을 것 같습니다.

2024-02-24 17:39 UTC, snkchan commented on src/pages/detail-product-page.jsx
> +	);
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 서버에 대한 정보를 이제 알게됬으니 findProduct라는 데이터는 따로 작성안해주셔도 될거같아요.
- 또한 데이터형태가 object인것을 확인했으니 productDetailObject와같은 변수명을 사용해주시면 해당 데이터가 어떤정보를 가진 어떤형태의 데이터인지 한눈에 더 들어올거 같습니다.

2024-02-24 17:39 UTC, snkchan commented on src/pages/detail-product-page.jsx
> +`;
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 해당부분은 CenterBox컴포넌트가 merge되었으니 그부분으로 대체 해야할것 같습니다.

2024-02-24 17:39 UTC, snkchan commented on src/pages/detail-product-page.jsx
> +import TagProducts from "../components/detail-product/tag-products/tag-products";
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- barrel파일에서 import하셔야 합니다.

2024-02-24 17:39 UTC, snkchan commented on src/components/detail-product/detail-product.jsx
> +import DetailInfo from "./detail-info";
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 컨밴션에 맞게 수정부탁드립니다.

2024-02-24 17:39 UTC, snkchan commented on src/components/detail-product/item-summary.jsx
> +const ItemSummary = () => {
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 현재컴포넌트도 서버에서 넘어온 response에 담긴 정보를 바탕으로 화면에 보여져야하기때문에 props로 findProdcut로 선언해주신 data를 전달받아야 할거 같네요

2024-02-24 17:39 UTC, snkchan commented on src/components/detail-product/item-summary.jsx
> +const SpecsText = styled.div`
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 해당tag는 text로 보여질 tag인거 같은데 div로 작성하신 이유가있나요? p테그나 b태그 span태그등등으로 작성하셔도 될거 같은데

2024-02-24 17:39 UTC, snkchan commented on src/components/detail-product/item-summary.jsx
> +						size={"3.5rem"}
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 저번회의 에서 클릭기능이 없는 icon은 responsiveIcon이아닌 일반 아이콘으로 불러오기로 했엇는데 수정이 필요합니다.

2024-02-24 17:39 UTC, snkchan commented on src/components/detail-product/seller-banner.jsx
> +			iconText: "매너온도",
- IconAndText트의 docs에보시면 gap이라는 것이있는데 확인해보시면 해결하실수 있습니다.

2024-02-24 17:39 UTC, snkchan commented on src/components/detail-product/tag-products/tag-product-chart.jsx
> +			</div>
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 저번에 수요일날 모여서 진행할때 style이들어가지 않은 컴포넌트라도 해당 컴포넌트가 어떤 내용을 나타내는지 알 수 있게 해당태그의 이름을 붙혀서 styled컴포넌트로 작성하기로 했엇는데 일반 div태그로 작성하시면 안될 것 같습니다.
- 또한 해당 text중에 모든 글자가 크기가 같지않을탠데 수정해주셔야 할거 같아요

2024-02-24 17:39 UTC, snkchan commented on src/components/detail-product/tag-products/tag-products.jsx
> +					총 {TagInProductList.length}건
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이부분은 length로 처리하셔도 문제는 없지만 패칭된 data의 배열의 길이값이 들어가야 맞을거 같네요 아직 datafetching전이라 findProduct.prodcutList.length이런식으로 임시로 작성해두셧다면 더좋을것 같네요

2024-02-24 17:51 UTC, snkchan requested changes
추가적인 review남깁니다.~~

2024-02-24 17:51 UTC, snkchan commented on src/components/detail-product/detail-image.jsx
> +	const [imageIndex, setImageIndex] = useState(0);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- image가 넘어가는 것을위해 imageData를 상태로 선언해주신것은 좋네요 하지만 imageIndex또한 상태로 관리되어야 하는 이유가 있을까요???? 
- state라는 것은 상태를 바꿔줍니다. 즉 state로 선언된 변수의 값이 바뀌면 해당 상태를 가지고있는 컴포넌트전체가 재실행되고 이는 rerender가되는 것인데 저희는 원하는 시점에 화면을 render해주기 위해서 setState를 실행함으로써 개발자가 의도한 순간에 화면의 render를 발생시킵니다. 현재 관리되고있는 imageIndex는 화면에서 어떤 부분을 담당하고있는지 생각해보셧으면 좋겠습니다.

2024-02-24 17:51 UTC, snkchan commented on src/components/detail-product/detail-info.jsx
> +	const [categoryData, setCategoryData] = useState([]);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 위에서 언급한것과 마찬가지로 categoryData는 어떤 것을 위한 상태인가요???? 화면 render에 꼭 필요한 state인가요?

2024-02-26 12:20 UTC, keeprok commented on src/components/detail-product/detail-info.jsx
> +				</S.ProductPrice>
수정했습니다

2024-02-26 12:22 UTC, keeprok commented on src/libs/axios/base/instance.js
> +	});
삭제 했습니다

2024-02-26 12:24 UTC, keeprok commented on src/libs/msw/database/products.json
네 삭제 후 push하겠습니다

2024-02-26 13:03 UTC, keeprok commented on src/components/detail-product/detail-image.jsx
> +const buttonStyle = css`
안그럽니다

2024-02-26 13:11 UTC, keeprok commented on src/pages/detail-product-page.jsx
> +`;
네 변경하겠습니다

2024-02-26 14:20 UTC, keeprok commented on src/components/detail-product/tag-products/tag-products.jsx
> +					총 {TagInProductList.length}건
..

2024-02-26 14:20 UTC, keeprok commented on src/pages/detail-product-page.jsx
> +	);
..

2024-02-26 14:20 UTC, keeprok commented on src/pages/detail-product-page.jsx
> + * @parameter findProduct : object<특정된 상품데이터> - detail-product-page 에서 Params로id를 특정해 받아옴
..

2024-02-26 14:22 UTC, keeprok commented on src/components/detail-product/detail-image.jsx
> +	const [imageIndex, setImageIndex] = useState(0);
image데이터를 state로 관리를 안하고 index만을 관리하는것으로 수정했습니다 
````
const [imageIndex, setImageIndex] = useState(0);
   const imageData = findProduct.imageSrcList;
````

2024-02-26 15:31 UTC, closed without merging