Design/my page
PurpleDynamics/PEA_Project pull request #65
Opened 2024-02-24 17:10 UTC by snkchan

## 🎯 작업 내용

- [feat: header icon중 my-page아이콘 클릭시 my-page이동기능 구현](https://github.com/PurpleDynamics/PEA_Project/commit/48a04a28ab9308933e7a87fc496d4208f768b26c)
  - my-page로 이동하기위해 header에 my-page아이콘 클릭시 이동기능을 추가했습니다.
 
- [design: my-page publishing작업했습니다.](https://github.com/PurpleDynamics/PEA_Project/commit/67e270fe1e446ece2880540eeb89a90c0393be98)
  - my-page컴포넌트에서는 4가지section을 나누어 하위 컴포넌트를 관리합니다.
  - 추후에 data fetching이 이루어지면 my-page에서 데이터 패칭을 진행하고 
    각각의 section에 맞는 데이터를 전달하는 방식으로 관리될것입니다.
  - <img width="605" alt="image" src="https://github.com/PurpleDynamics/PEA_Project/assets/144839872/05db3459-33dd-438e-a5f2-34b96b7cacb6">
  - 다음과 같은 4가지의 section을 관리합니다.
  - InformationSection 에서는 user의 개인정보를 보여줍니다.
  - GraphSection 에서는 user의 거래관련 금액정보를 보여줍니다.
  - ManageProductSection user의 거래형태에 따른 거래량 정보를 보여줍니다.
  - ProductListSection user의 거래형태에 따라 해당 상품들을 보여줍니다.
- [docs: 컴포넌트 설명 및 props수정](https://github.com/PurpleDynamics/PEA_Project/commit/0279d9a0bccd42f5a2b264f80f3171316c240254)
  - 각 컴포넌트에 fetching을 고려한 props로 변경했습니다.
  - 각 컴포넌트에 docs작성했습니다.
## 🎞구현된 design
- ![GIFMaker_me (1)](https://github.com/PurpleDynamics/PEA_Project/assets/144839872/a298376a-b7f9-4807-be08-5a3382b0aa18)
<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-25 13:42 UTC, ijimlnosk reviewed
잘 봤습니다
좋습니다
다만, navi와 idx에 관해서는 얘기를 좀 해보는게 좋을 것 같습니다

2024-02-25 16:36 UTC, hayoung78 approved these changes
미디어 쿼리 break-point 가 저도 그렇게 뜨긴하더라고요..? 흠..

2024-02-25 16:36 UTC, hayoung78 commented on src/components/my-info/manage-products-section.jsx
> + * - "등록상품", "구매상품", "판매완료", "관심상품" 4가지의 정보를 보여주며 각정보에 맞는 수량이 함께보여집니.
집니(다).

2024-02-25 17:44 UTC, TransparentDeveloper approved these changes
고생하셨습니다.

2024-02-25 17:44 UTC, TransparentDeveloper commented on src/components/layouts/header.jsx
> +	const navi = useNavigate();
공감합니다.

2024-02-26 14:19 UTC, snkchan commented on src/components/my-info/manage-products-section.jsx
> + * - "등록상품", "구매상품", "판매완료", "관심상품" 4가지의 정보를 보여주며 각정보에 맞는 수량이 함께보여집니.
- [fix: 변수명 navi -> navigate로 수정](https://github.com/PurpleDynamics/PEA_Project/pull/65/commits/3b18590e55234a18391bdde470aa1935a78adb05)
- 좋은 지적입니다.!! navi에서 navigate로 수정했습니다.

2024-02-26 14:21 UTC, ijimlnosk approved these changes

2024-02-26 15:04 UTC, keeprok reviewed
수고하셨습니다

2024-02-26 15:04 UTC, keeprok commented on src/components/my-info/product-list-section.jsx
> +	cursor: pointer;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
SaleOrUsedArea 이부분에 cursor주면 안되나요? 중복으로 들어가는거같아서

2024-02-26 15:15 UTC, jjjiyoung0130 requested changes

2024-02-26 15:15 UTC, jjjiyoung0130 commented on src/components/my-info/graph-section.jsx
> +const GraphSection = ({ priceData }) => {
혹시 priceData는 어디에 쓰이는 걸까요? 현재 코드에서는 어디서 어떻게 재가공해서 사용된 것인지 모르겠어요.

2024-02-26 15:15 UTC, jjjiyoung0130 commented on src/components/my-info/graph-section.jsx
> +	const [isClicked, setIsClicked] = useState(false);
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - isClicked에 대한 initialValue가 false로 되어있는데 초기 렌더 시 보여주는 그래프에 맞춰서 설정해주는게 좋지않을까요? 그래프를 보여주고 시작할테니까..?

2024-02-26 16:34 UTC, snkchan commented on src/components/my-info/graph-section.jsx
> +const GraphSection = ({ priceData }) => {
참고사항에 적어두었습니다... 추후에 최상단 my-page컴포넌트에서 데이터패칭을한후 하위컴포넌트들에게 전달하기위해 프롭스이름만 적어두었다고 작성해놨습니다

2024-02-26 16:35 UTC, snkchan commented on src/components/my-info/graph-section.jsx
> +	const [isClicked, setIsClicked] = useState(false);
디자인의 기획이 첫화면의 랜더에는 어떤것도 클릭되지않은 상태를하기로 되어있어서 그상태를 구현해둔것입니다.

2024-02-26 16:35 UTC, snkchan commented on src/components/my-info/product-list-section.jsx
> +	cursor: pointer;
클릭이 가능한부분에서 cursor를 주는것이 맞지않을까요?

2024-02-26 16:52 UTC, snkchan commented on src/components/my-info/graph-section.jsx
> +	const [isClicked, setIsClicked] = useState(false);
- [fix: transitionCard이 클릭된상태로 로드되도록 수정](https://github.com/PurpleDynamics/PEA_Project/pull/65/commits/765907baf8dfb3f3a5c358eacfa6b7336f2bfd02)
수정완료했습니다.

2024-02-26 16:53 UTC, jjjiyoung0130 approved these changes

2024-02-26 16:58 UTC, merged