PR: chat api 생성했습니다.
PurpleDynamics/PEA_Project pull request #66
Opened 2024-02-25 17:24 UTC by hayoung78

## 🎯 작업 내용

### chat api 생성했습니다.

- 채팅방생성
- 채팅방 메세지 모두 읽기
- 채팅방 메세지 저장
- 채팅 로그 조회
- 전체채팅방 목록 조회
- 특정물품 채팅방 목록 조회

*함수컨벤션
```요청종류 / 요청주소 / 정보 / By parameter ``` 

**#### ※컨벤션에 맞게 작성하였으나 ,애매한 부분이있어서 더 좋은 의견이 있다면 남겨주세요!**
수정하겠습니다.
<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] PR 제목 (컨벤션에 따랐는지) 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-25 17:53 UTC, TransparentDeveloper requested changes

2024-02-25 17:53 UTC, TransparentDeveloper commented on src/libs/axios/base/chat.js
> +};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 쿼리 파라미터 싣는 방법는 다른 함수들과 다르네요?? 통일시켜 주시길 바랍니다.

2024-02-25 17:53 UTC, TransparentDeveloper commented on src/libs/axios/base/chat.js
> + * @parameter room_idx : number - 채팅방 id
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 컨벤션에 `snake_case` 없는 걸로 알고 있습니다.
- 수정 부탁합니다.

2024-02-25 17:53 UTC, TransparentDeveloper commented on src/libs/axios/base/chat.js
> +	);
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 여기도 쿼리 파라미터,,,, 공식 문서에 나와있는 방법대로 사용하는게 좋을 것 같습니다.

2024-02-25 17:53 UTC, TransparentDeveloper commented on src/libs/axios/base/chat.js
> + * @parameter room_idx : number - 채팅방 id
- 다른 곳에도 `snake_case` 로 작성된게 많네요;;

2024-02-26 05:47 UTC, hayoung78 commented on src/libs/axios/base/chat.js
> + * @parameter room_idx : number - 채팅방 id
노션에 맞게 써야하는줄알고 ;; 죄송합니다 수정했습니다
```
export const postChatReadAllByRoomIdx = async ({ roomId }) => {
	const response = await axiosInstance.post("/chat/read-all", {
		params: {
			roomId,
		},
	});
	return response;
};

```

2024-02-26 05:48 UTC, hayoung78 commented on src/libs/axios/base/chat.js
> +};
수정했습니다.

```
export const getChatChatLogByRoomIdx = async ({ roomId }) => {
	const response = await axiosInstance.get("/chat/chat-log", {
		params: {
			roomId,
		},
	});
	return response;
};
```

2024-02-26 05:48 UTC, hayoung78 commented on src/libs/axios/base/chat.js
> +	);
[fix: 컨벤션에 맞게 파라미터 수정](https://github.com/PurpleDynamics/PEA_Project/pull/66/commits/644642a62950ed57d9624d5c7119e5df1b59b3e2)
수정했습니다

2024-02-26 05:48 UTC, hayoung78 commented on src/libs/axios/base/chat.js
> +	);
```
export const getChatProductChatListByPageAndProdIdx = async ({
	productId,
	page,
}) => {
	const response = await axiosInstance.get("/chat/product-chat-list", {
		params: {
			page,
			productId,
		},
	});
	return response;
};

```

2024-02-26 07:24 UTC, TransparentDeveloper approved these changes
고생하셨습니다.

2024-02-26 08:54 UTC, keeprok approved these changes
확인했습니다

2024-02-26 13:14 UTC, jjjiyoung0130 approved these changes
확인했습니다

2024-02-26 13:32 UTC, merged