PR/PD-49: detail-product 페이지 퍼블리싱 완료했습니다.(대체)
PurpleDynamics/PEA_Project pull request #67
Opened 2024-02-26 15:53 UTC by keeprok

## 🎯 작업 내용

[PR/PD-49: detail-product 페이지 퍼블리싱 완료했습니다.](https://github.com/PurpleDynamics/PEA_Project/pull/64)부분을 이어서 작성합니다
<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-02-29 05:26 UTC, ijimlnosk approved these changes
확인했습니다

2024-02-29 13:40 UTC, hayoung78 requested changes
닫힌 PR을 다시 여는것이라도 내용을 복붙해서 description 작성해주셨으면 좋겠습니다.
또 들어가서 봐야하는게 굉장히 불편합니다. (기억도 안나고..)

2024-02-29 13:40 UTC, hayoung78 commented on src/components/detail-product/item-summary.jsx
> +					<S.iconContainer>
혼자 'i'con 인게 거슬립니다

2024-02-29 13:40 UTC, hayoung78 commented on src/pages/detail-product-page.jsx
> +			<CenterBox>
CenterBox를 이렇게 주는게 맞나요..?
그냥 전체로 하나 묶으면 가운데로 잘 모여질텐데..?

2024-02-29 13:40 UTC, hayoung78 commented on src/pages/detail-product-page.jsx
> +			<CenterBox>
혹시 이렇게 준 이유가 있나요??

2024-02-29 13:47 UTC, keeprok commented on src/pages/detail-product-page.jsx
> +			<CenterBox>
banner때문에 나눠서 줬습니다

2024-02-29 14:15 UTC, keeprok commented on src/components/detail-product/item-summary.jsx
> +					<S.iconContainer>
[fix : 컨벤션맞춰서 수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/67/commits/2b48f611bac3d602df2f5c124cce32271a6fe516)

2024-02-29 15:14 UTC, jjjiyoung0130 requested changes

2024-02-29 15:14 UTC, jjjiyoung0130 commented on src/pages/detail-product-page.jsx
> +	); //삭제? useParams를 통해서 특정 제품 데이터를 가져오는건데(api사용하면 삭제할예정?)
주석.. 남긴 상태로 merge 하실건가요...?

2024-03-01 04:21 UTC, hayoung78 commented
+ 저번에 저거 디자인 맞춰달라고한거(내가 사진 캡쳐해서 단거) 수정된거맞나요? 
그거 바뀌었으면 바뀐사진으로 description.. 수정 해줘야 알죠..

2024-03-01 07:36 UTC, keeprok commented on src/pages/detail-product-page.jsx
> +	); //삭제? useParams를 통해서 특정 제품 데이터를 가져오는건데(api사용하면 삭제할예정?)
다지우고 올린다는걸 놓쳤네요

2024-03-01 14:23 UTC, jjjiyoung0130 approved these changes

2024-03-02 13:01 UTC, hayoung78 approved these changes

2024-03-02 15:56 UTC, snkchan approved these changes
수고하셧습니다.

2024-03-02 15:56 UTC, merged