PR/PD-41: react router dom 의존성 추가 및 설정 파일 셍성 했습니다.
PurpleDynamics/PEA_Project pull request #7
Opened 2024-01-23 16:05 UTC by ijimlnosk

## 🎯 작업 내용

- [config: react-router-dom 의존성 추가](https://github.com/PurpleDynamics/PEA_Project/commit/7298eb1acf701445415fbdf08f189c27ea26ce1a)
  - react-router-dom 의존성 추가 했습니다.

- [config: react-router-dom 설정 파일 추가 및 pages 폴더 구조 생성](https://github.com/PurpleDynamics/PEA_Project/commit/06571814292a0afa106838a278abe35871390aa1)
  - createBrowserRouter 생성
  - pages 폴더 구조 생성  ( 페이지 관련 컴포넌트 작성 시 해당 폴더에서 작업 해주세요 🫡
  - barrel file 생성

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] PR 제목 (컨벤션에 따랐는지) 확인 
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!! 

### 👍 문제가 없다고 생각된다면...
1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...
1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.
```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```
2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-01-23 16:13 UTC, hayoung78 approved these changes
확인완료했습니다

2024-01-23 16:13 UTC, snkchan approved these changes
한방에 완벽하게 작업하신거 같습니다...... 고생하셨습니다😘

2024-01-23 16:13 UTC, jjjiyoung0130 approved these changes
확인했습니다

2024-01-24 07:12 UTC, TransparentDeveloper requested changes
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 폴더 트리 관련해서 설명이 조금 더 필요합니다. 
  - `pages` 폴더 아래, `products`, `sign` 폴더 가 있네요. 파일 이름을 보니 어떤 기능을 하는지 이해가 잘 됩니다. 👍
  - 그런데, `product-list-page.jsx` 파일은 왜 `products` 폴더 아래 두지 않았죠? 결국 상품을 전시하는 기능을 수행하지 않나요??
  - 어떤 기준으로 각 폴더가 파일을 관리하는지 PR 본문이나 노션에 문서화되어있으면 좋겠습니다. 

- 추가로 `products`, `sign` 폴더도 두개 이상의 파일을 관리하는데, 베럴파일을 두어야하지 않나요?

2024-01-24 07:31 UTC, ijimlnosk commented
수정했습니다
4d736d6a82dc4eaac2345d27c73612aeba7dd791

2024-01-24 10:22 UTC, keeprok commented
확인했습니다

2024-01-24 11:47 UTC, keeprok approved these changes

2024-01-24 12:46 UTC, merged