PR/PD-57: 채팅 기능을 추가했습니다
PurpleDynamics/PEA_Project pull request #70
Opened 2024-03-02 16:10 UTC by ijimlnosk

## 🎯 작업 내용

- [config: socket.io 의존성 추가](https://github.com/PurpleDynamics/PEA_Project/commit/8171ea3425ceb3d6d7f4c19e67b4bac44f7d0f37)
- socket 기능 사용을 위한 의존성을 추가했습니다

- [feat: message-context생성](https://github.com/PurpleDynamics/PEA_Project/commit/36ee784df162d1b782ca747db388017c0ca84574)
- 전역상태 관리를 위한 message context를 생성했습니다.

- [fix: message provider 초가](https://github.com/PurpleDynamics/PEA_Project/commit/3173b83bfb75f0790d271d73fdf1d4a9964a49bd)
- message context 사용을 위한 message provider를 추가했습니다.

- [fix: chat_token 추가](https://github.com/PurpleDynamics/PEA_Project/commit/d1892a701d5655d95ea506c21dad75d9be538680)
- [fix: chat token storage 추가](https://github.com/PurpleDynamics/PEA_Project/commit/e73662a8358f0b78f6a45353a13d2e3c8ca65e7a)
- [fix: chat token 저장 로직 생성](https://github.com/PurpleDynamics/PEA_Project/commit/658a4e9349f8cbdf355b0a1fd7a1a90424a685ac)
- 로그인시 받아오는 User의 chat_token을 사용하기 위해 추가했습니다.

- [feat: chatting 생성](https://github.com/PurpleDynamics/PEA_Project/commit/d1af6ef04173d963bb180b2aa75041001be78f84)
- 채팅 기능을 추가했습니다.
- 정상작동은 하나 
- websocket.js:39 WebSocket connection to 'wss://topdragon.co.kr/socket.io/?EIO=4&transport=websocket&sid=vLLHUBpTxR6iPKkyABfR' failed: 
- 이러한 오류메시지가 발생합니다

<img width="1004" alt="스크린샷 2024-03-03 오전 1 06 26" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/e698406c-a70b-4d4c-a940-6e16e7088df6">
- 좌 : test10101@test.test
- 우 : testtest1@test.com

<img width="1004" alt="스크린샷 2024-03-03 오전 1 07 59" src="https://github.com/PurpleDynamics/PEA_Project/assets/98089768/8f1dadfb-61f1-4d48-b242-1ee0cf6ae62c">
- 채팅이 이루어지는 모습입니다

<br/>
<br/>

## ✅ 체크 리스트

-   [x] Main 브랜치 Pull 받기
-   [x] PR 제목 (컨벤션에 따랐는지) 확인
-   [x] Label 확인
-   [x] Assignees 설정 확인
-   [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-03-03 02:58 UTC, TransparentDeveloper requested changes
고생많으셨습니다.
한가지 공유할 내용이 있어 여기에 말씀드리겠습니다.

저도 얼마전에 지적당한 부분인데, 
한 PR에서 너무 많은 변경을 가할 경우, 리뷰하기가 굉장히 어렵다고 합니다.

이번 PR 에도 굉장히 많은 파일에 변경점이 있는 것 같아,, 조금 보기 어렵습니다.
앞으로는 서로 이런 부분도 고려해서 협업해보죠!!@ 저도 주의하겠습니다.

2024-03-03 02:58 UTC, TransparentDeveloper commented on package-lock.json
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 내용이 같은데 커밋이 됐습니다.
- `package.json` 도 그러하네요?

2024-03-03 02:58 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chatting-overlay.jsx
> +						<ResponsiveIcon icon={BsX} onClick={handleClose} />
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- handleClose 는 불필요한 함수인 것 같습니다.
- 아래처럼 작성해보시겠어요?

```js
<ResponsiveIcon icon={BsX} onClick={onClose} />
```

2024-03-03 03:34 UTC, ijimlnosk commented on package-lock.json
중간에 삭제를하고 다시 설치를 진행해서 그런거같습니다
문제가 될까요?

2024-03-03 03:36 UTC, ijimlnosk commented on src/components/overlay/chatting/chatting-overlay.jsx
> +						<ResponsiveIcon icon={BsX} onClick={handleClose} />
- [fix: 불필요한 함수 제거](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/2df389fe1f5014189c02d5be194805cc25b93f57)
- 수정했습니다

2024-03-03 11:17 UTC, TransparentDeveloper commented on package-lock.json
- 변경을 안했는데, 변경점이 잡히는 건 문제가 될 수 있죠. 
- 일단 충돌사유가 될 수 있습니다. 이 pr이 main에 merge 됐을 때, 지금 package.json 에서 새 의존성 추가해서 작업하는 사람들은 완전히 갈아엎어야 하죠.
- 그리고 진솔이 로컬에서만 다른 설정이라서 이런일이 발생한거면, 이후 협업하는 내내 `package.json` 은 계속 pr 에 등장할 수 있죠,

2024-03-03 11:45 UTC, hayoung78 approved these changes
봤는데.. 제가 잘 본건지 모르겠습니다..?;; ㅠㅠ  굳굳 확인

2024-03-03 11:46 UTC, TransparentDeveloper requested changes
추가 리뷰 남깁니다.

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/index.js
> +// }
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- msw 설정이 주석처리된 이유를 모르겠습니다??

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/libs/axios/base/chat.js
> +export const postChatReadAllByRoomIdx = async ({ room_idx }) => {
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 요청에 싣을 데이터이지만, 함수의 파라미터 받는 부분까지는 컨벤션에 따르는 게 맞을 것 같습니다. 
- 지금 이 상태라면, 함수의 사용부에서도 snake_case 를 써야하기 때문입니다.

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/libs/axios/auth/storage-manager.js
> +	return sessionStorage.setItem(CHAT_TOKEN, chatToken);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 함수 파라미터 전달방법이 컨벤션이 맞지 않습니다.

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/components/overlay/chatting/message-context.jsx
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 이 내용은 `components` > `overlay` 폴더 아래 작성할 내용은 아닌 것 같습니다.
- 이미 `src` > `contexts` 라는 폴더가 있습니다.

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/components/overlay/chatting/message-context.jsx
> + * @returns {JSX.Element}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- `@customhook` 이런 건 컨벤션이 없지 않았나요?
- 팀원들하고 공유되지 않은 걸 사용하시면 코드스타일이 통일이 안됩니다..
- 굳이 사용을 해야한다면 커스텀 훅 선언과 관련해서 jsdocs 이렇게 쓰자고 팀원들한테 얘기를 해주셨어야 할 것 같습니다.

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chatting-overlay.jsx
> +			}
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- console 지워주세요.

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat.jsx
> +			const $isSelf = messageData.nick_name === userInfo.nick_name;
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 변수명 앞에 `$` 이 들어가나요?

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat.jsx
> +const socket = io(process.env.REACT_APP_PEA_CHAT_URL);
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 환경변수 사용하면 노션에 바로 업데이트하고 알려주셔야 합니다.
- main 에 merge 되는 순간 다른 팀원들은 바로 에러 납니다..

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/components/overlay/chatting/chat.jsx
> + * @parameter roomId : String - chatting room 의 id를 받아옵니다.
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 지금까지 타입은 소문자로 시작하도록 작성했습니다. 
- 통일시켜주세요.

2024-03-03 11:46 UTC, TransparentDeveloper commented on src/libs/axios/auth/storage-manager.js
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- storage-manage 파일 위치가 잘못된 것 같습니다.
- `libs` > `{외부라이브러 설정 파일 폴더}` 처음 이렇게 정했는데, storage-manager 는 axios 설정 파일이 아니기 떄문입니다.
- 다시 `utils` 폴더로 원복 시켜주셨으면 좋겠습니다.

2024-03-03 11:51 UTC, ijimlnosk commented on src/index.js
> +// }
아 주석 처리 지우겠습니다.
socket 연결 시 msw에서 핸들러 설정을 하라는 오류가 계속 발생해서 콘솔에 로그가 계속 쌓여서 주석처리 해놓은 것입니다
이 주석 처리를 제거하면 머지 되었을 때, 콘솔에 주의 메시지가 쌓일 수는 있습니다

2024-03-03 12:20 UTC, ijimlnosk commented on src/libs/axios/base/chat.js
> +export const postChatReadAllByRoomIdx = async ({ room_idx }) => {
- [fix: chat parameter 컨벤션에 맞게 조정](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/b722bb96d5e7422309c96425b797e49404e79fcf)
- 수정했습니다

2024-03-03 12:21 UTC, ijimlnosk commented on src/index.js
> +// }
- [fix: msw 실행시켜주는 로직 삭제](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/794ad2c439d5bca9944d8b35da79ad2326938d8d)
- 제거 했습니다

2024-03-03 12:25 UTC, ijimlnosk commented on src/libs/axios/auth/storage-manager.js
> +	return sessionStorage.setItem(CHAT_TOKEN, chatToken);
- [fix: chat token 컨벤션에 맞게 조정](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/a0d77fbe5ce58ba3574a6243289f6a6adf6036c9)
- 수정했습니다

2024-03-03 12:28 UTC, ijimlnosk commented on src/components/overlay/chatting/message-context.jsx
- [move: message-context.jsx 파일 위치 변경](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/9b47c501bedfbc66ff3ae8c719ffd6f7b91198aa)
- 변경하였습니다

2024-03-03 12:32 UTC, ijimlnosk commented on src/components/overlay/chatting/message-context.jsx
> + * @returns {JSX.Element}
- [chore: jsdocs 수정했습니다](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/764caaaea3c8bb0d2bc5be3b428adec175453ba2)
- 수정했습니다

2024-03-03 12:46 UTC, ijimlnosk commented on src/components/overlay/chatting/chatting-overlay.jsx
> +			}
- [refactor: 불필요한 try-catch제거 및 catch 콘솔 제거](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/70139cadb2f26931df0a752a75ff3876010ce4e8)
- catch가 필요한 곳에는 setError로 메세지를 보여주도록 설정했습니다

2024-03-03 13:01 UTC, ijimlnosk commented on src/components/overlay/chatting/chat.jsx
> +const socket = io(process.env.REACT_APP_PEA_CHAT_URL);
환경 변수 업데이트 했습니다

2024-03-03 13:02 UTC, ijimlnosk commented on src/components/overlay/chatting/chat.jsx
> + * @parameter roomId : String - chatting room 의 id를 받아옵니다.
- [chore: jsdocs 오타 수정](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/59eaeeb68c719b98ffa302616d63633ba913c673)
- 수정 했습니다

2024-03-03 13:03 UTC, ijimlnosk commented on src/libs/axios/auth/storage-manager.js
다른 브랜치에서 작업 하겠습니다.

2024-03-04 16:04 UTC, jjjiyoung0130 commented on src/components/overlay/chatting/chat-room-list.jsx
> +const Wrppaer = styled.div``;
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 이건 Wrapper를 쓰려던 거겠죠?

2024-03-04 16:06 UTC, jjjiyoung0130 commented on src/components/overlay/chatting/chat-room-list.jsx
>  const RoomList = styled.div`
이건 현재 사용되고 있는 스타일인가요? 지워진 부분 같아서 여쭤봅니다 :)

2024-03-04 16:17 UTC, jjjiyoung0130 commented on src/libs/axios/base/chat.js
> +	prodId,
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - jsDoc의 parameter도 prodId로 변경해주면 좋을 것 같네요.

2024-03-04 16:19 UTC, jjjiyoung0130 commented on src/libs/axios/base/user.js
> +export const patchUserProfileUrl = async ({ image }) => {
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - jsDoc도 image로 변경해주면 좋을 것 같아요.

2024-03-04 16:23 UTC, jjjiyoung0130 commented on src/libs/axios/base/user.js
> +		page,
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 해당 부분의 parameters는 params로 묶어줘야하지않나요?

2024-03-05 05:09 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
>  const RoomList = styled.div`
네 사용되고있습니다

2024-03-05 05:12 UTC, ijimlnosk commented on src/components/overlay/chatting/chat-room-list.jsx
> +const Wrppaer = styled.div``;
- [fix: 오타 수정 및 jsdocs수정](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/387d55350a58cfb80fa1f051d3afc75bc7779988)
- 수정완료했습니다

2024-03-05 05:12 UTC, ijimlnosk commented on src/libs/axios/base/chat.js
> +	prodId,
- [fix: 오타 수정 및 jsdocs수정](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/387d55350a58cfb80fa1f051d3afc75bc7779988)
- 수정완료했습니다

2024-03-05 05:13 UTC, ijimlnosk commented on src/libs/axios/base/user.js
> +export const patchUserProfileUrl = async ({ image }) => {
- [fix: 오타 수정 및 jsdocs수정](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/387d55350a58cfb80fa1f051d3afc75bc7779988)
- 수정완료했습니다

2024-03-05 05:13 UTC, ijimlnosk commented on src/libs/axios/base/user.js
> +		page,
- [fix: 오타 수정 및 jsdocs수정](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/387d55350a58cfb80fa1f051d3afc75bc7779988)
- 수정완료했습니다

2024-03-05 05:14 UTC, jjjiyoung0130 approved these changes

2024-03-07 04:53 UTC, TransparentDeveloper requested changes
일전에 리뷰 남긴 거 반영해주셔서 감사합니다.!!
근데 추가 리뷰 작성했어요.!!! ㅋㅋㅋㅋ

2024-03-07 04:53 UTC, TransparentDeveloper commented on src/utils/room-data-finded.js
> +};
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- 함수 이름이 `saleData` 인데, 이름만 봐서는 판매상품 데이터를 찾아오는 함수 같습니다.

2024-03-07 04:53 UTC, TransparentDeveloper commented on src/contexts/message-context.jsx
# Request Level
  - [x] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
- socket 잘 몰라서,, 질문 드립니다.
- 제가 얼핏 봤을 때 메시지가 송수신 될 때, 그 값을 프로젝트 전체에 제공하도록 context api 활용한 것 같습니다. (질문1, 이게 맞나요??)
- 만약 이게 맞다면 메시지를 주고 받을 때마다 프로젝트의 모든 로직 및 ui 가 재작성되어 비효율적일 것 같습니다. (질문2, 이렇게 설계하는 게 일반적인....?? 이런 구조로 설계된 프로젝트가 있나요?  참고한 자료가 있다면 첨부 부탁드립니다. 🙇‍♂️ )
- context api 는 많이 비효율적이기 때문에 정말 필요한 경우가 아니라면 사용이 자제하는 게 좋다고 알고 있어요., 이러한 구조를 계획대로 설계하셨더라도, 더 효율적인 구조를 찾아보는 것도 좋을 거 같습니다. 😀

2024-03-07 05:06 UTC, ijimlnosk commented on src/contexts/message-context.jsx
- context를 사용한 이유는 api 노션을 봤을 때, 새로운 메시지가 왔을 때의 상황을 전역상태로 관리하라해서 설정해 둔 것입니다.

- 다른 페이지에 있을 때 새로운 메시지가 온 것을 알아채기 위해서 적용해 놓은 것이긴 한데, 일반적인 방법인지는 모르겠습니다(더 찾아보겠습니다)

- 현재 새로운 메시지가 왔을때 알려주는 기능은 없기때문에 안에있는 내용을 따로 함수로빼서 작업을 해도되긴합니다만 추후 알림기능을 생성할때 참고하기 위해 우선 선 작업 해놓은 내용입니다.

- 구조적인 문제는 더 찾아보도록 하겠습니다

2024-03-07 05:22 UTC, ijimlnosk commented on src/utils/room-data-finded.js
> +};
- [refactor: room-data-finded 의 함수명을 saleData => findRoom으로 변경](https://github.com/PurpleDynamics/PEA_Project/pull/70/commits/b33fb1acf7842d2595a4b7a9ec6c509166697072)
- 수정했습니다

2024-03-07 05:55 UTC, TransparentDeveloper approved these changes

2024-03-07 05:58 UTC, merged