PR/PR-85: ProductList 데이터 패칭 작업했습니다.
PurpleDynamics/PEA_Project pull request #71
Opened 2024-03-03 14:51 UTC by TransparentDeveloper

## 🎯 작업 내용

- [feat: 행정구역 이름 추출 함수 작성](https://github.com/PurpleDynamics/PEA_Project/commit/f88e72b3690c6d4cdcf6b5bb20285a761ad6e04f)
  - 서버에서 넘어온 주소 중, 특정 행정구역 정보를 추출하는 함수 작성했습니다.
    - `extractRegionalUnitDong` : '-동' 단위 주소만 출력
    -  `extractRegionalUnitGu` : '-구' 단위 주소만 출력

- [feat: getProduct(), react-query 활용 query 최적화](https://github.com/PurpleDynamics/PEA_Project/commit/2c6903487bfc850f9c45d8a5f1425b0fedd270b9)
  - react-query 사용해서, `useProductList` 작성했습니다.
    - '중고'.'무료' 카테고리의 각각 8개 상품 정보를 받을 수 있는 `getProduct` 함수와 관련하여 query 최적화 진행했습니다.

- [feat: product-list-page 데이터 패칭](https://github.com/PurpleDynamics/PEA_Project/commit/50d72db495d17c8f4aa5ee7be5fb75c68e9ecb57)
    - <img width="735" alt="스크린샷 2024-03-03 오후 11 47 06" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/1b52178b-fb29-489b-b7b7-2cb898b31790">
   - 상품 태그 중, 다음의 배열에 그 값이 없다면 모두 '기타중고물품' 으로 분류되어 출력하도록 했습니다.
     - ["디지털기기","생활가전","가전/인테리어","생활/주방","유아동","유아도서","여성의류","여성잡화","식물","남성의류/잡화","뷰티/미용","스포츠/레저","취미/게임/음반","도서","티켓/교환권","가공식품","반려동물용품","기타중고물품"]

<br/>
<br/>

## ✅ 체크 리스트

-   [ ] Main 브랜치 Pull 받기
-   [ ] PR 제목 (컨벤션에 따랐는지) 확인
-   [ ] Label 확인
-   [ ] Assignees 설정 확인
-   [ ] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!!

### 👍 문제가 없다고 생각된다면...

1. "FileChanged" Tab 으로 이동합니다.
2. "Review Changes" Button 클릭합니다.
3. Comment 입력 (**\*Optional**) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...

1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.

```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```

2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-03-04 05:43 UTC, jjjiyoung0130 approved these changes
regional-word-extractor.js의 jsDoc에 parameter's'로 쓰인거나 example에 console이 consol로 적힌 거 외에는 깔끔해 보입니다 :)

2024-03-04 07:07 UTC, ijimlnosk approved these changes
고생하셨습니다

2024-03-04 07:51 UTC, hayoung78 approved these changes
송강 늬집아들인지 참 잘생겼네

2024-03-04 10:11 UTC, snkchan requested changes
굉장합니다...역시윤신센세....

2024-03-04 10:11 UTC, snkchan commented on src/utils/regional-word-extractor.js
> +		addressSplit.endsWith("동")
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안돼요~!"
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
구를 추출하는 함수인데 이렇게하면 동을추출하는거아닌가요??!?!?!
추가로 두함수에서 parameter를 입력받아 사용하면 하나의 함수로 동작할 수 있지 않을까 싶습니다만.....

2024-03-04 23:59 UTC, TransparentDeveloper commented on src/utils/regional-word-extractor.js
> +		addressSplit.endsWith("동")
- [refactor: 행정구역 추출 함수 변경](https://github.com/PurpleDynamics/PEA_Project/pull/71/commits/e7af5a6f387164aa919cb57ffa7510bdd08cb61f)
  - 좋은 지적 감사합니다.! 👍
  
- [chore: JsDocs 컨벤션에 맞도록 수정](https://github.com/PurpleDynamics/PEA_Project/pull/71/commits/0fe2adda41d6c9266741d56ec514740f5bc2005c) 
  - @jjjiyoung0130 지영님 말씀하신 부분도 수정했습니다.

2024-03-05 11:58 UTC, snkchan approved these changes
고생하셧습니다 지적할게 없는 완벽한 코드였습니다.

2024-03-06 15:08 UTC, merged