PR/PD-37: 공용 컴포넌트 "CategoryToggle" 작성했습니다.
PurpleDynamics/PEA_Project pull request #8
Opened 2024-01-24 12:44 UTC by TransparentDeveloper

## 🎯 작업 내용

![CategoryToggle](https://github.com/PurpleDynamics/PEA_Project/assets/50646145/580b36e4-379c-487f-94bc-d9cd7f6f41c1)

- [design: 공용컴포넌트 CategoryToggle 생성](https://github.com/PurpleDynamics/PEA_Project/commit/a1322923a352f4f0bfe9674ca205ebc294e54454)
  - 호버/클릭 시, 색상이 변경 및 추가적인 로직을 수행하는 토글입니다.
  - `callbackFunc` 는/은 반환형이 없는 함수를 전달하셔야 합니다.
  - 토글이 활성화 되어있는지에 대한 상태를 자체적으로 관리합니다. 

- [feat: 카테고리 이름에 따라 토글 색상 변경 기능 추가�](https://github.com/PurpleDynamics/PEA_Project/commit/44568e1f0f606c8eda5b4ffd1fc890d2f8a21c30)
  - 전달된 `categoryName` 에 의해, 호버/클릭 시 색상이 결정됩니다.
  - `children` 이 string 타입으로 전달되지 않을 경우, "no_string" 문자열이 카테고리 이름으로 출력됩니다.

<br/>
<br/>
  
### ✋ 사용하려면,,?

#### 정상 사용 시,
- _코드_
```js
<CategoryToggle>test</CategoryToggle>
```

- _출력물_
<img width="220" alt="정상사용" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/2ced0d23-d44e-439a-88cb-f605b409588f">

------
  
#### 잘못된 사용 예시 1 - 카테고리 이름이 전달되지 않은 경우
- _코드_
```js
<CategoryToggle></CategoryToggle>
```

- _출력물_
<img width="220" alt="잘못된 사용" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/2de71795-c80a-4958-81a8-dbd51021fd08">

------
  
#### 잘못된 사용 예시 2 - 카테고리 이름을 string 타입으로 전달하지 않은 경우
- _코드_
```js
<CategoryToggle>
  <h1>test</h1>
</CategoryToggle>
```

- _출력물_
<img width="220" alt="잘못된 사용" src="https://github.com/PurpleDynamics/PEA_Project/assets/50646145/2de71795-c80a-4958-81a8-dbd51021fd08">

<br/>
<br/>

## ✅ 체크 리스트

- [x] Main 브랜치 Pull 받기
- [x] PR 제목 (컨벤션에 따랐는지) 확인 
- [x] Label 확인
- [x] Assignees 설정 확인
- [x] Reviewers 설정 확인

<br/>
<br/>

## 😭 꼭 리뷰 남겨주세요.!! 

### 👍 문제가 없다고 생각된다면...
1. "FileChanged" Tab 으로 이동합니다.
3. "Review Changes" Button 클릭합니다.
4. Comment 입력 (__*Optional__) 후, "Approve" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>

### 🙏 코드 수정 요청을 원하신다면...
1. 아래의 템플릿을 복사 하여, 위의 `2단계` 까지 진행해주세요.
```text
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description

```
2. Comment 에 템플릿을 붙혀넣고, `where` / `how` / `why` 3하 원칙(?) 에 따라, 구체적인 요청사항을 작성해주세요.
3. "Request changes" 선택하고 "Submit Review" 버튼을 클릭합니다.

<br/>
<br/>

2024-01-24 12:49 UTC, ijimlnosk approved these changes
확인했습니다

2024-01-24 13:23 UTC, snkchan reviewed
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [x] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [ ] S : "🤷 수정하면 좋지 않을까요?"

# Description
카테고리가 최대6글자까지 입력받을 수 있게할 예정인데 그것에대한 코드가 없는거같아서 
이부분은 추후에 카테고리직접입력하는 input에서 작업을 할건가요??

2024-01-25 04:14 UTC, TransparentDeveloper reviewed
추가 변경 사항에 대해 설명 남깁니다.

2024-01-25 04:14 UTC, TransparentDeveloper commented on src/components/category-toggle.jsx
> +		}};
- [chore: ArrowFunction 반환값에 대한 컨벤션 적용](https://github.com/PurpleDynamics/PEA_Project/pull/8/commits/eb13abd368d867a5bacefc8aaff2c8ed51b276bb)
  - 반환값에 대해 무조건 'return' 키워트 작성하자는 컨벤션을 미적용 했었습니다. 수정했습니다.

2024-01-25 04:14 UTC, TransparentDeveloper commented on src/components/category-toggle.jsx
- [move: 확장자 변경, '.js' -> '.jsx'](https://github.com/PurpleDynamics/PEA_Project/pull/8/commits/dfe6e3f8c5eb3ad8cbd58414d8524d0f8b5526ed)
  - JSX 태그를 사용했습니다. 기존에 merge 된 `pages` 하위의 파일과 같이 '.jsx' 로 확장자 변경했습니다.

2024-01-25 07:19 UTC, jjjiyoung0130 commented on src/components/category-toggle.jsx
> +	if (typeof children != "string") children = "no_string";
# Request Level
  - [ ] N : "🔥 이대로 Merge 하면 안되요~!" 
  - [ ] M : "🥹 고치면 분명 나아질 게 분명합니다.."
  - [x] S : "🤷 수정하면 좋지 않을까요?"

# Description
 - 공백만 입력하는 경우도 string인 걸로 알고 있는데, 앞뒤 공백 및 공백만 입력하는 경우에 대해 공백을 제거하는 로직을 추가하면 좋지않을까요?
 
   ``` 
   else children = children.trim();
     ```

2024-01-25 07:22 UTC, jjjiyoung0130 requested changes
의견 남겼습니다. 확인 부탁드립니다.

2024-01-25 15:15 UTC, snkchan approved these changes
확인했습니다.

2024-01-25 15:17 UTC, keeprok approved these changes
지영님 부분만 체크되면 될거같아여~!

2024-01-25 15:19 UTC, KR-HeoJU approved these changes

2024-01-25 15:26 UTC, TransparentDeveloper commented on src/components/category-toggle.jsx
> +	if (typeof children != "string") children = "no_string";
- [feat: 공백 문자로도 토글 생성되도록 설정](https://github.com/PurpleDynamics/PEA_Project/pull/8/commits/b3cd7ac1b18d2e262eff7223427e823268233c6c)
  - 너무나 좋은 지적 감사합니다. 거기까지 생각을 못했네요..
  - 'else' 는 제외하고 작성했습니다. 들어온 문자열이 'test    ' 인 경우에도, trim 이 필요하기 때문입니다.
  

https://github.com/PurpleDynamics/PEA_Project/assets/50646145/bfabc9b0-e24b-4996-b237-640d81e61eab

2024-01-26 03:55 UTC, jjjiyoung0130 commented on src/components/category-toggle.jsx
> +	if (typeof children != "string") children = "no_string";
확인했습니다👍

2024-01-26 03:55 UTC, jjjiyoung0130 approved these changes

2024-01-27 03:48 UTC, merged